### PR TITLE
[TS] LPS-144294 Introduce configurable build identifier instead of build number in static resource URLs

### PR DESCRIPTION
**Pull request by istvansajtos**
Hi Eric,

This is the continuation of https://github.com/ericyanLr/liferay-portal/pull/255. Please let me know if you have any further observation.

Thank you very much,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
@ericyanLr , do you have any concern about giving out the fix in SDH?

Thank you!

**Comment by istvansajtos** [comment]
ci:help

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
Hi @istvansajtos ,

**Possible Concern**
One concern I have regarding this fix, is that users who utilize this property and are going through an upgrade, may encounter the original issue: [LPS-13514](https://issues.liferay.com/browse/LPS-13514)

Can you confirm whether this is the case? 

**Note:** I did notice that in the property description, you did mention:
> If specified, it must be changed when upgrading to a newer release.

**Thoughts**
Basically, the concern is whether introducing this fix basically re-introduces [LPS-13514](https://issues.liferay.com/browse/LPS-13514).

Even though the property description mentions it should be changed during an upgrade, what are the chances that most users who introduced their own identifier for their Liferay instance, will forget about this and not actually change this during the upgrade?

If that's the case, then I think we need to evaluate this fix some more, so that it's a complete fix.

- e.g. do we need to update our documentation to inform users? do we need to update our upgrade guides?

**Is this the proper fix?**
Another option to consider is re-evaluating the old issue: ([LPS-13514](https://issues.liferay.com/browse/LPS-13514))
- e.g. since this is a really old fix, how does the fix actually work? what are these cached JS files? are these cached JS files deletable? should these cached JS files be deleted during an upgrade? etc.

These are just random questions that came to mind.

If this hasn't been explored yet, I would suggest looking into this some more, with the hope to find a fix that is both easily maintainable and less likely to introduce friction for users who are upgrading, if possible.

**Regarding your question:**
> do you have any concern about giving out the fix in SDH?

This decision is ultimately up to the Support team, and so I would suggest discussing with your team if you want to push for this.

As for my personal opinion, I would avoid introducing this as an SDH if possible, since this relies on adding a portal property. And if it turns out that engineering doesn't accept this fix (or ends up renaming the portal property), the customer may have a floating portal property that has no effect.

And if this is a critical issue, I would suggest looking at the original root issue: [LPS-13514](https://issues.liferay.com/browse/LPS-13514) and see if there's something safe/reasonable that can be done to help unblock the customer.
- e.g. would something as simple as deleting the cached JS files, resolve the issue? Is it easy/safe to delete the cached JS files? etc.

Please let me know if you have any further questions.
Thanks!

**Comment by istvansajtos** [comment]
Thanks for sharing your thoughts @ericyanLr ! I think the best would be to clarifying all the questions and concerns in frame of a PTR ticket. There I can share more details and we can evaluate the options. Soon I will open a ticket.

**Comment by jcampoy** [comment]
see https://github.com/liferay-frontend/liferay-portal/pull/1985

calculated timestamp from the newest deployed file should be enough to avoid browser cache issues between versions / upgrades and patches/fix-packs.

**Pull request closed without merging**
