### PR TITLE
LPS-116291: portletResource only use in case PortletConfiguration for referencing the right portlet

### PR DESCRIPTION
**Pull request by dacousalr**
https://issues.liferay.com/browse/LPS-116291

From @holatuwol

> From @binhtran92
> 
> > I found that the `portletResource` was introduced because the `PortletConfiguration` is loaded from different porlet. So they need that param to get preferences from the right portlet, as said from ticket https://issues.liferay.com/browse/LPS-44445.
> > 
> > However, I think when doing the refactor dependency at ticket https://issues.liferay.com/browse/LPS-55833, the author may assume that the PortletConfiguration is on all plugins (Portal and Market) then he decided to remove the condition.
> > 
> > So, my solution is, only set the portletResource if the portlet is PortletConfiguration. If not, just leave it as it is like the time this param was introduced.
> 
> Looking through the code base, the only places where we create a URL with the `portletResource` parameter are the following portlets, derived with the following bash script:
> 
> ```bash
> git ls-files modules | tr '\n' '\0' | xargs -0 grep -Fl 'setParameter("portletResource"' | sed 's@/src/.*$@@g' | uniq
> ```
> 
> * modules/apps/asset/asset-publisher-web
> * modules/apps/blogs/blogs-web
> * modules/apps/bookmarks/bookmarks-web
> * modules/apps/document-library/document-library-web
> * modules/apps/export-import/export-import-changeset-taglib
> * modules/apps/export-import/export-import-web
> * modules/apps/journal/journal-content-web
> * modules/apps/journal/journal-web
> * modules/apps/layout/layout-admin-web
> * modules/apps/layout/layout-content-page-editor-web
> * modules/apps/plugins-admin/plugins-admin-web
> * modules/apps/portal-workflow/portal-workflow-task-web
> * modules/apps/portlet-configuration/portlet-configuration-css-web
> * modules/apps/portlet-configuration/portlet-configuration-web
> * modules/apps/roles/roles-admin-web
> 
> There were a lot of matches, so I asked @binhtran92 to double-check these to make sure that there wasn't an accidental regression. According to his investigation, there shouldn't be any downstream effects from this change.
> 
> From @binhtran92
> 
> > I have review many class related to `git ls-files | tr '\n' '\0' | xargs -0 grep -F 'setParameter("portletResource"'`. As I know currently `portletResource` using in many purpose. Mostly using for notify the message. Methods using for URL adding the `portletResource` is indicate that where this url come from.
> 
> One of the other things that this change may affect is anything using `PortletDisplay.getPortletResource()`, which was also checked:
> 
> From @binhtran92
> 
> > Our solution mainly related to features which are using the `portletDisplay` then I using `git ls-files | tr '\n' '\0' | xargs -0 grep -F 'portletDisplay.getPortletResource()`, I go through these classes and I can see all classes is related to the Configuration Portlet
> 
> In this case, they were either directly tied to a configuration path (configuration was part of the package path), or in the case of `JournalWebRequestHelper`, were only invoked by a configuration class.

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
**Quick Update**
Overlooked this PR, will try to take a look tomorrow.

**Comment by ericyanLr** [comment]
Hi @dacousalr @holatuwol @binhtran92 ,

Thanks for the detailed notes. I took a look at the mentioned refactor ticket: [LPS-55833](https://issues.liferay.com/browse/LPS-55833)

From my understanding, one of the big changes from this refactor was to **remove dependencies to portlet configuraton**. For instance:
- this set of commits: https://github.com/liferay/liferay-portal/compare/ba64d0919b368c7fbc4644cbfe9bfcf10a55ace0...26701930859c96875c69a46fffebfe4cbdf7da74
- this commit: https://github.com/liferay/liferay-portal/commit/249bd739d3c65ddb68cc6c190b5ab28f56732f7e
- etc.

Looking at your change, this would basically:
- Add back a dependency to the **portlet configuration** in render_portlet.jsp
- Partially revert this commit: https://github.com/liferay/liferay-portal/commit/26701930859c96875c69a46fffebfe4cbdf7da74

**Questions**

1. Can you help verify is this would be the case?
2. If so, is the current logic of the portion of code that's being changed in render_portlet.jsp in question?
3. If not, if we follow the steps to reproduce, what is the expected value of portletResource in that portion of code? 
    - For instance, is the value for portletResource incorrect when SPA is disabled?

**Note:** I haven't actually tested the steps to reproduce, but just wanted to get more context before I dive in further in reviewing the changes. 

Please let me know your thoughts.
Thanks!

**Comment by binhtran92** [comment]
Hi @ericyanLr ,
I would like to answer you questions:
1. Yes
2. It is hard to get the full idea of the previous changes, from my understand, `portletResource` now can using at all `portlet` not only the `configurationPortlet`. However in the `render_portlet.jsp` a logic is related to the `PorletDisplay.java` which is contains
 contextual information about the currently rendered portlet, so the `portletResource` have to be the `portletId` of current portlet in case it is not the `configurationPortlet`.
3. It's not related to the SPA, we can reproduce it without disable SPA. `portletResource` value will come from the queryParam on the URL.

Thank you.

**Comment by ericyanLr** [comment]
Hi @binhtran92 ,

Thanks for answering my questions.

**Update LPS-116291 - Not related to SPA**
Since this is not related to SPA and can be reproduced without SPA, can we update the ticket description and title for [LPS-116291](https://issues.liferay.com/browse/LPS-116291), to not require SPA? 

**Re-asking Question 2**

> If so, is the current logic of the portion of code that's being changed in render_portlet.jsp, not working properly?

Can you help provide more details regarding this question?

Based on your changes, does that mean this portion of code (to assign the portletResource), should only apply if the portlet is related to the **PortletConfigurationPortlet**?

----

I haven't had time to dive deeper into this, hopefully have some time tomorrow.
But, your responses have been helpful in understanding about the issue.

Thanks!

**Comment by binhtran92** [comment]
Hi @ericyanLr ,
1. I updated the LPS-116291 title since it's not related to SPA.
2. About the question: 
- Because we add the web content from menu of `ProductNavigationControlMenuPortlet`, then when the web content is created, it will redirect back to site with the URL have param `portletResource` is `ProductNavigationControlMenuPortlet`.
The current logic will bases on that id to get the `PortletInstanceConfiguration`. Not all portlet will effects by this wrong configuration unless they need information from `PortletInstanceConfiguration` to display.
- From my understand, `PortletConfigurationPortlet` is loaded from different portlet so they need that param to get preferences from the right portlet. Because it is related to render part, then we should determine which portlet is triggered to render to set the `portletResource` correctly. This is what my changes means.

**Comment by ericyanLr** [comment]
Hi @binhtran92 ,

Thanks for updating the ticket and for your responses to my questions.

I have added a comment of my analysis on the LPP ticket.

Feel free to let me know if you have any questions.
Will be closing out this PR.

**Pull request closed without merging**
