### PR TITLE
LPS-106585 Add queryString parameters to redirect URL

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @crodriguezy ,

After discussing this issue with @achaparro, we had a few thoughts:

1. Should we only add the query parameters when the Link to Layout type is used?
2. Should we add the query parameters only for redirects and not forwards?
3. Or should we add the query parameters for both? (Which is your current proposed fix)
4. Would adding query parameters to redirects be a potential security concern?

If you have any thoughts on the questions above, feel free to share.

I'll continuing taking a look at this PR tomorrow and may create a PTR ticket for the Security team to address question # 4.

**Comment by crodriguezy** [comment]
Hi @ericyanLr ,

Here are my thoughts on your questions:

1. I guess your question here actually is if we should add the query parameters when the **Link To URL** type is used (which is the current case). Am I correct? If so, and now that you mention it I think it makes sense that **Link to Page** types and do the same and keep the parameters. For example, if a _Link To Page_ A links us to a _Link To URL_ B page, which at the same time redirects to an external page C, it can be the case that the original parameters set in **A** are important for **C**. What do you think?

2 and 3. I'm not sure about these. Seeing that multiple failed attemps were done to fix this in a general way (forwards and redirects), I also took into account both. But if you think it is better to just focus on the customer's particular case (redirects), there is no problem to change it.

4. This is the big question here. I needed someone's supervisoring mainly because among others, I was concerned about security issues that adding parameters to URL may imply. Thank you for taking care of the PTR.

Thank you!

**Comment by crodriguezy** [comment]
Ey @ericyanLr , by the way, and totally off-topic (sorry!!) I just wonder if you as SME of his team could tell me if Shuyang is on PTO? I'm  pending on a PR sent to him 10 days ago and it is still unattended, which is strange. 
Thanks again!

**Comment by ericyanLr** [comment]
Hi @crodriguezy ,

Thanks for your input, I have created PTR-1636 to ask for input from the security team. Let's wait for their response first and go from there.

As for Shuyang, he should be back sometime later this week. In the meantime, you can ask Tina to help review the PR.

Please let me know if you have any questions.
Thanks!

**Comment by crodriguezy** [comment]
Hi @ericyanLr ,

I take the PTR's response as a "it is ok to go with adding query parameters for Link To URL / Link to Page redirects". But I'm not sure about the forwards. What do you think? Do you take his answer meaning for both?
Should we focus our fix just on redirects and not forwards? 

Thank you!

**Comment by ericyanLr** [comment]
Hi @crodriguezy ,

**In regards to:**

> I take the PTR's response as a "it is ok to go with adding query parameters for Link To URL / Link to Page redirects". 

If you feel your issue should take into account both **Link to URL** and **Link to Page**, then I would consider looking at both. However, if you feel that your issue should only address **Link to URL**, then I would consider just looking at **Link to URL**

**In regards to:**
> But I'm not sure about the forwards. What do you think? Do you take his answer meaning for both?

To me, I think the response in the PTR seems to indicate that for the **Link to URL** scenario, including query parameters in the redirect URL is learning towards: not a security concern.

I think the option to introduce the behavior to include query parameters to the redirect URL, for when the **Link to Layout** layout type is used, would be worth exploring. I think this would be a safer option.

**In regards to:**
> Should we focus our fix just on redirects and not forwards?

If we choose to go the route above, the logic of whether to include query parameters would then be dependent on the **Layout type** and not whether the URL is a **forward** or **redirect.**

Though, whether the URL is used as a forward or redirect may be factors to consider.

Hope that helps!

**Comment by crodriguezy** [comment]
Hi @ericyanLr ,

Thanks a lot for all your help analyzing the case. After exploring some other options and ways to implement it, I've finally decided to fix it for the specific case of LPS-106585 (Link to URL types), since it will be safer and in order to minimize the number of possible regressions it may cause...(I hope it is safe enough and none is caused :D). 
If everyting goes fine with the automatic tests, I will resend [this PR](https://github.com/crodriguezy/liferay-portal/pull/168) to Tina (I will probably add some test), in case you want to have a look.

Thank you again!

**Comment by ericyanLr** [comment]
Hi @crodriguezy ,

Sounds like a plan to me, thanks for the update!

I took a look at the PR and wanted to share a few thoughts:

- Regarding: ```Map<String, String[]> parameterMap = httpServletRequest.getParameterMap();```
  - I noticed there's a method: **HttpImpl::parameterMapFromString** and **HttpImpl::getParameterMap**
    - Reference: [HttpImpl.java#L797](https://github.com/liferay/liferay-portal/blob/7.3.1-ga2/portal-impl/src/com/liferay/portal/util/HttpImpl.java#L797)
  - Not sure if just retrieving the parameters from the query string makes a difference. But, wanted to mention it in case you want to explore that more.
- Regarding: ```actualURL = HttpUtil.setParameter(actualURL, entry.getKey(), entry.getValue()[0]);```
  - I noticed theres **addParameter** and **setParameter**
    - It looks like **addParameter** appends whereas **setParameter** replaces.
      - This may be something to consider.
    - A scenario that came to mind:
      - Create page using Link to URL: **linkpage**
        - Use a URL with parameters: 
          - e.g. http://localhost:8080/group/control_panel/manage?p_p_id=com_liferay_users_admin_web_portlet_UsersAdminPortlet
        - Can play around to see what behavior you want to happen if the Link to URL itself already has URL parameters and the user appends additional URL parameters (that may or may not conflict)
          - e.g. http://localhost:8080/web/guest/linkpage?p_p_id=com_liferay_roles_admin_web_portlet_RolesAdminPortlet

Just wanted to share my thoughts.

Feel free to let me know if you have any questions!

Best,
Eric

**Comment by crodriguezy** [comment]
Hi @ericyanLr ,

Thanks for sharing your thoughts. I analyzed them:

- About `Map<String, String[]> parameterMap = httpServletRequest.getParameterMap();`: I explored the options you mentioned and I finally decided to do it that way since I needed less api calls to get the expected results.

- About the specific scenario where you configure a query string parameter that's then typed again by the user in the URL. Before deciding to use the set or add method of HttpImpl, I checked the current behaviour after following the next steps:

1. Create a widget page "test" and add a queryString parameter in the advanced config: **param=yes**
2. Type in the URL the following: http://localhost:8080/web/guest/test?**param=no** an press enter
3. Check in the network tab of the browser tools the value of **param** in the request: param=**no**

So I think the expected result of your example should be aligned with the observed behaviour of the above: to be redirected to http://localhost:8080/web/guest/linkpage?p_p_id=com_liferay_roles_admin_web_portlet_RolesAdminPortlet and the method to be used in this case is **setParameter**

Thank you again :)

**Comment by ericyanLr** [comment]
Hi @crodriguezy ,

np! Thanks for sharing your findings!

**Pull request closed without merging**
