### PR TITLE
Lps 154310

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-154310

The issue here is that when a user is added to a user group which is added as a member to an Asset Library, then that user does not get VIEW access to the Asset Library.
This is due to the userBag's user groups not accounting for memberships associated with user groups.

To fix the issue, I did an extra check for user group memberships that the user is added to.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Looking through the history of this class, it looks like there was a lot of effort put towards consolidating a lot of the permission check logic into the method: `doGetRoleIds`.

The `doGetRoleIds` method is also called in the method with the changes from your PR.

**Question**
Do you know if the proposed logic you are adding, should also be accounted for in `doGetRoleIds`? Or is it mainly just applicable to the `isGroupMemberImpl` method?

**Comment by noornajj** [comment]
Hi @ericyanLr 

I believe the `doGetRoleIds` method accounts for the user group roles. However, the `isGroupMemberImpl` method only checks for the general "Site Member" role in the returned list. The role id for an Asset Library member is different. 
And the problem in `doGetRoleIds` is that userBag.getUserGroups and userBag.hasUserGroup will not account for groups associated with Asset Library user groups so that the "Site Member" role is included. However, looking at `doGetRoleIds`, I can probably add an `if (group.isDepot())` and move the logic there and have the "Site Member" role added to the `roleIdsSet`
That being said, even though the code is moved to `doGetRoleIds`, this will only be applicable to `isGroupMemberImpl`

Theoretically, the other `isGroup*Impl` methods may also encounter the same issue for user groups associated with Asset Libraries but I haven't tested them. If yes, then I think they can be fixed by adding another check for the associated Asset Library role. For example in `isGroupOwnerImpl`, check if the user has role `DepotRolesConstants.ASSET_LIBRARY_OWNER` when `group.isDepot()` is true
I didn't look too much into the code for the other methods but this is what I'm thinking. And I don't think looking into this further would be directly related to this issue

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Thanks for the explanation, since this logic is only applicable for depot related assets, I think the better place to add additional logic would be in the [DepotPermissionCheckerWrapper.java](https://github.com/liferay/liferay-portal/blob/7.4.3.27-ga27/modules/apps/depot/depot-service/src/main/java/com/liferay/depot/internal/security/permission/wrapper/DepotPermissionCheckerWrapper.java)

For your particular case, since you are focused on `isGroupMemberImpl`, we can take a look at the [isGroupMember](https://github.com/liferay/liferay-portal/blob/7.4.3.27-ga27/modules/apps/depot/depot-service/src/main/java/com/liferay/depot/internal/security/permission/wrapper/DepotPermissionCheckerWrapper.java#L161-L179) method.
- We can see that once the AdvancedPermissionChecker call ([super.isGroupMember(groupId)](https://github.com/liferay/liferay-portal/blob/7.4.3.27-ga27/modules/apps/depot/depot-service/src/main/java/com/liferay/depot/internal/security/permission/wrapper/DepotPermissionCheckerWrapper.java#L168)) returns false, we run additional logic by calling [_isGroupMember(_groupLocalService.fetchGroup(groupId))](https://github.com/liferay/liferay-portal/blob/7.4.3.27-ga27/modules/apps/depot/depot-service/src/main/java/com/liferay/depot/internal/security/permission/wrapper/DepotPermissionCheckerWrapper.java#L172) method.

I think the logic you are trying to modify would be better placed in the `_isGroupMember` method: [DepotPermissionCheckerWrapper.java#L297-L314](https://github.com/liferay/liferay-portal/blob/7.4.3.27-ga27/modules/apps/depot/depot-service/src/main/java/com/liferay/depot/internal/security/permission/wrapper/DepotPermissionCheckerWrapper.java#L297-L314)

Also, you mentioned there may be additional checks to be added for related `isGroup*Impl` methods, such as `isGroupOwnerImpl`. In that case, you can explore the `isGroupOwner` method in this class as well if you would like to look into this further.

**Findings while debugging**
I also did some debugging and added a breakpoint here: [DepotPermissionCheckerWrapper.java#L306](https://github.com/liferay/liferay-portal/blob/7.4.3.27-ga27/modules/apps/depot/depot-service/src/main/java/com/liferay/depot/internal/security/permission/wrapper/DepotPermissionCheckerWrapper.java#L306)

And for the roleIds, one of the roles is `Asset Library Connected Site Member`. Currently, this logic only checks for the role `DepotRolesConstants.ASSET_LIBRARY_MEMBER`. 

A suggestion would be to check if the `Asset Library Connected Site Member` role should also be accounted for. If so, this could be an alternative solution and we would be able to continue to rely on the `getRoleIds` method.

Please let me know if you have any questions.
Thanks!

**Pull request closed without merging**
