### PR TITLE
Lps 161738

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-161738

The issue here is that the Private Pages tab was being set to visible based on whether the SCOPED group had private pages created. However, the Portlet URL for the tab was being generated off of the REFERRER group. This caused a null pointer error to occur and the portlet to become unavailable when the Private Pages tab is clicked. This is because the URL is trying to navigate to the private pages of a group that does have any private pages.

To fix the issue, I had the Private Pages tab work similar to the Public Pages so that it will always be visible but will show "No pages available" if the group doesn't have any pages.
Based on how the [PortletURL](https://github.com/noornajj/liferay-portal/blob/2173b7690c4205ef30cabbadc4c7fecdd599f193/modules/apps/item-selector/item-selector-web/src/main/java/com/liferay/item/selector/web/internal/ItemSelectorImpl.java#L335) gets generated, it intentionally sets the group of all tabs, other than the selected tab, to the referrer group. Therefore, it would make sense that the visibility of the Private Pages tab should not be dependent on the SCOPED group.

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Just wanted to confirm, does this fix still apply to the scenario in the LPS ticket or do we need to update the LPS ticket?

Also, maybe we can add additional info in the commit message, regarding the new proposed logic, to help the reviewer better understand the changes.

**Comment by noornajj** [comment]
Hi @ericyanLr 

Sorry, I forgot to update the LPS. I just changed the summary and steps to better reflect the issue and expected behavior. 

Does something like this work for the commit?
_LPS-161738 Have the Private Page tab always be visible and not dependent on whether they exist on the scoped group. This matches the logic for generating the URLs for the tabs where they are not dependent on the scoped site but the referrer site._

**Comment by ericyanLr** [comment]
Hey @noornajj ,

Sorry the the confusion, I was referring more to the **isLayoutSetPrototype** and **isPrivateLayoutsEnabled** logic.
- The current commit message explains why we are removing the pageCount logic, but does not explain why we are replacing it with this logic.

**Comment by ericyanLr** [comment]
Edit: You can also add that explanation on a separate line, if you would like.

I think it would just be helpful for the reviewer and any developers who may view this commit message in the future.

**Comment by noornajj** [comment]
Hi @ericyanLr,
I have updated the commit message

**Comment by ericyanLr** [comment]
Thanks @noornajj !

**Comment by ericyanLr** [comment]
Reviewed and sent to Echo Team for further review: https://github.com/liferay-echo/liferay-portal/pull/9590

**Pull request closed without merging**
