### PR TITLE
LPS-155839: DDMTemplates no longer displaying in escaped format, no longer double escaped

### PR DESCRIPTION
**Pull request by jakesliwka**
https://issues.liferay.com/browse/LPS-155839

The issue is caused when the user creates a Template in Web Content. If the user used certain characters (such as &, ", ', < >, etc), the title of the Template would display correctly at the top, but once the user navigates back to the Templates page to view all of the templates, the titles would be displayed in escaped format. 
When viewing how the title was being called, it was called in the _view_ddm_templates.jsp_ by creating a vertical card based off of an object referencing the DDMTemplate, automatically generating all of its content. When it is used this way, the HtmlUtil.escape is unnecessary and only directly impacts the name. 
This was tested and verified by giving the templates JavaScript names, such as "<script>alert("test");</script>" to see if it would execute, however it did not, showing that the way that the templates are being called does not require an escaped format. 
After going through and verifying everywhere else that the titles of DDMTemplates are being retrieved, most of them are used the same exact way, and those that are different are already formatted with an HtmlUtil.escape during the call. So, returning the escaped format is only impacting the name. 
This bug was tracked to JournalDDMTemplateVerticalCard.java and JournalSelectDDMTemplateVerticalCard.java where the getName function for the Templates was being used. This fixes the return statement so that it no longer returns the escaped version and allows for the template titles to be displayed properly with any characters.
In the implementation of VerticalCardTag.java, the title returns escaped by default. So, by passing an escaped format in the getTitle method, it actually is escaping the title twice.

The issue **is** reproducible in other areas that utilize the VerticalCard, however only the ones that are called similar to those in _view_ddm_templates.jsp_

### CODE REVIEW

**Comment by jakesliwka** [comment]
ci:test:sf

**Comment by jakesliwka** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @jakesliwka ,

From my understanding, based on your fix, you were able to identify a pattern in the VerticalCard taglib that would encounter the issue that is described on the ticket.

I understand that many components may be utilizing this VerticalCard system (e.g. blogs, journal, layout, etc.) that may also be experiencing this same issue. And looking at your current approach, it seemed as if the goal is to just resolve this for the cards related to journal, which is fine.

However, I noticed that you are only resolving this issue for a select few cards in the journal component. For instance, this issue isn't being fixed for JournalArticleHistoryVerticalCard. And so, to me, your fix seems incomplete or it's unclear why we are only targeting these select few cards or whether the plan really is to target the cards related to journal.

And so, it would be great if you can provide a more complete solution or if only a few cards are involved, then an explanation as to why we only need changes to these select few cards, would be helpful for the reviewer.

Please let me know your thoughts and if you have any questions.
Thanks!

**Comment by jakesliwka** [comment]
Hello @ericyanLr ,

Thank you for the response!

To answer your question, the reason that these changes were made was to make the changes that were directly impacting the customer's original issue which was with DDM Templates specifically. Upon doing the fix, it was found that this change could be applied in many different areas that the vertical card is implemented, however this would take a great deal of time and the solution was to deliver the fix to the customer first, staying specific to their issue.

So, my solution only impacted the DDM Templates and the files associated with them.

To answer your next question, I found that there are more areas inside of journal specifically that the same change could be applied, however it would require more testing and verification to make sure that the changes can be safely deployed. If they follow the same format and structure that the DDM Templates follow, it would be a simple fix. That is certainly something I can look in to, but ultimately this change was for the customer's issues only.

**Comment by ericyanLr** [comment]
Hi @jakesliwka ,

**Regarding:**
> That is certainly something I can look in to, but ultimately this change was for the customer's issues only.

Is this in regards to the steps in LPS-155839? If so, from my understanding, doesn't this just involve one of the classes? Or are we handling multiple scenarios (that aren't mentioned in the ticket)?

**Comment by jakesliwka** [comment]
@ericyanLr 

Yes - it directly involves the JournalDDMTemplateVerticalCard class specific to the ticket.
However, during the first round of review, it seemed important to test wherever else the DDM Templates were being used since the customer will be using them and is already having issues with them. That is when the other issue was found, prompting for the change in JournalSelectDDMTemplateVerticalCard.

So yes, I suppose we are handling an alternate scenario that is not mentioned in the ticket, however it made sense to me to still change it since it is related to DDM Templates.

**Comment by ericyanLr** [comment]
Hi @jakesliwka ,

Thanks for the clarification, I see what you mean now, the vertical cards you modified all are related to Journal and DDMTemplate.

**Comment by ericyanLr** [comment]
Reviewed and sent to Team Echo for further review: https://github.com/liferay-echo/liferay-portal/pull/8567

**Pull request closed without merging**
