### PR TITLE
LPS-147931 Get Display Page URL for a web content with a specific Display Page when journal article has a non-null layoutUUID

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-147931

The issue here was that the Display Page URL was not retrieved properly for a web content with a specific Display Page pointing to a Default Asset Publisher.
To fix this issue, I generated the corresponding Display Page URL when the journal article has a non-null layoutUUID. (This fix was suggested in [PTR-2882](https://issues.liferay.com/browse/PTR-2882))

@ericyanLr a customer is asking for an SDH for this issue on 7.3 SP3. Please let me know whether this fix can be provided for them.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

**Question**
How important is the check for: `Validator.isNotNull(journalArticle.getLayoutUuid())`?

Looking at the code block referenced from the PTR ticket ([JournalArticleAssetRenderer.java#L385-L392](https://github.com/liferay/liferay-portal/blob/687d7dfd609b7727d307edba457477fa2b9de9f5/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRenderer.java#L385-L392)), the logic is:
- Use **_assetDisplayPageFriendlyURLProvider** to retrieve **friendlyURL**
- If **friendlyURL** is not null, return **friendlyURL**
- else generate **friendlyURL** using groupFriendlyURL + etc

Would we be able to also just use the null check for friendlyURL or is there significance to also check for `Validator.isNotNull(journalArticle.getLayoutUuid())`?

**Comment by noornajj** [comment]
Hi @ericyanLr,

I did not look into it that much but from what I understood from the PTR and my reasoning of the situation is that we need to check whether the journal article is actually displayed in a layout before trying to retrieve it's display page. Otherwise, we would be trying to retrieve a journal article's display page when it actually doesn't have one.

The code block you have linked above is inside the method `getURLViewInContext()`. This view is available as a link under a journal article that is displayed in a layout; therefore, it is already known that there is an associated layout and there's no need to check for a non-null layoutUUID.

Let me know if further clarification is needed or there's is something that I am missing.

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Actually, in the code block I linked, it does have some sort of check for layoutUUID in the method:  **_isShowDisplayPage**
```
if (!_isShowDisplayPage(themeDisplay.getScopeGroupId(), _article)) {
```
- [JournalArticleAssetRenderer.java#L375](https://github.com/liferay/liferay-portal/blob/687d7dfd609b7727d307edba457477fa2b9de9f5/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRenderer.java#L375)

**Regarding:**
> I did not look into it that much but from what I understood from the PTR and my reasoning of the situation is that we need to check whether the journal article is actually displayed in a layout before trying to retrieve it's display page. Otherwise, we would be trying to retrieve a journal article's display page when it actually doesn't have one

But, is the null check for friendlyURL enough to handle what you described? 

To clarify, the logic would resemble the referenced code block more:
```
String friendlyURL =
    JournalArticle.class.getName(), journalArticle.getResourcePrimKey(),
    _assetDisplayPageFriendlyURLProvider.getFriendlyURL(
    themeDisplay);
        JournalArticle.class.getName(),
        journalArticle.getResourcePrimKey(), themeDisplay);

if (Validator.isNull(friendlyURL) {
    return friendlyURL;
}

Layout layout = journalArticle.getLayout();

String groupFriendlyURL = _portal.getGroupFriendlyURL(
    _layoutSetLocalService.getLayoutSet(
        journalArticle.getGroupId(), layout.isPrivateLayout()),
    themeDisplay, false, false);

friendlyURL = StringBundler.concat(
    groupFriendlyURL,
    JournalArticleConstants.CANONICAL_URL_SEPARATOR,
    journalArticle.getUrlTitle(themeDisplay.getLocale()));

return friendlyURL;
```

And if it turns out that this null check is not enough and we actually do need to account for the non-null layoutUUID, then:
- I think we can work on improving the commit message (or possibly split it into multiple commits) to help better explain the issue.
- Or maybe even adding a test if needed?

**Additional Thoughts**
Regarding the referenced logic code block, maybe the logic in: **_isShowDisplayPage** may be helpful for the scenario you described as well?

**Comment by noornajj** [comment]
Hello @ericyanLr,

I have tested and yes, the check for a non-null layoutUUID is necessary.

**Comment by ericyanLr** [comment]
**Update**
As discussed, Noor will be looking into this further.

**Comment by ericyanLr** [comment]
Reviewed and sent to Team Echo for further review:
https://github.com/liferay-echo/liferay-portal/pull/7485

**Comment by ericyanLr** [comment]
**Additional Notes**
As discussed, the logic to create the URL matches other Journal classes in our code-base and a technical task can be created to better consolidate this in the future to handle the duplicate code.

**Pull request closed without merging**
