### PR TITLE
Lps 157163

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-157163

The issue here is that an orphan FriendlyURLEntry gets left in the database when a layout's old friendly url is deleted.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

To start, I'm not too familiar with how **FriendlyURLEntry** and **FriendlyURLEntryLocalization** work together, but I figured looking at the **FriendlyURLEntryLocalServiceImpl** would be a good start.

A few things I noticed was that:
- When adding a **friendlyURLEntry**, **FriendlyURLEntryLocalization** is also created/updated: 
  - [FriendlyURLEntryLocalServiceImpl.java#L148-L150](https://github.com/liferay/liferay-portal/blob/7.4.3.33-ga33/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/service/impl/FriendlyURLEntryLocalServiceImpl.java#L148-L150)
- When updating a **friendlyURLEntry**, **FriendlyURLEntryLocalization** is also created/updated: 
  - [FriendlyURLEntryLocalServiceImpl.java#L504-L505
](https://github.com/liferay/liferay-portal/blob/7.4.3.33-ga33/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/service/impl/FriendlyURLEntryLocalServiceImpl.java#L504-L505)
- However, when deleting a **friendlyURLEntry**, I didn't see any logic regarding **FriendlyURLEntryLocalization**

**Questions**
All this to say:
- Do we know why the current logic in **FriendlyURLServlet** only deletes **FriendlyURLLocalizationEntry** entries?
- And does the proposed change make sense, to also delete the related **friendlyURLEntry**?
  - And if so, should the deletion of **FriendlyURLLocalizationEntry** entries be accounted for, when deleting a **friendlyURLEntry**?

Can you help provide some additional context for the proposed change? 
Thanks!

**Comment by robertoDiaz** [comment]
Hi,

Please send this solution to @liferay-lima

**Comment by robertoDiaz** [comment]
ci:close

**Comment by noornajj** [comment]
Hello @robertoDiaz,
The reason we had not forwarded this PR is because there are other questions regarding FURLs that were raised and could affect whether this solution is added in the correct spot or not.
I have opened [PTR-3229](https://issues.liferay.com/browse/PTR-3229) to get some answers to my questions.

**Comment by robertoDiaz** [comment]
Yes, I've seen that.

Anyway it should had been sent to Lima so we could have provided feedback faster

**Pull request closed without merging**
