### PR TITLE
[TS] LPS-129450 Include bug fix for org.eclipse.equinox.http.servlet > Generated from https://github.com/rotty3000/rt.equinox.bundles/pull/33

### PR DESCRIPTION
**Pull request by nikolettabuza**
Hi @ericyanLr,

I opened a [PR](/https://github.com/rotty3000/rt.equinox.bundles/pull/33) to `rotty3000/rt.equinox.bundles` containing the changes of
[Bug 562440 - method getStatus() of class HttpServletResponseWrapperImpl returns -1 in case of success](https://github.com/eclipse/rt.equinox.bundles/commit/81083c1d65abe31c8c5ec8fe866ebee96980a84d#)

It solves the following issue:
[LPS-129450](https://issues.liferay.com/browse/LPS-129450)

I noticed that the previous PRs included some changes to gradle.build and README.markdown.
So I included those changes as well, they might be needed for the relevant tests.

Please review the PR.

Thank you,
N

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @nikolettabuza ,

Regarding the commit: **LPS-129450 Include bug fix for org.eclipse.equinox.http.servlet** , is the bug fix from an official fix or is that a custom thing we are introducing? 

If it's from an official bug fix, it would be helpful if we include a reference to it in the commit message, or maybe even cherry-pick the actual commit if it applies the same exact changes.

Here are a couple examples:
- Referencing the related bug fix: https://github.com/rotty3000/rt.equinox.bundles/pull/31/commits/ea74f574f43cf2780ce87891c4fc0a03f07c268a
- Cherry-picking the related bug fix (notice first 2 commits): https://github.com/rotty3000/rt.equinox.bundles/pull/27

Regarding LPS-123554, I'm not super familiar with this process, but it looks like we only included a few of the commits for this PR when compared against this PR: https://github.com/rotty3000/rt.equinox.bundles/pull/32

I'm not super familiar with the process, but I'm sure Ray would be able to help with the next steps to make sure we're not missing anything.

These are just my thoughts from looking at the PR.
Hope that helps.

**Comment by nikolettabuza** [comment]
Hi @ericyanLr,

thank you, I only added the reference of the official fix to the PR. Now I added the link to the commit msg as well.

----
I saw that pull/32 (related to LPS-123554) was still open but it was referenced in commits ([example](https://github.com/liferay/liferay-portal/commit/d203199ff651e256e9ab25c2a01b2f1f313e1771)) as the PR from which the current `org.eclipse.equinox.http.servlet-{...}.jar` was generated. So I fetched pull/32.

Do you mean not all commits of pull/32 are included in pull/33? I see 3 commits and all of them are present in the current PR, pull/33, along with the 1 new commit.
[pull/32/commits](https://github.com/rotty3000/rt.equinox.bundles/pull/32/commits) > [pull/33/commits](https://github.com/rotty3000/rt.equinox.bundles/pull/33/commits)

Maybe I misunderstood something, the whole procedure is still unclear to me, the PR statuses are confusing in that repo etc.

If this is not what you meant, could you clarify it?

Thank you!

**Comment by ericyanLr** [comment]
Hi @nikolettabuza ,

Sorry for the noise, I got confused by the conversation in [pull/32/commits](https://github.com/rotty3000/rt.equinox.bundles/pull/32/commits). You're right, there's only 3 commits.

And thanks for adding the reference to the commit, it's really helpful.

**Comment by nikolettabuza** [comment]
Hi @ericyanLr,

I closed the PR and I am opening a new one because I ran into several issues while discussing which commits should be included and which ones not.

The library is usually generated from [pulls](https://github.com/rotty3000/rt.equinox.bundles/pulls?q=is%3Apr+is%3Aclosed) instead of the [base branch](https://github.com/rotty3000/rt.equinox.bundles/commits/R4_5_maintenance) containing all merged commits. This method is prone to errors because some commits can be missed. And once the pull request is merged, it will not reflect the changes pushed to the feature branch as I experienced, so it wouldn't solve this issue. Instead, the library is generated from the base branch containing all necessary commits.

* pull/32 excluded the commit from pull/31 for no documented reason, so it should be part of the generated library.
* pull/33 excluded the commits of pull/32 due to the discussion over whether they will be fixed before merge or not. Since the pull/33 commit was originally built on the branch of pull/32, it would also inevitably miss the commit from pull/31 as mentioned above.

**Pull request closed without merging**
