### PR TITLE
LPS-160639 Change location of the check to importPortletPermissions i…

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-160639

This is a regression bug caused by [LPS-150838](https://issues.liferay.com/browse/LPS-150838)
The issue here is that blog entries don't get published to live when the blog portlet is scoped to the page. 

To fix this issue, I reverted the fix from LPS-150838 and changed the location of the fix to PortletDataContextImpl.importPortletPermissions. Here I changed the the target resource from scope group Id to the current group Id. 

This fix resolves both issues.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hey @noornajj ,

Since the fix fully reverts the commit from the previous fix, can we include the revert as a separate commit? I think it would help to clearly show the reverted change and the change you are introducing.

Please let me know what you think.
Thanks!

**Comment by noornajj** [comment]
Yeah, that makes sense. I'll update the commits after the relevant tests finish

**Comment by ericyanLr** [comment]
Hey @noornajj ,

I took a look at the fix and have some concerns.

**Concern 1**
Looking at the code, the change you are making originated from a really old ticket: 
`LPS-25621 Add convenience methods to handle permissions export-import`
- https://github.com/liferay/liferay-portal/commit/161ddbefef25addac329b5926af4f24cd9689244#diff-ad0e33ee830a571bfa49d4dcc51fc67610d7b77ac956d16fa64a144926f0c7d6R1695

**Concern 2**
From looking at the code, I'm thinking this is related to: [PortalImpl#addPortletDefaultResource](https://github.com/liferay/liferay-portal/blob/7.4.3.38-ga38/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L730-L773), which eventually calls [PortalImpl#addRootModelResource](https://github.com/liferay/liferay-portal/blob/7.4.3.38-ga38/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L7202-L7225)

And based on these calls, it looks like the **scopeGroupId** is used as the primaryKey for adding these permissions. 
- I'm assuming the import part is referring to these permissions? 
- And if that's the case, does that mean we should be using the scopeGroupId?

**Question**
I haven't looked into this in detail, can you help check/clarify if these are actual concerns?

**Comment by noornajj** [comment]
Hi @ericyanLr 
I fixed the changes to what we discussed yesterday.
I also added the integration test for the original issue.

**Comment by ericyanLr** [comment]
Reviewed and sent to Staging Team for further review: https://github.com/liferay-staging/liferay-portal/pull/110

- Note: renamed commit: `LPS-150838 Add integration test` to `LPS-160639 Add integration test`

**Pull request closed without merging**
