### PR TITLE
LPS-84320

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-84320

To avoid sending mail when sender is unconfigured (e.g. test@liferay.com) this PR does following changes:
- **First commit https://github.com/ericyanLr/liferay-portal/pull/134/commits/a3618aea5e07040721816a2e11cc16ecc0ba89bf -** In SetupWizard, I have removed default email value, so customers cannot simply accept default "test@liferay.com" and they have to fill a valid email
- **Second commit https://github.com/ericyanLr/liferay-portal/pull/134/commits/5caf27fbbca94bc98e7f16402dcdde44170b9e2c -** In portal.properties, I have replaced "test@liferay.com" and "noreply@liferay.com" with  "test@domain.invalid" and "noreply@domain.invalid", so if customers don't execute the SetupWizard, they don't have "test@liferay.com" and they will have an [invalid eamil](https://tools.ietf.org/html/rfc2606). We cannot leave it empty as it will break some tests.
- **Third commit https://github.com/ericyanLr/liferay-portal/pull/134/commits/a6c796d6412fe34ab305a50ede551c30976e533d -** In case we have an old customer that already have "test@liferay.com" in its installation, I am adding a email blacklist before email is sent, so we will stop any wrong email from being send in case they have the default configuration.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @jorgediaz-lr ,

**Thoughts**
Would the second commit: https://github.com/ericyanLr/liferay-portal/pull/134/commits/5caf27fbbca94bc98e7f16402dcdde44170b9e2c no longer be needed, since we have the third commit?

And if the second commit is no longer needed, does that mean it would be possible to simplify the third commit: https://github.com/ericyanLr/liferay-portal/pull/134/commits/a6c796d6412fe34ab305a50ede551c30976e533d ?

For example, if we only have the 1st and 3rd commit, the resulting changes would be:

- The startup wizard will no longer auto-populate the the default email to test@liferay.com
- The email: test@liferay.com would be blacklisted by default.

From my understanding, the main fix is the 3rd commit.

**Concerns**
The reason I mention this is that currently, the 3rd commit looks kinda like a new feature, to provide the ability to:

- Blacklist specific email addresses
- Blacklist email addresses belonging to a domain

But, looking at the implementation, it looks like it would fail for certain cases, since it's only making a **emailAddress.endsWith(...)** comparison.

**3rd Commit - Simplification**
From my understanding, the main fix is blacklisting the email address: test@liferay.com

Would adding a simple implementation to block the email address: test@liferay.com, be sufficient?

**Note:** These are just my thoughts and it's possible I may be misunderstanding the actual issue.

Please let me know your thoughts.
Thanks!

**Comment by jorgediaz-lr** [comment]
Hi @ericyanLr 

I have removed second commit, see https://github.com/ericyanLr/liferay-portal/pull/135

See my full explanation there.

**Comment by jorgediaz-lr** [comment]
Hi @ericyanLr 

I have modified third commit, see https://github.com/ericyanLr/liferay-portal/pull/137

See my full explanation there.

**Pull request closed without merging**
