### PR TITLE
LPS-103091 Avoid truncating in the middle of an encoded characters taking into account surrogate pairs

### PR DESCRIPTION
**Pull request by dacousalr**
Hey @ericyanLr, could you review this? Thanks in advance \cc @holatuwol

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
Hi @dacousalr, didn't have much time to look over the fix, but considering whether to add additional safe-checks for the while loops and whether to return early with a better error, if we encounter a scenario where we cannot actually provide a unique url.

**Comment by dacousalr** [comment]
Hi @ericyanLr,

The upper limits of the while loops are properly checked but the bottom limits are not checked since they are practically impossible to reach given the existent values of maxLength (255) and the fact that a decoded character can suppose 12 encoded characters at best.

Given the nature of the algorithm to return a unique friendly URL, there is not much room for duplicates or for reducing the prefix to 0 chars.

**Comment by ericyanLr** [comment]
Hi @dacousalr ,

That makes sense to me. Reviewed and forwarded to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/8396

**Comment by ericyanLr** [comment]
**Update**
Actually, resent to Adolfo for further review: https://github.com/adolfopa/liferay-portal/pull/1126#issuecomment-542855255

**Pull request closed without merging**
