### PR TITLE
LPS-139866 Check portlet usage through PortletPreferencesLocalServiceUtil.getPortletPreferencesCount

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @ericyanLr 

could you please review my fix?

**Steps to reproduce:**
_Case 1_

1) Create a layout template and embed a single instance portlet (e.g. Announcements) in one of the columns (or use the attached template).
2) Deploy the template.
3) Create a Widget page and configure the above template for it.
Note #1: The Announcements portlet appears on the page immediately as it is embedded in the template.
4) Try to add the Announcements portlet to the page

_Case2_

1) Create a Web Content Structure with one field item
2) Create a template for the structure with an embedded portelt
<@liferay_portlet["runtime"]
    portletName="com_liferay_announcements_web_portlet_AnnouncementsPortlet"
/>
3) Create a Web Content based on the structure
4) Create a Widget Page
5) Add the Web Content to the page
6) Try to add the Announcements portlet to the page

**Actual behavior:**
The Announcements (single instance) portlet can be added to the page again if it is embedded in the layout template.

**Expected behavior:**
The Announcements (single instance) portlet can not be added to the page again if it is embedded in the layout template.

**Solution**
Instead of checking the layout we can check the portlet preferences

Thanks, Roland

https://issues.liferay.com/browse/LPS-139866
Related ticket: https://issues.liferay.com/browse/LPS-88060

Documentation for Embedding Portlets in a Layout Template on 6.2 with processor.processPortlet: 
https://help.liferay.com/hc/en-us/articles/360018180991-Embedding-Portlets-in-a-Layout-Template

Documentation for Embedding a Portlet by Portlet Name on 7.2 with  @liferay_portlet["runtime"]
https://help.liferay.com/hc/en-us/articles/360028746512-Embedding-a-Portlet-by-Portlet-Name

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @rolandpakai ,

**My Findings**
From what I can tell, the logic to your changes look similar to the previous behavior, before [LPS-127346](https://issues.liferay.com/browse/LPS-127346) was introduced: 
- https://github.com/ericyanLr/liferay-portal/commit/c84f06cfe67a688e41b4dff4f1a33fc4493a9f31#diff-fe02bdadb33154d4f13f2bd013a24812b401f600eca4b0908f4f3355622f48b6L659

The logic in your changes is similar to that original logic: `layoutTypePortlet.hasPortletId(portlet.getPortletId())`. 

**Suggestions**
I would suggest testing if your issue is still reproduced if you revert the changes from [LPS-127346](https://issues.liferay.com/browse/LPS-127346).

If it's no longer reproducible, then the issue that you're working on is actually a regression bug that was caused by: [LPS-127346](https://issues.liferay.com/browse/LPS-127346).

Feel free to let me know if you have any questions.
Hope this helps!

**Pull request closed without merging**
