### PR TITLE
[TS] LPS-79348

### PR DESCRIPTION
**Pull request by arthurchan35**

### CODE REVIEW

**Comment by arthurchan35** [comment]
ci:test:relevant

**Comment by arthurchan35** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:close

**Comment by lipusz** [comment]
Hi @arthurchan35 

Unless you required further assistance from the Search team, this fix should be sent to the WCM team, for example to @ ealonso.

Feel free to reach me if you have any questions.

**Pull request closed without merging**
