### PR TITLE
LPS-109837 Handling Collection instance valueObject

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @ericyanLr 

could you please check my changes and push it forward?

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
Hi @rolandpakai ,

One thing I noticed was this line: 
```
else if (valueObject instanceof Collection) {
	Collection<String> collection = (Collection<String>)valueObject;
```
- Reference: https://github.com/ericyanLr/liferay-portal/pull/168/files#diff-b40dba6f84376e16d11fe805aa17c3b3R66

From my understanding, it's possible that the **valueObject** may not be of type **Collection\<String>**

Can you verify whether an exception occurs if we change queryValues0 in the template:
- From: `"queryValues0": ["34651","34652"]`
- To: `"queryValues0": [34651,34652]`

Note: Based on this previous commit: 1aa6242c6b33c219e7680050d5080a8098bd206d, only Strings are expected for the values.

Feel free to re-send and let me know if you have any questions.

**Comment by rolandpakai** [comment]
Hi @ericyanLr 

If the values are not quated "queryValues0": [34651,34652] than the numbers converted into BigDecimals and the backend throws an invalid ClassCastException.

I changed the code and resent it, please check it.

Resent: https://github.com/ericyanLr/liferay-portal/pull/170

Thanks, Roland

**Pull request closed without merging**
