### PR TITLE
[TS] LPS-134550 Cookies do not follow custom context paths

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-134550](https://issues.liferay.com/browse/LPS-134550)

Hi Eric,

I hope you can review the PR.

In short, cookies are not separated properly if multiple portals are deployed on the same host under different context paths. You are probably familiar with the issue from the related PTR ticket.

Please let me know if you have any questions of concerns.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:relevant:norebase

**Comment by istvansajtos** [comment]
Hi Eric, @ericyanLr 

Regarding the relevant test failures called "unique", they failed on clean master too when tested locally.

Please let me know if you think the fix can go out as SDH.

Thank you!

**Comment by ericyanLr** [comment]
Hi @istvansajtos ,

Can you help confirm whether this fix needs to account for Liferay's portal proxy path? 

We have a portal property: `portal.proxy.path` that can be used when setting up Liferay behind a proxy server.

The closest example I could find related to cookies is this: https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/modules/dxp/apps/saml/saml-opensaml-integration/src/main/java/com/liferay/saml/opensaml/integration/internal/servlet/profile/BaseProfile.java#L548-L553

If you look into the implementation of: `portal.getPathContext()`, you'll notice that it accounts for the `portal.proxy.path` portal property.

And after looking at this logic, another question I would ask is whether we should be using Liferay Portal's context path or the provided httpServletRequest's context path.

Can you help look into this a bit?

**Additional Thoughts**
I noticed that one of the commits made changes to a js file. 

I did a quick search and I'm assuming these would be similar as well:
- https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/modules/apps/analytics/analytics-client-js/src/analytics.js#L501
- https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/modules/apps/commerce/commerce-frontend-js/src/main/resources/META-INF/resources/utilities/cookies.js#L30

----

Overall, the approach of this fix makes sense to me. The above are just concerns / edge-cases that came to mind.

Can you help look into them a bit? 
Also, feel free to let me know if you have any questions as well. 

As for the SDH approval, I believe that decision would be decided by the TS team in your region.

I'll mark this PR as closed for now, feel free to re-open.
Thanks!

**Pull request closed without merging**
