### PR TITLE
[TS] LPS-108729 PostgreSQLTransformerLogic.replaceCastLong(Matcher matcher) converts to a wrong type

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-108729

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @NorbertKocsis ,

It looks like the changes are causing this test to fail: [com.liferay.portal.dao.sql.transformer.PostgreSQLTransformerLogicTest.testReplaceCastLong](https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/372755/testReport/com.liferay.portal.dao.sql.transformer/PostgreSQLTransformerLogicTest/testReplaceCastLong/)

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by NorbertKocsis** [comment]
Hi,

I've fixed PostgreSQLTransformerLogicTest also.

Br,
Norbert

**Comment by ericyanLr** [comment]
Reviewed and forwarded to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/8870

**Pull request closed without merging**
