### PR TITLE
LPS-173068 Check for null before adding field value when repeatable field is empty

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-173068

The issue here is that a null literal is added to a search summary when a repeatable field is empty and there is at least one other field that is not empty. This occurs because repeatable fields are returned as arrays and when the field is empty, an empty string is added to the array --> [""] 
_getSortableValue will return the empty string as null and then null is added to the string bundler as a literal. 

To fix the issue, I had _getSortableValue return an empty string instead of null.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Do you know if this would cause any issues for this usage:
- [DDMIndexerImpl.java#L491-L493](https://github.com/liferay/liferay-portal/blob/7.4.3.59-ga59/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/util/DDMIndexerImpl.java#L491-L493) - createField
- [DDMIndexerImpl.java#L677-L678](https://github.com/liferay/liferay-portal/blob/7.4.3.59-ga59/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/util/DDMIndexerImpl.java#L677-L678) - _addToDocument

Looking at the original commit: https://github.com/liferay/liferay-portal/commit/c19fc924160bcdeb60cd5d46b2891242cd62415b, it looks like null value is being utilized by the _addToDocument method.

**Comment by noornajj** [comment]
Hi @ericyanLr 
I see what you mean. I can adjust [DDMIndexerImpl.java#L677-L678](https://github.com/liferay/liferay-portal/blob/7.4.3.59-ga59/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/util/DDMIndexerImpl.java#L677-L678) to use Validator.isNull to keep it from causing a regression.

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Regarding the **Validator.isNull** approach, can you verify if this would cause any issues for keywords that use the actual string: **null** ?

From my understanding, the **_addToDocument** method is the step that defines the document to be added to Elasticsearch. Would changing this mean that an entry with the value: **null** , would no longer be indexed?

**Comment by noornajj** [comment]
Hi @ericyanLr 
You mean if the entry had "null" literally as a value?

**Comment by ericyanLr** [comment]
> Hi @ericyanLr You mean if the entry had "null" literally as a value?

Yep! (But not exactly the same as the scenario on this ticket, which uses an array of strings. It would need to be a single String value)

**Comment by noornajj** [comment]
Ok, so testing this scenario, it looks like my previous fix for this similar issue causes "null" literals to be replaced by empty strings 
https://github.com/liferay-forms/liferay-portal/pull/2055/commits/e7370c1ae5323f1e60b6157f39d25b2eb6123ba5

And this current change will cause it for repeatable fields

**Comment by noornajj** [comment]
This seems to work for both senarios `(value == null || value == "")`

**Comment by noornajj** [comment]
Hey @ericyanLr 
I made these adjustments to the fix. I think this should work now for empty fields, null fields and the spacing issue.

**Comment by ericyanLr** [comment]
Hi @noornajj ,

I did some testing on the latest master and noticed that if I just include the first commit, I'm no longer able to reproduce the issue for both related tickets: 
- Commit: [LPS-173068 Revert LPS-169433 to allow null literals to be indexed](https://github.com/ericyanLr/liferay-portal/pull/300/commits/a69c4066de9fb733e226112b9960921e2760e2da)
- Tickets: [LPS-169433](https://issues.liferay.com/browse/LPS-169433) and [LPS-173068](https://issues.liferay.com/browse/LPS-173068)

Can you verify if this is the case for your testing as well?

**Additional Notes**
Regarding the second commit (if we determine to go this route):
- I assume for your string comparison: `(value != "")`, your intention was to use **.equals()**
- This approach modifies a general **Field** class in DDM Framework (The original approach just affected the indexer for DDM - DDMIndexerImpl)
  - And so, this would probably mean it would have an affect on the behavior of a DDM field, not just how a field gets indexed
  - If that's the case, and we think a change should be made to fields in general, I would suggest:
    - To check whether it passes existing tests
    - Whether a new test should be added, to describe why we are making this change for a DDM field.

Please let me know what you think.
Thanks!

**Comment by mbowerman** [comment]
Hi @noornajj , @ericyanLr ,

FYI, regarding this:
> This seems to work for both senarios (value == null || value == "")

You can use [Validator.isBlank](https://github.com/liferay/liferay-portal/blob/7fe3fcc7dd7578866b6e758c90769c47003b2a06/portal-kernel/src/com/liferay/portal/kernel/util/Validator.java#L300-L305) for this instead.

**Comment by noornajj** [comment]
Hi @ericyanLr 
- I'll test on latest master and let you know. 
- I didn't use **.equals()** for the comparison because value is serializable

Thank you @mbowerman, that only solved the issue when value is not repeatable (only one value). If there's an empty string inside an array, then it won't catch that.

**Comment by noornajj** [comment]
Hello @ericyanLr,
I was able to confirm the first commit solves the issue regarding null literals and empty strings. However, we're back to the issue of an additional space being added to the string bundler when the value is an empty string

**Comment by ericyanLr** [comment]
Hi @noornajj ,

I see, that's great news! Regarding the extra spaces, I think that's a much easier issue to address. If I remember correctly, the extra spaces issue is just on the indexer side.

If that's the case, the logic change could be made within the DDMIndexerImpl class.

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Reviewed and forwarded to Forms team for further review: https://github.com/liferay-forms/liferay-portal/pull/2123

**Pull request closed without merging**
