### PR TITLE
LPS-107587 Upgrade 51degrees to 3.2.18.1

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @ericyanLr 

could you please push this forward?
This need to be backported to 72x and 71x based on a customer ticket: https://issues.liferay.com/browse/LPP-39104

Thanks, Roland

https://issues.liferay.com/browse/LPS-107587

### CODE REVIEW

**Comment by rolandpakai** [comment]
Hi @ericyanLr

could you please check this and push it forward?

Thanks, Roland

**Comment by ericyanLr** [comment]
Hi @rolandpakai ,

Based on the LPS ticket description, the goal appears to be to update the LMDD Lite device database to the latest free available version.

Looking at the build.gradle file, the latest database should already be retrieved from the 51Degrees repo's master branch, during the build process:
- https://github.com/liferay/liferay-portal/blob/7.2.x/modules/apps/portal-mobile-device-detection-fiftyonedegrees/portal-mobile-device-detection-fiftyonedegrees/build.gradle#L18-L24

With that in mind, from my understanding, your change wouldn't actually be updating the database. If we compare the 51 Degrees branch, the database hasn't changed for almost 2 years:
- Compare (branch - master): https://github.com/51Degrees/Device-Detection/blob/master/data/51Degrees-LiteV3.2.dat
- Compare (tag - v3.2.21.1): https://github.com/51Degrees/Device-Detection/blob/v3.2.21.1/data/51Degrees-LiteV3.2.dat

You can see that the commit matches.

**Additional Testing**
As a sanity check, if you download Liferay Mobile Device Detection Lite - v3.0.0 for 7.2
- https://web.liferay.com/marketplace/-/mp/application/92831494

And you compare the checksums for the **51Degrees-LiteV3.2.dat** file, you'll see that it matches:
- Liferay's LMDD LPKG - 51Degrees-LiteV3.2.dat: 
  - MD5 (51Degrees-LiteV3.2.dat) = e9f5d4e24515fbdcb0b4aed21230d9c3
- 51Degrees master branch - 51Degrees-LiteV3.2.dat: 
  - MD5 (51Degrees-LiteV3.2.dat) = e9f5d4e24515fbdcb0b4aed21230d9c3

**Additional Thoughts**
For now, I'll mark this PR as closed, since from my understanding, the current build process should already fulfill the behavior described in the LPS ticket.

If my understanding is incorrect, please let me know. 

I would also suggest you verify whether this is truly the case for your particular scenario as well. And if this does not happen to match your scenario and you feel this PR still applies, it would be helpful if you can provide additional context + clarification as to what we are trying to solve and how this fix resolves the issue.

Feel free to re-open if needed and if you have any further questions.
Hope that helps.

**Comment by rolandpakai** [comment]
ci:reopen

**Comment by rolandpakai** [comment]
Hi @ericyanLr 

thanks for reviewing my changes.

Yes, i checked the database dat file too, and i can confirm it is using the latest version.

But the LPS-107587 is about to upgrade the 51degrees **core** version from 3.2.14.2 to 3.2.18.1
https://github.com/liferay/liferay-portal/blob/7.2.x/modules/apps/portal-mobile-device-detection-fiftyonedegrees/portal-mobile-device-detection-fiftyonedegrees/build.gradle#L4

The LPS-107587 title is missleading: _Upgrade LMDD Lite to the latest 51Degrees device database_,
but the description is about to upgrade the core version.
To avoid this missunderstanding i change the LPS-107587 title to **Upgrade LMDD Lite to the latest 51Degrees device core**

Sorry for the missunderstanding, could you please review the PR again?

Thanks, Roland

**Comment by ericyanLr** [comment]
Hi @rolandpakai ,

**Regarding:** 
> But the LPS-107587 is about to upgrade the 51degrees core version from 3.2.14.2 to 3.2.18.1

Regardless of the title, the ticket description still states: 

- "Please upgrade the LMDD Lite device database to the latest Free version available from 51Degrees."

From my interpretation, the initial intention was to update the 51Degrees device database.

**Thoughts**
Task tickets are normally used by the Product Team. And from my understanding, this task isn't something the PT is working on.

The confusion part right now for me is why we are pushing this task ticket from the Support side. It's still unclear to me what we are trying to fix.

If it's a bug that we are trying to fix, it would be helpful to have a bug ticket, with normal steps to reproduce. This would at least help provide context as to why we need to upgrade this library and how upgrading is involved with the bug fix.

But, with just this task ticket alone, it's unclear why this PR is being implemented from the Support Side and sent up to the Product Team.

Please let me know your thoughts.

**Comment by rolandpakai** [comment]
Hi @ericyanLr 

we have the following ticket on the support side: https://issues.liferay.com/browse/LPP-39104
Updating the 51degrees core version increase the compatibility with iPhone 11 + iOS 14.0 + Safari.
But there is no Bug type LPS ticket is created for the LPP, because i found this Task type LPS-107587 which solves the issue.

Thanks, Roland

**Comment by rolandpakai** [comment]
Hi @ericyanLr 

could you please check my last comment?

Thanks, Roland

**Comment by ericyanLr** [comment]
Hi @rolandpakai ,

**Proposed Next Steps**
Based on [LPP-39104](https://issues.liferay.com/browse/LPP-39104), we are trying to resolve a bug issue.

With that in mind, we would need an LPS bug ticket in order to properly:
- Document the Bug, along with steps to reproduce the issue
- Allow QA to reproduce the issue and review the bug fix

This is how we normally approach creating bug fixes in our TS workflow.

I understand that the same solution may possibly resolve the Task ticket and that we both may have different interpretations of the originally requested change from the Task ticket. 
- However, the main point is that a LPS bug ticket should still be created to properly document the issue and allow QA to properly test the bug fix. 

**What about the Task Ticket?**
As for the task ticket, I would suggest to first fulfill the LPS bug ticket. 

Depending on the results of the LPS bug ticket, if you determine that the solution also fulfills the task ticket, you could then circle back to the task ticket at that point and update the status accordingly (e.g. resolved, duplicate, etc.).

Please let me know your thoughts.
Hope that helps.

**Pull request closed without merging**
