### PR TITLE
LPS-48290 Added support for Malay Language

### PR DESCRIPTION
**Pull request by holatuwol**
/cc @dhavaldesai75

https://issues.liferay.com/browse/LPS-48290

If there's anything else we need to do in order to add a new beta language, please let me know!

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hey @holatuwol ,

/cc @achaparro

We discussed this with Supportability to try to get an understanding of the situation and they mentioned that if the language is a beta language, they're okay with it.

At the same time, we're not exactly sure who should review this, but we don't think this should go through the SME route. Also, we're not sure if Core Infra would be the proper component as well, but then again, most things that are uncertain do end up at Core Infra as we know.

We think you might have a better grasp on the scope of things related to Localization changes and may know which team / reviewer may be best to push this forward. 

Can you send the PR directly to a reviewer on a PT? If you do decide that Core Infra would be the team to send it to and would still like me to do the forwarding for the PR, feel free to let me know.

Please let me know how you would like to proceed.
Thanks!

**Comment by holatuwol** [comment]
@ericyanLr : Sorry for not clarifying! I'm double-checking with core infrastructure to make sure that other than I18nServlet, there's nothing else we need to update for adding a localization.

If you can't think of anything, the plan is to route it through someone who knows something about the localization systems (like CrowdIn) to make sure we're covered there.

**Comment by ericyanLr** [comment]
Hey @holatuwol ,

Thanks for the clarification!

**Analysis - Past Tickets**
I took a look at a few of the past tickets, and it looks like they all have at least the following 3 commits:

- Add a flag image
  - e.g. [LPS-94555 Adds ta_IN flag image (copied from hi_IN)](https://github.com/liferay/liferay-portal/commit/cb293f28e224b6bc01b49354802148630b607d78)
  - e.g. [LPS-87590 frontend-theme-unstyled - adds Kazakh flag image - kk-KZ.png](https://github.com/liferay/liferay-portal/commit/9297fac9c205b030baa9490fbb107b4583efc8b5)
- Add iso code to portal.properties 
  - e.g. [LPS-94555 Adds Tamil language iso code to portal.properties](https://github.com/liferay/liferay-portal/commit/a2e64ff15734430eb99dd03098076b5976a14fa8)
  - e.g. [LPS-87590 portal-impl - adds Kazakh language and country code to portal.properties](https://github.com/liferay/liferay-portal/commit/c5827d3593bc94ab060124b8d555846f8b619fd4)
- Add language to servlet mappings & security constraints
  - e.g. [LPS-94555 Added Tamil (ta_IN) language change servlet mappings & security constraints](https://github.com/liferay/liferay-portal/commit/2b14a53e12841c5ba2f499e0c150c5870979f0af)
  - e.g. [LPS-87590 Add new language to web.xml](https://github.com/liferay/liferay-portal/commit/fdecf4d45c8dfcae51efca67fb35029df014902d)

**locales vs locales.beta**
From what I can tell, a language iso code should be added to **one of properties**, either **locales** or **locales.betas**.

This is based on observations from past commits, such as the following where they officially switch a language from **locales.beta** to **locales**:
- liferay@39afc5ced3f06b07407c45da08d125ac5b4e8bdd
- liferay@726706d50a2661c566cbac8bb2bf87d973168810

**Regarding - Language.properties**
From the provided commit, I noticed there was also an addition being made to **Language.properties**

Looking at the code, it looks like these language keys were added for the Translator Portlet, which has been deprecated.

There hasn't been any new additions to this since 2012.

----

Hope that helps, just wanted to make sure we have additional context first before moving forward.

**Question:** Would you like me to ask Engineering if they know of any other things to consider when adding a new beta locale?

**Comment by holatuwol** [comment]
> Would you like me to ask Engineering if they know of any other things to consider when adding a new beta locale?

@ericyanLr Yes, please!

**Comment by ericyanLr** [comment]
Hey @holatuwol ,

I asked Shuyang and he said:

> I actually don't know, never done that before. But it feels that just the I18nServlet config matters.

**Comment by ericyanLr** [comment]
Closing out this pr, feel free to let me know if you have any further questions.

**Pull request closed without merging**
