### PR TITLE
LPS-92701 Impossible to add image with page-scope, when virtual host is used

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @ericyanLr 

Could you please review this pull request?

As you suggested in the PTR, changing the `group` from `themeDisplay.getScopeGroup()` to `themeDisplay.getSiteGroup()` solves the issue.

Thank you and best regards,
István

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @IstvanD, 

can you provide more insight as to why this is the proper change?

For instance, I understand that it fixes your issue, but is there a reason why you decided to choose SiteGroup over ScopeGroup as the default for the method **createControlPanelPortletURL**? 

Does your commit message properly describe the change? Without proper context, I don't see how "image" plays a part. Should the mention of image even be included?

Providing more insights and a more accurate commit message would be helpful for understanding the proposed changes.

Please let me know if for have any  questions.

Thanks!

**Comment by IstvanD** [comment]
Hi @ericyanLr 

I am no expert of this component, but as I understand, the scopeGroupId will inherit it's value from the scope settings of the portlet configuration. 
If the portlet's scope is set to Page, scopeGroupId will be that of the Page's, and RequestBackedPortletURLFactoryUtil._getControlPanelLayout() will not return a Layout from which PortletURLFactoryUtil.create() could create a valid portletURL.

Using the Site's group ID, RequestBackedPortletURLFactoryUtil._getControlPanelLayout() can retrieve the Control Panel Layout.

I have chosen the commit message based on the issue it solves, but if you don't find it accurate, I'll choose another one.

Best regards,
István

**Comment by ericyanLr** [comment]
Hi @IstvanD,

Thanks for providing your insight as to why the change works. 

## Additional Information + Reasoning
I guess what I'm trying to learn more about is the reasoning behind why you chose to make this change here.

On PTR-798, I also mentioned that this change could possibly be made in **DocumentsAndMediaURLEditorConfigContributor**.

What made you choose to make the change in **RequestBackedPortletURLFactoryUtil:: createControlPanelPortletURL** and not **DocumentsAndMediaURLEditorConfigContributor**?

**Note:** I'm not questioning the changes in the pr, I'm just hoping to get more information and reasoning behind the change. 

I honestly don't know whether the change from **ScopeGroup** to **SiteGroup** in **RequestBackedPortletURLFactoryUtil:: createControlPanelPortletURL** makes sense or not without further investigating myself.

My hope is that, you can provide additional information + reasoning behind the changes, and if it makes sense to me, I would just pass that information along to the PT for further review.

## Commit Message
As for the commit message, I guess what I'm trying to say is that the change being made to **RequestBackedPortletURLFactoryUtil:: createControlPanelPortletURL** seems more general.

Your commit message mentions an image, but I don't really see how an image is involved if I'm just looking at this class.

However, if the commit was made in **DocumentsAndMediaURLEditorConfigContributor**, mentioning "image" would make a little more sense.

**Note:** Again, I'm not questioning the changes in the pr, I just wanted to express what I meant by the commit message could be more accurate for the commit that's being made.

Thanks!

**Comment by ericyanLr** [comment]
Hi @IstvanD,

Thanks for providing your insight as to why the change works. 

## Additional Information + Reasoning
I guess what I'm trying to learn more about is the reasoning behind why you chose to make this change here.

On PTR-798, I also mentioned that this change could possibly be made in **DocumentsAndMediaURLEditorConfigContributor**.

What made you choose to make the change in **RequestBackedPortletURLFactoryUtil:: createControlPanelPortletURL** and not **DocumentsAndMediaURLEditorConfigContributor**?

**Note:** I'm not questioning the changes in the pr, I'm just hoping to get more information and reasoning behind the change. 

I honestly don't know whether the change from **ScopeGroup** to **SiteGroup** in **RequestBackedPortletURLFactoryUtil:: createControlPanelPortletURL** makes sense or not without further investigating myself.

My hope is that, you can provide additional information + reasoning behind the changes, and if it makes sense to me, I would just pass that information along to the PT for further review.

## Commit Message
As for the commit message, I guess what I'm trying to say is that the change being made to **RequestBackedPortletURLFactoryUtil:: createControlPanelPortletURL** seems more general.

Your commit message mentions an image, but I don't really see how an image is involved if I'm just looking at this class.

However, if the commit was made in **DocumentsAndMediaURLEditorConfigContributor**, mentioning "image" would make a little more sense.

**Note:** Again, I'm not questioning the changes in the pr, I just wanted to express what I meant by the commit message could be more accurate for the commit that's being made.

Thanks!

**Pull request closed without merging**
