### PR TITLE
[TS] LPS-86512 User notification about lockout is shown in server time instead of portal time

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi Eric,

Please review my fix:
Link to the LPS ticket:
[LPS-86512](https://issues.liferay.com/browse/LPS-86512)
If you approve this change, please forward it to the next approver,
Thank you,
Peter

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

After looking into the issue and the proposed fix some more, do you think it would be sufficient to just include the Server's timezone as well?
- e.g. 10/12/18 12:08:PM UTC

With the approach above, we wouldn't need to disclose the timezone of a user to a guest user.

I was also considering whether we could detect the client's current timezone from their browser and adjust accordingly, but that may be too much.

Please let me know your thoughts.
Thanks!

**Comment by peterpetrekanics** [comment]
Hi @ericyanLr ,

I could not reproduce a case where the timezone of a user was disclosed to a guest user.
Could you please send me the steps if you think that this is an issue?
Also I am not sure what kind of a change you have in mind.
The ticket I am working on will run out of SLA in 1.5 days so we are in a hurry.
I need to provide a temporary workaround to the client tomorrow: do you think I can provide the current solution as a temporary fix?
Thank you very much in advance,
Peter

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

Sorry for the confusion, to re-summarize my previous comment, would displaying the actual timezone be enough to resolve this issue?
- Current Message: This account is locked until  10/12/18 12:08:PM
- Proposed Message (Providing the timezone): This account is locked until 10/12/18 12:08:PM UTC

This should resolve the confusion between the provided date time.

As for temporary fixes, do you mean SDH? I'm not sure how SDHs work in the other offices, but for our team, we usually do not give out SDHs until the issue is committed into master.

Please let me know your thoughts.
Thanks!

**Comment by peterpetrekanics** [comment]
Hi @ericyanLr,

Ah ok now I understand.
For our customer, this proposed message would not be enough, unfortunately: they would like to see the lockout time displayed based on the user's timezone (the user who has his account locked). My proposed code change aims exactly that.
In case you have a better solution, of course I would be happy to use that - so please send me your modified jsp files or a pull request so I can have a look.
Regarding SDHs: for us it is ok to create an SDH as long as the first reviewer accepted the proposed fix. In this case you are the first reviewer, based on the "SME Master List" knowledge article - that is the reason why I've sent you this pull request. If you approve the current solution then I'll be able to send the SDH to the customer.
Finally: I wanted to thank you for your suggestions and help with this, I am sure with your help we will find a proper solution for this client.
Best Regards :)
Peter

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

From our perspective, it makes more sense to use the Server's timezone or Portal Instance's timezone than the user's timezone (the user who has his account locked).

As for the modified jsp files, I haven't had much time to look into best way to fix this.

Currently, the date is being formatted by the `<liferay-ui:message` tag.
The tag eventually calls: [LanguageImpl.java#_getFastFormattedMessage](https://github.com/liferay/liferay-portal/blob/7.1.0-b3/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L1787-L1791) to format the provided date.

Currently, I can think of two ways we could approach this fix:
- One way to fix this issue is to modify the jsps.
- Another way to fix this issue is to modify **LanguageImpl.java#_getFastFormattedMessage** to also provide the timezone when formatting a date object.

Apologies for the delays, I understand that you are near SLA deadline.

Please let me know your thoughts.
Thanks!

**Comment by psajevics** [comment]
Hi @ericyanLr,

Thank you for your inputs regarding this matter. I hope you don't mind me jumping into the conversation. We were discussing the described issue with the team from the customers perspective mainly. Our understanding is that the account locked message contains information mainly for the given user who is being locked out. So the goal is to display the end time in the user's timezone.   

Could you please elaborate further on your approach mentioned before: 

> From our perspective, it makes more sense to use the Server's timezone or Portal Instance's timezone than the user's timezone (the user who has his account locked). 

The reason I am asking is because if we need to inform the user about our perspective, it would be great to have a proper reason to overwrite their need or request of resolution.

Please let me know your thoughts.
Thanks,
Peter

**Comment by ericyanLr** [comment]
Hi @psajevics ,

Thanks for your input and summary.

**Main Issue**
From our perspective, the main issue here is that the provided date time does not provide enough context for the reader to determine the actual lockout date time. 

One simple way to resolve this issue is to include the timezone when displaying the lockout date time. This would provide the reader with enough context to determine the actual lockout date time.

For example:
- Current Message: This account is locked until 10/12/18 12:08:PM
- Message with timezone: This account is locked until 10/12/18 12:08:PM UTC

Including the timezone would provide enough context for a reader to determine the actual lockout date time.

**Customer's Request**
From my understanding, the customer would like to show the date time based on the customer's timezone preference.

But, just displaying the date time in a different timezone does not resolve the **Main Issue** described above.

For example: If a locked out user has their timezone set as PDT
- Current Message: This account is locked until 10/12/18 12:08:PM
- Message with customer's date time: This account is locked until 10/12/18 5:08:AM

With the message above, this does not clearly provide the actual lockout date time to a reader, as there is not enough context.

----
**Additional Thoughts**
We understand that there's also the potential option to include a fix that would: 

- Fix the Main Issue
- Include the customer's request

For example: If a locked out user has their timezone set as PDT
- Current Message: This account is locked until 10/12/18 12:08:PM
- Message with timezone + customer's date time: This account is locked until 10/12/18 5:08:AM PDT

But, ultimately, we think that using the server's timezone (or possibly Portal Instance's timezone) makes the most sense and would reduce potential inconsistencies.

The described customer request is more of a specific customer request. If they would like that behavior, we would see it more as a customization.

Hope that helps.

Please let me know your thoughts.
Thanks!

**Comment by psajevics** [comment]
Hi @ericyanLr,

Thank you so much for the detailed explanation of your standpoint. I think there is a minor misunderstanding about what we perceive as the **Main Issue.**

Let me separate the following roles for further explanation: User and Customer.

Based on the reported issue as per our perception the Users have the following Main Issue:

"_the end time of the lockout is wrongly shown"_

Instead of not having full context for determination. however we can agree that providing further context such as the server's time zone (UTC) can give additional context. 

To simplify my previous statement: 

**Main issue**: The users are not able to see the actual end time of the lockout as per their timezone.

Our goal as far as I understood: Show the actual time in the error message as per their timezone - This is where I think we are having a minor misunderstanding. 

**Suggested fix**: Show the server's time zone, so the user can have bigger context in order to calculate the time as per his/her time zone.

I am curious about this topic because of these dimensions: 

User Experience - how the users are using the portal
Customer Experience - what we communicate as a fix to a reported issue

I hope you don't mind me asking the following questions:

_But, ultimately, we think that using the server's timezone (or possibly Portal Instance's timezone) makes the most sense and would reduce potential inconsistencies._

In the scenario are we considering what makes sense for the Users?
Is it possible to have additional insights regarding the potential inconsistencies?

I feel this would also be useful for us for the future to see what are the aspects, that we need to consider before searching for solutions.

Thanks again for all your time and effort,
Peter

**Comment by ericyanLr** [comment]
Hi @psajevics ,

Thanks for providing your insight for this matter.
To further clarify our discussion, I would like to make a better distinction between: 
- The Main Issue
- The approach to resolve this issue

### Main Issue
Currently, the provided lockout message does not provide enough context for the user to deduce the actual lockout date time.

### Approach
Currently, we discussed a couple of options to resolve this issue:
- Provide the date time with the time zone (server's)
- Provide the date time with the user's time zone

----
### Question: Is it possible to have additional insights regarding the potential inconsistencies?

Here are a few things that I took into consideration:

1. To fix the main issue, providing the timezone should be sufficient (server/portal instance's timezone)
2. The person viewing the site is currently the GUEST user
3. Providing the timezone of the "Locked out" user would share this information with the GUEST user. 

Although providing the user's timezone may be considered a very minor security risk, it was still something I took into consideration.

There are a few other thoughts I had as well:

1. If the user's timezone was used, and they are viewing the site while traveling at a destination with a different timezone, would it still be as useful?
2. If a System Administrator was helping a user, would it be easy for them to understand the message?

### Question: In the scenario are we considering what makes sense for the Users?

I believe that regardless of whether we use the "Locked out" user's timezone or the server's timezone, ultimately the provided lock out date time would make sense for the user.

----
Above were my thoughts and concerns regarding the proposed fix.

If you believe that the benefits of your approach outweighs the concerns above, feel free to provide a pr with the fix and we can send it along for review.

### Note: Current PR
From what I can tell, this current pr also does not provide a timestamp in the message, which means the Main Issue would still be reproduced.

Please let me know if you have any further questions or concerns.
Thanks!

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics 

Closing this pr for now.

Please let me know if you have any questions regarding my previous comment.
Thanks!

**Comment by psajevics** [comment]
Hi @ericyanLr,

Thanks a lot for all your insights for the subject. At this point we are good with the outcome. My goal was to understand the reasons and the context behind the decision and suggestions. 

I appreciate your attention and effort. Going forward we notify the customer about the possible solution.

Thanks,
Peter

**Pull request closed without merging**
