### PR TITLE
[TEST CI] LPS-146343 Only alter the portlet namespace of the request when a non-empty querystring is provided

### PR DESCRIPTION
**Pull request by ericyanLr**
Testing on CI

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@ericyanLr most of the failures here are real.

Steps to Reproduce 1:
1. Go to Product Menu > Publishing > Staging

Result: Portlet does not render.
```
ERROR [http-nio-8080-exec-7][IncludeTag:128] Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_staging_processes_web_portlet_StagingProcessesPortlet&p_p_lifecycle=0&p_p_state=maximized&p_v_l_s_g_id=20123&p_p_auth=6yFaFqIN generates exception: null
java.lang.NullPointerException: null
        at com.liferay.portlet.internal.PortletConfigFactoryImpl.create(PortletConfigFactoryImpl.java:41) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.portlet.PortletConfigFactoryUtil.create(PortletConfigFactoryUtil.java:31) ~[portal-kernel.jar:?]
        at com.liferay.portal.util.PortalImpl.getPortletDescription(PortalImpl.java:4241) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.util.PortalUtil.getPortletDescription(PortalUtil.java:1396) ~[portal-kernel.jar:?]
        at org.apache.jsp.html.common.themes.portlet_jsp._jspService(portlet_jsp.java:654) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:9.0.56]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
        at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53) ~[portal-impl.jar:?]
        at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:409) ~[util-taglib.jar:?]
        at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:384) ~[util-taglib.jar:?]
        at com.liferay.taglib.util.IncludeTag.doInclude(IncludeTag.java:217) ~[util-taglib.jar:?]
        at com.liferay.taglib.util.IncludeTag.doEndTag(IncludeTag.java:88) ~[util-taglib.jar:?]
        at org.apache.jsp.html.portal.render_005fportlet_jsp._jspService(render_005fportlet_jsp.java:1566) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:9.0.56]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
        at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
2022-02-15 02:06:03.904 ERROR [http-nio-8080-exec-7][LiferayMethodExceptionEventHandler:42] Unable to execute method processMax {exception=com.liferay.portal.kernel.portlet.PortletContainerException: java.lang.NullPointerException, className=com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor}
com.liferay.portal.kernel.portlet.PortletContainerException: java.lang.NullPointerException
        at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:424) ~[portal-impl.jar:?]
        at com.liferay.portlet.internal.PortletContainerImpl.render(PortletContainerImpl.java:211) ~[portal-impl.jar:?]
        at com.liferay.portlet.SecurityPortletContainerWrapper.render(SecurityPortletContainerWrapper.java:144) ~[portal-impl.jar:?]
        at com.liferay.portlet.RestrictPortletContainerWrapper.lambda$render$0(RestrictPortletContainerWrapper.java:124) ~[portal-impl.jar:?]
        at com.liferay.portlet.RestrictPortletContainerWrapper._render(RestrictPortletContainerWrapper.java:185) ~[portal-impl.jar:?]
        at com.liferay.portlet.RestrictPortletContainerWrapper.render(RestrictPortletContainerWrapper.java:122) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.portlet.PortletContainerUtil.render(PortletContainerUtil.java:214) ~[portal-kernel.jar:?]
        at com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor.processMax(TemplateProcessor.java:146) ~[portal-impl.jar:?]
```

Steps to Reproduce 2:
1. Go to Home page
2. Mouse over Page menu "Menu Display"
3. Go to dropdown menu > Configuration

Result: Configuration iframe does not load.

Result: Portlet does not render.
```
ERROR [http-nio-8080-exec-1][IncludeTag:128] Current URL /web/guest/home?p_p_id=com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet&p_p_lifecycle=0&p_p_state=pop_up&_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_mvcPath=%2Fedit_configuration.jsp&_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_settingsScope=portletInstance&_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_redirect=%2Fweb%2Fguest&_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_returnToFullPageURL=%2Fweb%2Fguest&_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletConfiguration=true&_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletResource=com_liferay_site_navigation_menu_web_portlet_SiteNavigationMenuPortlet&_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_resourcePrimKey=6_LAYOUT_com_liferay_site_navigation_menu_web_portlet_SiteNavigationMenuPortlet&_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_bodyCssClass=dialog-iframe-popup+ generates exception: null
java.lang.NullPointerException: null
        at com.liferay.portlet.internal.PortletConfigFactoryImpl.create(PortletConfigFactoryImpl.java:41) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.portlet.PortletConfigFactoryUtil.create(PortletConfigFactoryUtil.java:31) ~[portal-kernel.jar:?]
        at com.liferay.portal.util.PortalImpl.getPortletDescription(PortalImpl.java:4241) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.util.PortalUtil.getPortletDescription(PortalUtil.java:1396) ~[portal-kernel.jar:?]
        at org.apache.jsp.html.common.themes.portlet_jsp._jspService(portlet_jsp.java:654) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:9.0.56]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
        at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53) ~[portal-impl.jar:?]
        at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:409) ~[util-taglib.jar:?]
        at com.liferay.taglib.util.IncludeTag.include(IncludeTag.java:384) ~[util-taglib.jar:?]
        at com.liferay.taglib.util.IncludeTag.doInclude(IncludeTag.java:217) ~[util-taglib.jar:?]
        at com.liferay.taglib.util.IncludeTag.doEndTag(IncludeTag.java:88) ~[util-taglib.jar:?]
        at org.apache.jsp.html.portal.render_005fportlet_jsp._jspService(render_005fportlet_jsp.java:1566) ~[?:?]
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) ~[jasper.jar:9.0.56]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
        at com.liferay.portal.servlet.DirectRequestDispatcher.include(DirectRequestDispatcher.java:64) ~[portal-impl.jar:?]
        at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190) ~[portal-impl.jar:?]
2022-02-15 02:10:10.117 ERROR [http-nio-8080-exec-1][runtime:59] Error executing FreeMarker template
freemarker.core._TemplateModelException: Java method "com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor.processMax()" threw an exception when invoked on com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor object "com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor@764138d7"; see cause exception in the Java stack trace.

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${processor.processMax()}  [in template "classic_WAR_classictheme_STANDARD_pop_up" at line 4, column 25]
----
        at freemarker.ext.beans._MethodUtil.newInvocationTemplateModelException(_MethodUtil.java:289) ~[bundleFile:?]
```

There might be more ways this shows up, but detailing all the test failures would take a long time. Can you look into these for now?

**Comment by ericyanLr** [comment]
Hi @vicnate5 ,

Thanks for your analysis, really useful information and enough to help me move forward. 

Thanks again!

**Pull request closed without merging**
