### PR TITLE
LPS-124315

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @ericyanLr 

This fix solves the issue of selecting a different language via Language Selector widget when a virtualhost set for a specific language is in use.

This solution adds a new attribute that is taken into account at the time of generating the new URL from UpdateLanguageAction to set the required target language.

Could you please review it?

Please, let me know if any further clarification is needed.

Thanks in advance

--

Related tickets:
- LPS-124315
- PTR-2116
- PTR-2137

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @dacousalr ,

To start, I may not be the best person to review this, but I am a bit familiar with a few of the components involved.

**Question**
From our previous discussion, we mentioned that the **VirtualHost** instance was **directly setting** it's default locale to the attribute **WebKeys.I18N_LANGUAGE_ID**, which iirc, results in bypassing the I18nFilter.

Were you able to confirm if that was the case? 

And if so, based on your proposed fix, does this mean that we are intentionally bypassing the I18nFilter and handling this elsewhere, when a Virtual Host is involved?

Can you provide more details about the approach you took for this and reasoning?

**Thoughts**
Without additional details, it's unclear to me how the Virtual Host's default locale is expected to be used and it's priority, in comparison to the existing locale logic that's currently present.

For instance, in regards to the 2nd commit, I'm not sure whether the "requested locale" refers to the LanguagePortlet, a URL parameter, I18nFilter, etc. I think this commit could be probably be split into multiple commits to help describe the proposed changes being made.

Again, I may not be the best person to review this, but hopefully this feedback could be helpful!

Please let me know your thoughts.
Thanks!

**Comment by dacousalr** [comment]
Hi @ericyanLr,

> From our previous discussion, we mentioned that the VirtualHost instance was directly setting it's default locale to the attribute WebKeys.I18N_LANGUAGE_ID, which iirc, results in bypassing the I18nFilter.
> 
> Were you able to confirm if that was the case?

Yes, this seems to be intended since the goal is to force this locale in absence of any language/locale prefix.

> And if so, based on your proposed fix, does this mean that we are intentionally bypassing the I18nFilter and handling this elsewhere, when a Virtual Host is involved?
> 
> Can you provide more details about the approach you took for this and reasoning?

At the beginning I refused to believe that we had to bypass the I18nFilter so my first attempts to fix it tried to partially revert the original solution but doing so this functionality would work only for the case of a guest user who has not specified a locale yet. This made me explore the possibilities of leaving LPS-44217 as is and trying to find a fix from the point of view of the component more related to the use case in focus, that is, the UpdateLanguageAction. In my opinion it makes sense to bring the resposibility returning an appropriate URL to change the locale without relying on I18nFilter to UpdateLanguageAction (something similar is currently being done when locale.prepend.friendly.url.style is set to 1 or 2, I do not why this is not done for value 3 by the way but this is another different question).

> Again, I may not be the best person to review this, but hopefully this feedback could be helpful!

Of course it was, thanks!

I will send you this PR since Echo team told me that this should be reviewed by Core Infra so as Core Infra SME I have sent it to you but please, let me know who could be the most suitable reviewer for this PR in your opinion.

Thanks again!

**Comment by ericyanLr** [comment]
Hi @dacousalr ,

I left a comment on PTR-2137.

Feel free to let me know if you have any questions.
Closing out this PR, feel free to re-open.

**Pull request closed without merging**
