### PR TITLE
LPS-102567 In the password reset email use the portal URL from which the request was sent

### PR DESCRIPTION
**Pull request by hudakl**
Hi Eric,

Could you please review my solution suggestion for LPS-102567?

Thank you,
Laci

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @hudakl ,

I did not have much time to take a look, but a question did come to mind: 
- Do you know if **serviceContext.getPortalURL()** would ever return blank or null?

And if so, should we provide a default value?

**Comment by hudakl** [comment]
Hi,

I tested the possible scenarios, which would use that method, but I haven't encountered any NPE problems.
Nonetheless, I reckon it could be triggered via remote call and if that has incorrect service context, that might lead to such issues.

If you think that's a valid danger I can add the old logic back as default in case serviceContext contains null for PortalURL.

Thanks,
Laci

**Comment by ericyanLr** [comment]
Hi @hudakl ,

I think my only concern is that the **serviceContext.getPortalURL()** can technically be set to anything and will be injected into the email.

Though, it's also possible that this concern is nothing to be worried about.

As an example, if ValidHostNameFilter is not actually being used, it may be possible for someone to customize their portalURL by modifying their /etc/hosts file and adding the entry: 
- `127.0.0.1	lrdev.com`

If we then navigate to: http://lrdev.com:8080/ and request a password reset, and debug using a breakpoint at where your code change is, we can see that **serviceContext.getPortalURL()** will be **http://lrdev.com:8080**, which will be added to the email.

An alternative solution may be to lookup the virtualHostName from the layout of the current page. It looks like the ServiceContext has references to plid and scopeGroupId, which may be able to retrieve that.

These are just my thoughts.
Hope that helps!

**Comment by hudakl** [comment]
Hi Eric,

The scenario you described is in fact the purpose of the fix :)
In the notification email we should see the URL from which we accessed the portal.

Furthermore, as I think of it the passwordResetURL in that method also uses serviceContext.getPortalURL(), so I think we should indeed use that to retrieve the portalURL.

What do you think?

Thanks,
Laci

**Comment by ericyanLr** [comment]
Hi @hudakl ,

**The scenario you described is in fact the purpose of the fix :)**
Just wanted to confirm if this is really the case.

Using the steps to reproduce on the ticket, we would have the following:
- Instance Virtual Host: **instance.com**
- Guest Public Pages Virtual Host: **mysite.com**

From my understanding, you would expect an email that includes a portal URL could originate from: **instance.com** and **mysite.com**

With the example scenario I provided, the email would now include a portalURL from **lrdev.com**, which is not a virtual host that's been configured within Liferay, but rather only on a user's machine, via /etc/hosts.

Can you confirm whether the sample scenario is a part of the expected behavior from your proposed fix?

Thanks!

**Comment by hudakl** [comment]
Hi,

Yes, that's how I think this should work. Similarly to the case, when we just access it from localhost. That's also not configured in the portal, but the email we receive will contain localhost:8080.

Regards,
Laci

**Comment by ericyanLr** [comment]
Hi @hudakl ,

Do you think this may be a security concern, since a user can technically change **localhost** to any domain they want, such as **evil-server.int**? (For the case that ValidHostNameFilter is not actually being used)

Or, do you think that this would be okay, since it's up to the customer on how they configure their server?

Best,
Eric

**Comment by hudakl** [comment]
I'm not sure what could be the possible security concerns. Nonetheless, I reckoned this would fine, since:
- it is indeed up to the customer on how they configure their server
- I simply used the same logic that is also used for creating the passwordResetURL

**Comment by ericyanLr** [comment]
Hi @hudakl ,

It seems I was not able to clearly describe the possible security concern with my hypothetical situation.

But, nonetheless you make a good point that:
- it is indeed up to the customer to configure their server to properly protect their domain
- this logic is used in several places to provided the portal url, for email templates as well.

I'll forward this pr to the USM team for further review: https://github.com/drewbrokke/liferay-portal/pull/890

**Pull request closed without merging**
