### PR TITLE
[TS] User notification about lockout is shown in the server's time zone which can be confusing for a user in a different time zone

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi Eric,

Please review my fix, I have created it based on your earlier suggestions.
I have checked the [FastDateFormatConstants](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/FastDateFormatConstants.java) possibilities but none of them provided the time format that I needed, that is why I have used the existing StringBuilder in LanguageImpl to add the timezone information.

If you approve this change, please forward it to the next approver,
Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by peterpetrekanics** [comment]
ci:test

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

Apologies for the delayed review of this pr.

I think the current proposed code would be somewhat confusing, as we are combining two date formatted strings.

In regards to your initial comment, I took a look at the code, and I think configuring the timeStyle might allow us to display a timezone. Based on this Oracle page, it looks like using the LONG constant for the timeStyle might provide us with the timestamp.
- Reference: https://docs.oracle.com/javase/tutorial/i18n/format/dateFormat.html

Can you verify if this is the case?
Our FastDateFormatFactoryUtil also allows us to specify a timeStyle as well.
- Reference: [FastDateFormatFactoryUtil.java#L43-L48](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/FastDateFormatFactoryUtil.java#L43-L48)

Thanks!

**Comment by peterpetrekanics** [comment]
Dear @ericyanLr,

No worries - I have read the references you've sent.
I have created a new fix based on that, in a new repository.
I am going to close this PR now and send you a new pull request with this latest fix.

Best Regards,
Peter

**Pull request closed without merging**
