### PR TITLE
[TS] LPS-133074 Avoid denied access in cases where an object has a valid companyId

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi @ericyanLr ,

Thank you for checking my pull:
https://github.com/ericyanLr/liferay-portal-ee/pull/72

Just like you asked, I have tested the steps on master, and created this new pull request.
Please review my fix, and if you approve this change, please forward it to the next approver.

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

Can you help provide an explanation regarding your commit message:
> Avoid denied access in cases where an object has a valid companyId

From my understanding, the current existing code: `currentCompanyId != (Long)function.apply(object)`, is also doing the same thing. And so, when I read this commit message, I feel it's a bit confusing and doesn't help me easily understand why this additional condition is being added. 
- The commit message sounds as if it's proposing to add an entirely new check, but don't we already have existing logic that is checking if an object has a valid companyId? 

It's also possible that I'm misunderstanding the current code as well, please let me know if that's the case.

Hopefully that makes sense. 

Please let me know your thoughts.
Thanks!

**Comment by peterpetrekanics** [comment]
Hi @ericyanLr ,

I agree, this may be a little confusing. Actually, the code change suggestion comes from the customer, and on my side it solved the issue indeed.
My understanding is that this is the additional check that was added:
(CompanyConstants.SYSTEM != objectCompanyId)

Do you have a suggestion on what the commit message should be? Just let me know and I can re-phrase it, no problem.
Many thanks,
Peter

**Comment by crabel** [comment]
To clarify the issue: I wrote those lines, so I can explain them.

The current code blocks access to all objects that don't belong to the current company (e.g. 20116 or something like that). That change was introduced this year and improves the security, it is not possible to access objects belonging to other companies anymore. That's good, I fully agree!

But it has a hole, there are some objects, like the documenttype BASIC_DOCUMENT, that have a companyId of 0. So, if you want to handle files differently in freemarker based on the document type, you run into an "Access denied" error. And that's simply not correct. BASIC_DOCUMENT should be accessible.
This commit checks for that too and allows objects with companyId == 0 too.

So, maybe a commit message like this would be better:
Allow access from freemarker to objects belonging to SYSTEM and not only the current company

**Comment by ericyanLr** [comment]
Hi @crabel ,

Thanks for the explanation for your suggested fix.

@peterpetrekanics , does this explanation help provide additional context to help you better understand the change you are proposing in the PR?

Basically, I just wanted to make sure you understood the change you are proposing. And if so, providing a simple explanation would be helpful for reviewers (which, if can be accomplished by the commit message, would be preferred).

However, the commit message you provided does not really help explain the additional check you are proposing. And usually if the explanation is unclear through the commit message, at least some explanation would instead be provided in the ticket description.

Please let me know your thoughts and whether you would like any more changes.

For instance, if you feel that nothing needs to be changed in the PR and @crabel 's explanation is exactly what you would have provided, please confirm that. If not, feel free to make changes and/or provide an explanation for the change.

Thanks!

**Comment by peterpetrekanics** [comment]
Hi @ericyanLr ,

Thanks for checking with me - actually my goal is to provide an SDH as soon as possible because the CS Team asked for urgency.
As for me, I don't want to hold up the approval process by making further changes - like you said I can confirm that there are no changes needed in the PR and crabel's explanation is exactly what I would have provided.
My original commit message was: "Avoid denied access in cases where an object has a valid companyId" and as crabel said the companyId: 0 is a valid one so that is why I thought that my commit message was ok.

Anyway now I have 2 questions / discussion points:
- in order to create an SDH, I need your approval, so please confirm that
- if you still think that I should change the commit message pls let me know and of course I can do that (just let me know what the message should be)

I will update the LPS ticket now to provide a more detailed explanation for future readers :)

Thanks again for all your help,
Peter

**Comment by achaparro** [comment]
Hi @peterpetrekanics,

I will answer your questions since @ericyanLr is on PTO next two days:
- _in order to create an SDH, I need your approval, so please confirm that_
Without a further analysis this is not a valid fix. With this change we always allow to access to any kind of object with companyId 0. It is ok to access to the Basic Document Type from any company but, we have to analyze in deep if other objects are created or can be created with companyId 0 (as far as I remember, at least some images could be created with that companyId) that should be accessed only from the default company. Even if we don't currently create other objects with companyId 0, this fix opens the door to potential issues in the future.

Regarding the approval for the SDH, this can be valid for a specific installations where is ok to access to these objects from any company however, we can't deliver the solution from Liferay Support since it can cause security issues in the future and we would be responsible for them.

So, in order to solve the issue we have three options:
- Analyze which objects are created or can be created with companyId 0 and verify the access scope for those objects. We should also restrict future cases based on some kind of security rule.
or
- Create the BASIC DOCUMENT for every companyId
- Any other idea that can allow access to the BASIC DOCUMENT


- _if you still think that I should change the commit message pls let me know and of course I can do that (just let me know what the message should be)_
We have to verify previous point first.

Let me know if I missed something.

Thanks

cc/ @peterpetrekanics @crabel

**Comment by crabel** [comment]
Hi @achaparro, @peterpetrekanics 

First of all, please take your time. We have already implemented a workaround for the issue at hand (we test for the typeId of the documents and only fetch the type if it doesn't throw). I will also update the ticket with the information that this is not urgent.

Well, this is a complicated issue and I have multiple points. 

1) When you enable ServiceLocator, I think, you already need to really trust the people who are allowed to edit templates. I am quite sure, once I can edit templates, I can make myself at least admin. Maybe I can get hold of e.g. CommandProcessor (oh, yes, I can) and then I can do anything I want.

I think, serviceLocator is broken beyond repair, there are too many loopholes ...

And when you introduced the restriction we are talking about (in January, I think), you broke stuff. I know of at least one other customer, who uses ServiceLocator, document types and templates. Maybe two. And both want to upgrade to 7.3 soon. So, I predict, support will get further tickets about this. IMHO opening this up would not be a big deal and give you some time to properly evaluate the situation. But that's your choice.
(Note: I am not sure if you can get the document object otherwise)

2) Since you obviously are not sure, which objects are or can be placed in SYSTEM, you really should evaluate that. I did a quick check with a query, several of the tables in our db have entries with companyId == 0, summing up to several thousand lines across several tables (The journalarticleresource table seems to contain many, I am not sure if that's intentional or an issue). 

Since the DB was upgraded, it might also be a legacy/upgrade issue. Skimming through the entries, it might well be that BASIC_DOCUMENT is the only object that is "interesting" for freemarker.

3) If you go for adding a BASIC_DOCUMENT type for each company, please do it only in a major upgrade (e.g. in 7.4), I really dislike fixpacks with DB changes. This looks like a major change to me and it should be tested thoroughly.

Well, that's my two cents. As I said, we have a workaround in place, so take your time.

Kind regards, Christoph

**Comment by achaparro** [comment]
Hi @crabel,

Thank you for your input, it is really valuable for us.

> When you enable ServiceLocator, I think, you already need to really trust the people who are allowed to edit templates. I am quite sure, once I can edit templates, I can make myself at least admin. Maybe I can get hold of e.g. CommandProcessor (oh, yes, I can) and then I can do anything I want.

I agree with that but in some cases (like the one required by this change) every company is maintained by different organizations and we shouldn't allow access to the others.

At this point I think we need:
1. Analyze in which cases we use the companyId 0
2. Depending on that, make a decision about how to fix it.

@peterpetrekanics please, complete the point 1 and contact me and @ericyanLr to make a final decision with the Core Infra team.

I think @crabel is right and we can have more customers with this issue so we should solve in the next week maximum.

Thanks.

**Comment by achaparro** [comment]
ci:close

**Pull request closed without merging**
