### PR TITLE
Lps 183421

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-183421

Applying this fix based on [PTR-3835](https://issues.liferay.com/browse/PTR-3835)

I was not able to get CacheRegistryUtil.setActive(false) to work for the test.

I was not sure whether I should apply the fix to this instance as well https://github.com/liferay/liferay-portal/blob/e57cae7bea4b38dd0f319ac072df90a1c1976df2/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L4546
Are there steps I can take to test updating an incomplete user?

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

**Regarding:**
> I was not able to get CacheRegistryUtil.setActive(false) to work for the test.

I was able to get it to work by also including: `_classNameLocalService.checkClassNames();`. Doing this allowed the test to reproduce with just one layout.
- Branch: https://github.com/ericyanLr/liferay-portal/tree/pr-305_LPS-183421_POC
- Commit: https://github.com/ericyanlr/liferay-portal/commit/2619c2962369a5ae02098817efc7a4c77e2e3510

Explanation:
- Calling `CacheRegistryUtil.setActive(false)`, resulted in clearing the map for [ClassNameLocalServiceImpl.java#L153-L156](https://github.com/liferay/liferay-portal/blob/7.4.3.74-ga74/portal-impl/src/com/liferay/portal/service/impl/ClassNameLocalServiceImpl.java#L153-L156)
- As a result, the StaleStateException was being swallowed (You could still see a mention of the exception in the console though)
- The exception was being swallowed when calling: [CTPersistenceHelper.isProductionMode()](https://github.com/liferay/liferay-portal/blob/7.4.3.74-ga74/modules/apps/change-tracking/change-tracking-service/src/main/java/com/liferay/change/tracking/internal/CTPersistenceHelperImpl.java#L103-L104) during the Expando service calls
  - --> [ClassNameLocalServiceImpl.java#L116](https://github.com/liferay/liferay-portal/blob/7.4.3.74-ga74/portal-impl/src/com/liferay/portal/service/impl/ClassNameLocalServiceImpl.java#L116)
  - --> [ClassNameLocalServiceImpl.java#L40-L56](https://github.com/liferay/liferay-portal/blob/7.4.3.74-ga74/portal-impl/src/com/liferay/portal/service/impl/ClassNameLocalServiceImpl.java#L40-L56)
    - I'm thinking it gets swallowed because of the annotation: `@Transactional(propagation = Propagation.REQUIRES_NEW)`
- Since the exception was swallowed, it no longer affected our transaction and the test continued successfully

**Regarding**

> I was not sure whether I should apply the fix to this instance as well https://github.com/liferay/liferay-portal/blob/e57cae7bea4b38dd0f319ac072df90a1c1976df2/portal-impl/src/com/liferay/portal/service/impl/UserLocalServiceImpl.java#L4546
> Are there steps I can take to test updating an incomplete user?

It took me awhile to figure out where incomplete users were created, Jonathan helped point out that these users can be created when adding comments as a guest
- Add blogs portlet
- Add new entry
- As guest user
  - View page with blogs portlet
  - Click comments
  - Click reply
    - Notice a login screen comes out
    - Notice the login screen has a Guest link, to create a guest account

With that said though, I don't think there's a simple way to reproduce this scenario with this type of user.

Since the logic you pointed out is quite old, I think it would be okay to skip this one. We could always add it if the issue actually comes up in the future. (or if you feel like you want to include it, that's fine as well).

**Other Thoughts**
For the changes, can you also include the comment for Expando? Based on the PTR ticket, I think Hai's suggestion is to include it to match the pattern

Example:
```
layout = layoutLocalService.updateLayout(layout);

// Expando

layout.setExpandoBridgeAttributes(serviceContext);
```

As for whether to include the test case with a single layout or two layouts, I think either of the tests are fine. To me, the single layout looks a bit more clear in what's being tested. Another option would be to include both test cases, if we determine the test cases serve different purposes.

But ya, feel free to decide on which test case to use. In the end, I would say it would be up to the Publications team (since LayoutCTTest class belongs to Change Tracking) or Core Infra Team, which would be reviewed by the Product Team when we send up the PR.

Feel free to let me know if you have any questions.
Thanks!

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
Hi @ericyanLr 
I've added the commit for the add methods

**Pull request closed without merging**
