### PR TITLE
LPS-161738 Render the portlet URLs for all tabs in the item selector based off of the scope group

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-161738

The issue here was that the tabs in the item selector would navigate to the referrer group instead of the scoped group when the selected site was different than the referrer group.
To fix this issue, I had the getPortletURL method in ItemSelectorImpl always pass in the scopeGroup when rendering the portlet url.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
Hi @ericyanLr 

Were you able to look into this fix further?

Thanks!

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Apologies for the delay, will be able to review this today.

**Comment by ericyanLr** [comment]
As discussed, we will be trying a different approach to resolve this issue. Closing out this PR.

**Pull request closed without merging**
