### PR TITLE
[TS] LPS-114409 InvocationTargetException occurs during Liferay startup if there is a subfolder in osgi\configs

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi @ericyanLr ,
Please review my fix, and if you approve this change, please forward it to the next approver,
Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

From my understanding, this change is to:
- Account for sub-directories in osgi/configs
- Allow for processing .config files in subdirectories in one level depth
- Account for kubernetes ConfigMap?

However, do you know if Liferay currently processes **.config** files in sub-directories?

I tried testing in master and 71x, however, I was unable to introduce a **.config** file in a sub-directory that affected a System Settings property.

Can you help provide additional context and clarify the goal(s) of this fix?
Thanks!

**Comment by peterpetrekanics** [comment]
Dear @ericyanLr,

Yes sure, let me send you the full info:
1. The primary goal of this fix is to ensure that the portal can be started up, even if there is a sub-directory in the osgi/configs folder. Detailed reproduction steps can be found in LPS-114409. The directory can be empty or it can contain a .config file - this was not specified in the original issue description in the LPP, however my fix can read a .config file if it is placed in the sub-directory.
2. The secondary goal is that the portal can read one or more config files if they are placed in the sub-directory. Only one level depth is enabled, it is enough for the customer who reported the problem.

The customer mentioned that this behavior was introduced with DXP 7.2, and that this was not a problem in 7.1.
While analyzing the issue on the LPP, I found that LPS-97609 is causing this new behavior, we have re-organized the code because the portal was unable to connect to Solr with SSL configuration during initial startup. I did not want to revert this LPS because we may have further improvements or changes that are already based on this fix, and for me it was much simpler to add my fix to ModuleFrameworkImpl, it is just a few lines of code and it fixed the issue.

The customer's comment about kubernetes is something that you can ignore, it is not really important if we are officially supporting kubernetes ConfigMaps in this case, the important thing is that if there is an extra folder created in osgi/configs then the 7.1 portal is starting up while 7.2 is not starting up.   

For my fix, I have used yesterday's master code base for testing (9617f95b39dbb47f032785f08b71932038e1bb9e): I created a sub-directory in osgi/configs and placed an exported .config file. Let me send you the detailed testing steps to show that with my fix, indeed a .config file placed in a sub-directory is affecting the System Settings:

1. Build my fix and start up the portal
2. Log on as admin and go to:  Control Panel / Configuration / System Settings / and randomly pick a setting, I choose: Adaptive Media
3. Within Adaptive Media, I will change a setting to see if it can be exported / imported correctly:
Go to Adaptive Media / Processes and change Max Processes from 5 to 7
4. Click on Save and then on the right hand side click the 3 dots and click Export, save the .config file to your PC.
5. Change the Max Processes back to 5 manually so that we can see if the .config file will be imported successfully.
6. Shut down the portal and place the resulting .config file in this folder:  osgi/configs/testsubdirectory
7. Start up the portal again and check if the Max Processes value indeed changed from 5 to 7 as a result of the .config import.

During my testing the .config file was imported correctly every time, I also tested with other random setting options. I have used my Ubuntu 18.04 PC with JDK 1.8 for testing.

Please let me know in case further explanation is needed.
The customer would expect a reply very soon.

Thank you very much,
Peter

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

In regards to your comment, the main focus would be your goal # 2: 

> The secondary goal is that the portal can read one or more config files if they are placed in the sub-directory. Only one level depth is enabled, it is enough for the customer who reported the problem.

**Question**
Again, my question is: do you know if Liferay currently processes .config files in sub-directories?

From my testing (master + 71x):
- I was unable to introduce a .config file in a sub-directory that affected a System Settings property.

From your previous comment, I understand that testing with your proposed fix would satisfy this behavior (and the steps you provided, does reproduce and demonstrate that).

However, can you confirm whether this behavior of: **using .config files in sub-directories**, really is working in master + 71x?

- If so, can you provide steps to reproduce for that?

Again, from my testing, I am not able to get it to work (without your proposed fix).

**Additional Thoughts**
Again, the uncertainty here is goal # 2.

If the goal were to just fix goal # 1, to resolve the startup issue, that makes sense to me and we can send up a specific commit just for that.

However, goal # 2's behavior is still unconfirmed, at least from my testing.

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by peterpetrekanics** [comment]
Dear @ericyanLr ,

I am sorry now I understand - after clarifying with the client now it is clear to me that they only want to have the sub-directory ignored, and the config files should not be imported from that folder - I guess I wanted to do more than needed :)
So now I have modified my fix and force pushed it here - please review it and forward to the next approver if you agree with these changes.

Thank you very much,
Peter

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

Looks good, I'll be forwarding it to the next reviewer.
Thanks for making the changes!

**Comment by ericyanLr** [comment]
Reviewed and sent to Matt for further review: https://github.com/mtambara/liferay-portal/pull/988

**Pull request closed without merging**
