### PR TITLE
Lps 169881

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-169881

The issue here is that Liferay.Util.fetch does not handle impersonated users. 
To fix the issue, I passed the impersonated user's id from the Liferay.Util.fetch method to the request 

I also cleaned up instances where the doAsUserId is passed into the fetch method. 
There were two instances that I wasn't sure if it should be removed or not. The doAsUserId being passed here could be a custom value and not necessarily the same as the one stored in the themeDisplay. 
So, I thought I would leave it up to the product team to decide whether it is safe to remove these additions of doAsUserId to the fetch method.
https://github.com/liferay/liferay-portal/blob/321766dacdc65adcf958db582121ed699763277d/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/portlet.js#L36
https://github.com/liferay/liferay-portal/blob/321766dacdc65adcf958db582121ed699763277d/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/util.js#L653

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Can you provide more context, regarding where `config.data.doAsUserId` would eventually be processed?

From my understanding, this eventually calls the Fetch API:
https://developer.mozilla.org/en-US/docs/Web/API/fetch#syntax

Looking at the spec, the `options` parameter doesn't have an expected object called **data**; does that mean Liferay is managing this **data** object and processing it somewhere?

**Comment by noornajj** [comment]
Hi @ericyanLr,
I'm not %100 sure how this is working. I thought that the data gets added as a parameter to the url. 
Before trying this implementation, I was thinking of adding it to the body as `URLSearchParams` but this example uses a GET method which doesn't have a body.

Then I saw this [example](https://github.com/liferay/liferay-portal-ee/blob/9eed98a82d85e14f9ca088d6314243e9fc8d18f0/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/store.js#L79-L83) but I didn't notice that these data values are eventually added to the body. 

I also tried changing the fix to:
`if (doAsUserIdEncoded) {
	headers.set('doAsUserId', doAsUserIdEncoded);
}`
This worked as well. Would this implementation make more sense?

**Comment by ericyanLr** [comment]
Hi @noornajj ,

When testing the proposed fix, I actually see errors in the console, regarding the data object:
```
Uncaught TypeError: a.data is undefined   [ fetch.es.js:58:13 ]
    default fetch.es.js:58
    <anonymous> guest:3328
     ...
    <anonymous> aui_sandbox.js:37
    ...
```

And so, I wasn't able to get the fix to work. 

**Regarding:**
> I also tried changing the fix to:
> if (doAsUserIdEncoded) { headers.set('doAsUserId', doAsUserIdEncoded); }
> This worked as well. Would this implementation make more sense?

I think that could be something to consider. For instance, this would avoid tampering with a user's form data.

But, one thing I would suggest exploring, would be how Liferay.Util.fetch is being used in our code base and how do some of those use-cases incorporate the doAsUserId parameter.

**Comment by noornajj** [comment]
Hi @ericyanLr,

Here are the updated commits. Let me know if you have any comments or concerns.

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

I'm not sure to what extent we would like to handle an impersonated user when using this util method, but here is a scenario that I wanted to bring up to see if it should be something we need to handle as well:

**Scenario: Use Liferay.Util.fetch to load a page (e.g. page from a private site)**

1. Enable private pages
2. Create a site called: **privateSite**
    1. Create two pages: **pageA** and **pageB**
3. Edit the main **/web/guest** home page
    1. Add an HTML fragment with the following content:
        ```
        <script type="">

        Liferay.on('allPortletsReady', function() {
          Liferay.Util.fetch(
              '/group/privatesite'
          ).then((response) => {
               console.log(`Response status: ${response.status}`)

              if (response.status === 200) {
                  return response.text()
              }
          }).then((responsePayload) => {
                let div = document.getElementById('testDiv');
                div.innerHTML = responsePayload;
          });
        });
        </script>

        <div id="testDiv">
        ```
4. **Notice:** The page loads as expected, showing the private site with tabs of the 2 pages
5. Create user: **test1**
6. Create user: **test2**
    1. Add **test2** as a member of **privateSite**
7. Impersonate **test1**
    - **Notice:** The page still loads, even though **test1** should not be able to see the private site
8. Impersonate **test2**
    1. **Notice:** The page still loads, but the user shown on the private site is not **test2**
    2. Future Test: Click on **pageB**
        - If we were to support this behavior, I would assume the page would load **pageB** as the impersonated user

Can you share your thoughts on this type of scenario?
Thanks!

**Comment by noornajj** [comment]
Hello @ericyanLr,
Just for clarification, is the site private, or pages A and B private?

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Woops, forgot to clarify that part. I forget if there's actually way to make a site "private", but all I did was:
- Create a site named: **privateSite**
- Create two private pages: **pageA** and **pageB**

The goal was basically to demonstrate:
- what happens if the HTML fragment accesses a resource that the impersonated user does not have access to 
- or what happens if they click on a link within that requested resource (does the link account for doAsUserId? if not, should it?)

**Comment by noornajj** [comment]
Hello @ericyanLr,
I believe you are correct. I have adjusted the code and tested to make sure everything still works as expected

**Comment by noornajj** [comment]
Hi @ericyanLr 

I have made the adjustments we discussed in out call and edited the description accordingly

**Comment by ericyanLr** [comment]
Thanks Noor, reviewed and sent for further review:
https://github.com/liferay-frontend/liferay-portal/pull/2900

**Pull request closed without merging**
