### PR TITLE
LPS-134094

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-134094

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @holatuwol ,

Would you happen to know how to handle that test failure? 

I was able to find the script executing this, but not sure how to handle it.
https://github.com/liferay/liferay-portal/blob/master/build-test-batch.xml#L6772-L6777

**Comment by holatuwol** [comment]
Ah, I missed the `@generated` annotation on it, so I need to fix the .ftl instead.

**Comment by ericyanLr** [comment]
ah icic, that makes sense! I'll close out this PR then, feel free to resend.

**Pull request closed without merging**
