### PR TITLE
LPS-106586 Escape the properties to be exported

### PR DESCRIPTION
**Pull request by hudakl**
Hi Eric,

This is a followup of this pull: https://github.com/ericyanLr/liferay-portal/pull/154
As discussed, I added the test.

Could you please review the changes?

Thanks,
Laci

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @hudakl ,

**Your Proposed Fix**
Regarding your proposed fix and test, I had a few questions that came to mind, regarding the following:

###### EscapePropertiesUtil Class
1. What's the advantage of creating this EscapePropertiesUtil class?
   - e.g. reusability, clarity, better architecture, etc. ?
2. Would adding the method directly in **ExportConfigurationMVCResourceCommand** also be an option? 
   - e.g. Is there a disadvantage of doing that vs creating the EscapePropertiesUtil class?
3. If you decide on using the EscapePropertiesUtil class, does the class name and method name properly represent what your logic is accomplishing?
   - e.g. If someone looks at your class, is it clear what your method does and how they can utilize it?
     - To me, it seems unclear. I'm not sure what type of properties would require that type of string replacement and what it's trying to escape.
4. From what I can tell, the method [EscapePropertiesUtil::escapeProperties](https://github.com/ericyanLr/liferay-portal/commit/f3b7eed69c341be189aede23964e1be26cef9344#diff-9323f128e06015b2afb908c19640e948R30-R36) doesn't actually do anything for your String[] case.
   - Can you verify whether this is really the case?

###### Test Case(s)
1. I noticed you introduced: **_exportImportTypedProperties**. 
   - Is **_exportImportProperties** not capable of testing for your test case(s)?
2. Do you have other test cases that could help to make sure your new changes are working as expected?
   - e.g. property value that:
      - includes property substitution
      - includes nested property substitutions
      - includes an escaped property substitution
      - includes an incomplete/invalid property substitution
      - etc.

Feel free to let me know if you have any questions.
Hope that helps.

**Comment by hudakl** [comment]
@ericyanLr 

Here are my answers:
    What's the advantage of creating this EscapePropertiesUtil class? e.g. reusability, clarity, better architecture, etc. ?
		Yes, mostly these, in your secon

    Would adding the method directly in ExportConfigurationMVCResourceCommand also be an option? e.g. Is there a disadvantage of doing that vs creating the EscapePropertiesUtil class?
		Other classes that might need it and also the test wouldn't be able to use it, if it would be there.
	
	If you decide on using the EscapePropertiesUtil class, does the class name and method name properly represent what your logic is accomplishing? e.g. If someone looks at your class, is it clear what your method does and how they can utilize it? To me, it seems unclear. I'm not sure what type of properties would require that type of string replacement and what it's trying to escape.
		That's the best name I could come up with. However, if you have something more suitable in mind feel free to rename it.
	
    From what I can tell, the method EscapePropertiesUtil::escapeProperties doesn't actually do anything for your String[] case. Can you verify whether this is really the case?
		To think about it, that might indeed be problematic. My tests might not have covered that properly. However, my original version looked like this in line 34:
			property = escapeProperty(property);
		for which I got this sourceFormat error:
			No need to assign call to variable 'property', because 'property' is not used after the call: .../EscapePropertiesUtil.java 34 (Checkstyle:UnnecessaryAssignCheck)


Test Case(s)

    I noticed you introduced: _exportImportTypedProperties. Is _exportImportProperties not capable of testing for your test case(s)?
		No it's not. That's why I introduced the new method. I needed to resolve escaping for a proper test. The ConfigurationHandler.read didn't do that, TypedProperties.load did.
	
    Do you have other test cases that could help to make sure your new changes are working as expected?
        e.g. property value that:
            includes property substitution
            includes nested property substitutions
            includes an escaped property substitution
            includes an incomplete/invalid property substitution
            etc.
		Could you please give me examples to these? I'm not sure what exactly mean by property substitution in this case.

**Comment by ericyanLr** [comment]
Hi @hudakl ,

I kinda see what you mean, I thought that the issue would be reproducible when using **ConfigurationHandler.read*. I have a feeling it might be due to different versions of the OSGI library being used for the export and for the import.

Maybe that's something to investigate as well if you're familiar with what's happening during the import.

When I get a chance, I'll help take a look as well to confirm.

**Comment by ericyanLr** [comment]
**Additional Note**
To elaborate on:

> I thought that the issue would be reproducible when using ConfigurationHandler.read

I'm not sure if I remember this correctly, but from what I remember, during the import, **ConfigurationHandler.read** eventually called **TypedProperties.load**. 

But, I'm not exactly sure if this is the case and would have to verify. I forget if the newer version of the OSGI library called **TypedProperties.load** and if the older version did not.

**Comment by ericyanLr** [comment]
Hi @hudakl ,

**_exportImportTypedProperties method**
I took a look at the scenario again and noticed that the escape happens during import, due to OSGI's ConfigInstaller, specifically this line: [ConfigInstaller.java#L271-L278](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/modules/third-party/org-apache-felix-fileinstall/src/main/java/org/apache/felix/fileinstall/internal/ConfigInstaller.java#L271-L278)

Our .config file get's loaded into TypedProperties and that's where the substitutions occur.

With that in mind, it makes sense to me now, why you are introducing the new **_exportImportTypedProperties** method.

**EscapePropertiesUtil**
In regards to introducing this new class, I think one option would be to instead move your method into **ConfigurationExporter**.

From what I can tell, this logic seems very unique and would unlikely be re-used in other places. Placing it within this class makes sense to me, since it appears to mainly be used in conjunction with the **ConfigurationExporter**.

Also, if the logic resides within **ConfigurationExporter**, it would also make it easy to utilize within the test class as well.

Feel free to let me know what you think regarding this.

**Test Case - Examples**
In regards to your test case examples, your current test case tests for this string:
```
String nestedValue = "${foo.${bar}}"
```

I think it would be useful if we also test for other scenarios, such as:
- "${foo"
- "${foo ${bar}"
- "${foo"
- etc.

This would help to ensure that your new string replacement doesn't cause any unexpected side effects.

Please let me know if you have any questions with moving forward with this fix.
Hope that helps.

**Comment by hudakl** [comment]
Hi @ericyanLr ,

Thanks for your reply!

I can move the escaping to the ConfigurationExporter, however, it will be slightly more complex, as iterating the Dictionary object is a bit more complicated.

Thanks for the examples. I'm a bit confused, though. As I see, these proeprties are incorrectly formatted and they will cause errors regardless of the escaping during the export. If that's the case, why should we run tests on them to see if the escaping works? I think the current test proves sufficiently that the escpaing works correctly for a correctly formed proeprty.

Thanks,
Laci

**Comment by ericyanLr** [comment]
Hi @hudakl ,

**Regarding:**

> I can move the escaping to the ConfigurationExporter, however, it will be slightly more complex, as iterating the Dictionary object is a bit more complicated.

Sorry if there was a confusion, but what I meant by moving the logic to ConfigurationExporter was basically, you can add your method in there instead of creating a new class.

Meaning, instead of **EscapePropertiesUtil.yourEscapeMethod**, it would just be **ConfigurationExporter.yourEscapeMethod**.

**Regarding:**

> Thanks for the examples. I'm a bit confused, though. As I see, these proeprties are incorrectly formatted and they will cause errors regardless of the escaping during the export. If that's the case, why should we run tests on them to see if the escaping works? I think the current test proves sufficiently that the escpaing works correctly for a correctly formed proeprty.

Basically.. these properties are technically.. not incorrectly formatted. They just represent values that may possibly have such a format.

The goal is to make sure that the properties are still exported as expected, even with our introduced changes.

For instance.. if we use **${foo** as an example..
- **${foo** is saved as a property
  - key: test
  - value: ${foo
- We run our export test and retrieve the new outputted properties
- We expect the new outputted properties to be:
  - key: test
  - value: ${foo

However, if for some reason your new proposed change results in the new outputted properties to be:
  - key: test
  - value: $\\{foo

If this happens and the test fails, then this would mean that your proposed change would introduce a regression.

-----

One way to arrange and work on your proposed fix is like this:
1. Add test commits (with all your test cases)
2. Run test without your changes (all tests pass)
3. Add your proposed fix commits
4. Run test 
5. Check if all tests pass
    - If a test fails, fix proposed fix
    - Repeat steps 4-5

Feel free to let me know if you have any further questions.
Hope that helps clarify things.

**Pull request closed without merging**
