### PR TITLE
LPS-84320

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-84320

Same code than https://github.com/ericyanLr/liferay-portal/pull/134 but I have done some changes:
- Modified last commit, now I am doing `Objects.equals` instead of `.endsWith`, so now only specific email addresses are blocked
- Added `noreply@liferay.com` , `test@domain.invalid` and `noreply@domain.invalid` to blacklist

**In order to clarify this PR and LPS, I am explaining my two goals:**

1. **Goal 1** Stop customers using `@liferay.com` emails: They should use their own email.
      - That is done removing default value from setup wizard and portal.properties.
      - Having a `@liferay.com` as a default value is risky, as they can use it and third people will reach us.
2. **Goal 2** In case we have bad luck and somebody tries to send a email using `test@liferay.com` or `noreply@liferay.com`, blacklist that emails by default:
      - Old customers will have `test@liferay.com` unless they manually change their `portal-ext.property`
      - But we should allow removing them from blacklist just in case we need to unlock it 

In my opinion, if we only block the email but we don't change the default values, we could have problems in a future. For example:
   * In a future Liferay version perhaps a new Liferay component could use `admin.email.from.address` configuration without filtering the wrong `test@liferay.com` email.

**About your comments in https://github.com/ericyanLr/liferay-portal/pull/134**

*First comment*
> Would the second commit: 5caf27f no longer be needed, since we have the third commit?

Second commit is necessary in case a customer don't use setup wizard to configure a new Liferay and they just configure `portal-ext.property` with setup wizard disabled.

Setting `admin.email.from.address` and `announcements.email.to.address` will avoid them using `@liferay.com` emails.

If we maintain `test@liferay.com` some customers can just remove it from the blacklist and they will continue sending emails using that `@liferay.com` address.

*Second comment*
> The reason I mention this is that currently, the 3rd commit looks kinda like a new feature, to provide the ability to:
>    Blacklist specific email addresses
>    Blacklist email addresses belonging to a domain
> But, looking at the implementation, it looks like it would fail for certain cases, since > it's only making a emailAddress.endsWith(...) comparison.

In this PR, I have simplified this code, now I am doing `Objects.equals` instead of `.endsWith`, so now only specific email addresses are blocked

*Third comment*
> 3rd Commit - Simplification
> From my understanding, the main fix is blacklisting the email address: test@liferay.com
> Would adding a simple implementation to block the email address: test@liferay.com, be sufficient?

As I said above,  I have simplified a bit this code, now, only specific emails are blocked.

But I don't think it is a good idea to block "test@liferay.com" inside java code, it is better to maintain blocked email addresses in portal.properties:

1. It is a bad idea to hard-code an email address inside java code.
2. We should allow customers to revert "test@liferay.com" blacklist to avoid complains from existing customers.
3. Having a property in *portal.properties* will also allow blocking other email addresses in case it is necessary.

Thank you

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @jorgediaz-lr ,

Thanks for the detailed notes and responses.

In regards to my comment regarding the 3rd commit simplification, apologies for the confusion, I basically meant simplifying to just match single email values. 

But, your latest commit alleviated my concern for the previous implementation of **endsWith** and now only takes single email values.

I have reviewed and forwarded to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/8200

**Pull request closed without merging**
