### PR TITLE
Lps 146666 2

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-146666

Added test case as well as cleaned up the code by removing a check that was not needed.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Reviewed and sent to Team Lima for further review: https://github.com/liferay-lima/liferay-portal/pull/2785

**Pull request closed without merging**
