### PR TITLE
LPS-90376

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-90376

Hey Eric,
I initially sent this PR to @lipusz, but he feels it's better suited to Core Infra.  Let me know if you have any questions about it.  Here's the original message: 

> I looked into this issue and found by setting the windowState to Maximum, everything works correctly because we need [the stateMax variable to be true in header_portlet.jsp](https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/portal/header_portlet.jsp#L50).  Setting the lifecycle to 1 (to reproduce the issue) and manually changing this variable to true once hit through a breakpoint is enough to resolve the issue.
> 
> My only hesitation has to do with the portlet phases and if this is the "right" solution.  I'm not sure if there is some reason we shouldn't be executing this logic if in the action lifecycle, but I haven't seen any issues, nor have any tests failed.
> 
> Please let me know what you think, thanks!

CC @jrao

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jrao** [comment]
@ChrisKian Makes sense. Implemented the fix you suggested here: https://github.com/ChrisKian/liferay-portal/pull/106

**Comment by ericyanLr** [comment]
Hi @ChrisKian ,

I did not have time to take a look at this today.

My initial plan is to investigate whether the main factor is having the WindowState as max or just having a proper WindowState.

**Comment by ericyanLr** [comment]
Forgot to update/close this pr.

Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/7418

**Pull request closed without merging**
