### PR TITLE
LPS-130651 Slow loading of Users & Organizations page (Cont)

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-130651](https://issues.liferay.com/browse/LPS-130651).<br/><br/>Hey Eric, will you please test these changes against the known use-cases\? Please let me know if there is anything more needed.<br/><br/>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @drewbrokke ,

From my testing of the proposed changes, I found two behaviors that have been affected:
1. Non Site Administrators can view all users if they have the following permissions:
    - Site Role: People > Memberships > Access in Site and Asset Library Administration 
    - Site Role: People > Memberships > Site: Assign Members
2. Account Managers cannot view users that they created
    - Follow the steps to reproduce in this ticket: LPS-130611
    - Account Manager cannot view users they created in both: 
        - Users and Organizations page
        - Accounts > Account Name 1 > Users tab

**Todo: Test if adding 6000+ users to the same Organization results in slow load times** 
This is another test case I just thought of, which may not be covered. 

Test: If a user has the Organization Role: Manage_Users and the organization that they manage has 6000+ users, would loading the Users and Organizations page be slow?

Will do some testing for this test case, since it may be a commonly encountered scenario.

**Comment by drewbrokke** [comment]
I'm not as sure about what the best path forward is for number 1, I'll think about it. I'm still toying with the idea of requiring VIEW permissions for users, but if it's not possible from a customer perspective I understand.

**Comment by ericyanLr** [comment]
Hey @drewbrokke ,

**Update - Test Case**
I did further testing on that test case I mentioned:
- Add 6000+ users to testOrg
- Add a user: manager to testOrg with Organizational Role: Manage_Users
- Login as user: manager and navigate to Users and Organizations - Users Tab

**Result:** With the proposed changes, the page takes awhile to load (~10-15 seconds without cache). 

I'm guessing this is due to all the post-filtering that still has to be done to check if the manager user can actually view the returned users from testOrg.

**Comment by drewbrokke** [comment]
Ah I see. This is a case where we have returned to permission checking each individual model. I'll address the other issues, then we can work on a solution for this last case.

**Comment by drewbrokke** [comment]
Force-pushed a fix for issue number 2

**Comment by drewbrokke** [comment]
See https://github.com/liferay-search/liferay-portal/pull/123

**Pull request closed without merging**
