### PR TITLE
Test: Trigger jdk 21 integration tests

### PR DESCRIPTION
**Pull request by ericyanLr**

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:jdk21-integration

**Comment by ericyanLr** [comment]
ci:report:2542059924

**Comment by vicnate5** [comment]
ci:report:2542059924

**Comment by ericyanLr** [comment]
ci:test:jdk21-integration

**Comment by ericyanLr** [comment]
ci:test:jdk21-integration

**Comment by ericyanLr** [comment]
ci:report:2542662412

**Comment by ericyanLr** [comment]
ci:report:2542662412

**Pull request closed without merging**
