### PR TITLE
LPS-106585

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi @ericyanLr !

I'm continuing with the work you and Roland did not long ago for https://issues.liferay.com/browse/LPS-106585 and I wonder if you could take a look to this new PR.

During my tests I could confirm that it was originally caused by https://issues.liferay.com/browse/LPS-93973, and the changes made in this PR don't break neither LPS-93973 nor https://issues.liferay.com/browse/LPS-95208.

As you can see I've taken a totally different approach than the ones you were talking about in the related PTR or LPS, but I'm not totally sure it is the best one. But since it's passed all the relevant tests in my ci (you can check the results in https://github.com/crodriguezy/liferay-portal/pull/164) I think it may be a good candidate for the fix, but I feel I a second opinion of someone with the context would be useful here.

Thank you in advance!

**Comment by ericyanLr** [comment]
Hi @crodriguezy ,

Thanks for the quick update regarding this ticket. I did not have time to dive into this today, should have some time next week.

**Comment by crodriguezy** [comment]
No problem, @ericyanLr , thank you!

**Comment by ericyanLr** [comment]
Hi @crodriguezy ,

**Context**
After taking a closer look at the issue, I think I now understand more of what's going on:
- Layouts with the type: [LayoutConstants. TYPE_URL](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/portal-kernel/src/com/liferay/portal/kernel/model/LayoutConstants.java#L51) are now expected to send redirects, not forwards after [LPS-93973](https://issues.liferay.com/browse/LPS-93973) + [LPS-95208](https://issues.liferay.com/browse/LPS-95208)
- The proposed fix is to make sure redirects include query params.

With that in mind, it looks like the goal of your proposed fix is to make sure that redirects, sent from the FriendlyURLServlet, include query params.

**Suggested Next Steps**
If this is the case, I would suggest checking the following:
- Consider whether the query params should be included for both Permanent Redirects ([FriendlyURLServlet.java#L423-L425](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/internal/servlet/FriendlyURLServlet.java#L423-L425)) and Temporary Redirects ([FriendlyURLServlet.java#L436](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/internal/servlet/FriendlyURLServlet.java#L436))
  - If only one, how come?
- Consider whether **redirect.getPath() + "?" + queryString** may not work for certain circumstances
  - For instance, looking at this line here: [FriendlyURLServlet.java#L296-L297](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/internal/servlet/FriendlyURLServlet.java#L296-L297), it looks like this logic would introduce a parameter to **redirect.getPath()**. 
    - If that's really the case, the logic: **redirect.getPath() + "?" + queryString** would not work.
    - **Note:** I did not got a chance to test this scenario during my investigation
  - Here are a few additional resources that I found, may be helpful:
    - [docroot/index.jsp#L57-L64](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/portal-web/docroot/index.jsp#L57-L64)
    - [HttpImpl.java#L240-L271](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/portal-impl/src/com/liferay/portal/util/HttpImpl.java#L240-L271)

Please let me know your thoughts and if you have any questions.
Thanks!

**Comment by crodriguezy** [comment]
Hi @ericyanLr , thanks for your comments.

I think you are right about your findings (expected behaviour after LPS-93973 + LPS-95208) of performing redirects instead of forwards in specific cases.

The main goal of this PR, and again you are right, is to include the query params in those redirections. After studying your analysis I refactored a bit the PR:

- I included the query params in the [getRedirect()](https://github.com/liferay/liferay-portal/blob/8326a95fe0966a30a3e66b0df88eb24b5ff91790/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/internal/servlet/FriendlyURLServlet.java#L95) method, so all cases are covered (permanent and temporary redirects).

- I used the [HttpImpl.setParameter(...)](https://github.com/liferay/liferay-portal/blob/8326a95fe0966a30a3e66b0df88eb24b5ff91790/portal-impl/src/com/liferay/portal/util/HttpImpl.java#L1135) method, as you suggested, to add them to the **actualURL**, just like the _doAsUserId_ param is included. I tested the scenario (forced it while debugging, and it didn't work the way it's done directly with the '?' in the present one).

This is the new PR: please let me know any concern you may still have about it.

Thank you again.

**Pull request closed without merging**
