### PR TITLE
[TS] User notification about lockout is shown in the server's time zone which can be confusing for a user in a different time zone

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Dear @ericyanLr,

I have created a new fix based on your latest suggestions, in a new repository.
Local testing showed correct results.
Link to the LPS ticket:
[LPS-86512](https://issues.liferay.com/browse/LPS-86512)

If you approve this change, please forward it to the next approver,
Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test

**Comment by ericyanLr** [comment]
ci:test

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

From what I can tell, the failed tests do not appear to related to our fix.
I'm looking into who I showed forward this pr to and should be able to forward it sometime tomorrow.

Best,
Eric

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

Just wanted to let you know I'll be forwarding this pr to Shuyang tomorrow.

Best,
Eric

**Comment by ericyanLr** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/7222

**Pull request closed without merging**
