### PR TITLE
LPS-92701 Additional check for the portal domain is it may be different than the default virtual host name

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @ericyanLr 

I modified the solution.
The test failure reported in https://github.com/ericyanLr/liferay-portal/pull/116#issuecomment-484592409 does not occur.

Could you please check it?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hi @ericyanLr 

As I see, the test failures are not caused by the fix.

Best regards,
István

**Comment by ericyanLr** [comment]
Hi @IstvanD ,

From my understanding, the pattern / code snippet below was initially introduced to resolve issues for local development/testing installations (instances using the **localhost** address):
```
!StringUtil.equalsIgnoreCase(portalDomain, _LOCALHOST)
```

**Question:** Do you know if this issue only occurs if localhost is used?
My main concern is whether this fix is resolving the main issue or would it only resolve it for instances that use **localhost** for it's address.

References:
- https://issues.liferay.com/browse/LPS-1798
- https://issues.liferay.com/browse/LPS-10207
- https://issues.liferay.com/browse/LEP-6976

**Comment by IstvanD** [comment]
Hi @ericyanLr 

The issue doesn't occur when the instance has localhost (the default) set as it's virtual host.
It occurs however, when the instance has any other virtual host configured and a Site on this instance has yet another virtual host configured to it's (public or private) pages.

**Comment by ericyanLr** [comment]
Hi @IstvanD ,

## Analysis: Current Proposed Fix
After looking into this further, I don't think this is the right fix to resolve this issue.

```
if (group.isControlPanel() ||
    !StringUtil.equalsIgnoreCase(
        portalDomain, _LOCALHOST)) {

    virtualHostname = themeDisplay.getServerName();

    if (Validator.isNull(virtualHostname) ||
        StringUtil.equalsIgnoreCase(
            virtualHostname, _LOCALHOST)) {
        LayoutSet curLayoutSet =
            LayoutSetLocalServiceUtil.getLayoutSet(
                themeDisplay.getSiteGroupId(),
                privateLayoutSet);
        virtualHostname = curLayoutSet.getVirtualHostname();
    }
}
```

Original Condition: (If this group is Control Panel)
`group.isControlPanel()`

New Condition: (If this group is Control Panel OR if the domain is NOT localhost)
`group.isControlPanel() || !StringUtil.equalsIgnoreCase(portalDomain, _LOCALHOST)`

Currently, I do not understand the reasoning behind **why having a domain that is NOT localhost** should be allowed into that code block.

**Question:** Can you provide more insight regarding the reasoning behind this criteria?

## Analysis: Previous Proposed Fix
In my opinion, the previous proposed fix looks more reasonable.

Original Condition: (If this group is Control Panel)
`group.isControlPanel()`

New Condition: (If this group is Control Panel OR if we declared this as Control Panel)
`group.isControlPanel() || controlPanel)`

In my mind, it makes sense that we are entering this code block if we expect that this is for Control Panel.

**Testing Notes**
I also manually tested running the Integration Test: **PortalImplLayoutRelativeURLTest**

During my testing, the test did not fail. Also, it does not look like the test even touches the code changes.

So, it's possible that the test failure from your previous pr was a false positive.

**Question:** Was this the same for your testing as well?

## Suggested Next Steps
My suggestion would be to create a Test for the scenario you are fixing.

From my understanding, the scenario involves 3 elements:
- Custom Company Virtual Instance name
- Custom Site Virtual Instance Name
- Setting Scope to a Page

This would help:
- Provide additional insight behind the proposed changes
- Ensure that we are testing scenarios with changes to the elements above
- Ensure that we do not break this functionality in the future

Hope that helps.

Please let me know if you have any questions.
Thanks!

**Comment by IstvanD** [comment]
Hi @ericyanLr 

I couldn't run the test on my computer, and check if my previous solution broke the fix.
As I'm not familiar with the component, can I kindly ask you for a few guidelines how to construct the tests on the code level?

Thank you and best regards,
István

**Pull request closed without merging**
