### PR TITLE
LPS-134015 Update themeDisplay user when persistState is true in order to generate the proper language prefix afterwards

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
Hi @ericyanLr,

After doing some tests with the context from the customer it looks the changes from @dacousalr fixes the behavior described on the issue.

Could you review the PR?
Thanks in advance.

Regards,
Jorge

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @jgarcialr ,

I took a closer look at the portal.properties description and I feel there's still an uncertainty, specifically this line:

> Set this to 3 if the locale is automatically prepended to a URL when the requested locale is not the **default user** locale.

The uncertainty I'm referring to is **default user** locale vs **current user** locale. Can you help confirm whether setting `locale.prepend.friendly.url.style=3` applies to the actual default user or the current user?

**Additional Note**
There's also similar logic I noticed in PortalImpl.java that has related logic, such as:
https://github.com/liferay/liferay-portal/blob/7.4.1-ga2/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L3662-L3682

Can you verify if your changes should apply in those areas as well?

Please let me know your thoughts.
Thanks!

**Comment by jgarcialr** [comment]
Hello @ericyanLr,

In my previous test I detect that if current user locale is the same as the request locale, the locale is not added to the url.

I'll do some test to validate your second question, but I suspect this is covered with this part of the condition where the appendI18nPath is calculated. **_locale.equals(LocaleUtil.getDefault())_**
 
Regards.

**Comment by dacousalr** [comment]
Hi @ericyanLr,

> The uncertainty I'm referring to is default user locale vs current user locale. Can you help confirm whether setting locale.prepend.friendly.url.style=3 applies to the actual default user or the current user?

According to https://issues.liferay.com/browse/LPS-37809 and https://issues.liferay.com/browse/LPS-65302, and their respective commits, the answer to that question would be the current user locale. Otherwise, the behavior of value 3 would be almost identical to value 1.

What do you think?

**Comment by ericyanLr** [comment]
Hi @jgarcialr ,

**Regarding:**

> I'll do some test to validate your second question, but I suspect this is covered with this part of the condition where the appendI18nPath is calculated. **locale.equals(LocaleUtil.getDefault())**

The thoughts I had were basically:
- Should this existing logic also account for `locale.prepend.friendly.url.style=3`
- Is this existing logic and the logic you are working on duplicate code?

**Comment by ericyanLr** [comment]
Hi @dacousalr ,

**Regarding:**

> According to https://issues.liferay.com/browse/LPS-37809 and https://issues.liferay.com/browse/LPS-65302, and their respective commits, the answer to that question would be the current user locale. Otherwise, the behavior of value 3 would be almost identical to value 1.

Looking at LPS-37809, it looks like there was a portal.properties description change:
https://github.com/liferay/liferay-portal/commit/669dba67ae21a58f26b5ac4734eaee0fad2a7de9

In the past, the description says: **current user's preferred locale**. 
Currently, it's: **default user locale**.

But yes, I think you're right, looking at the two tickets the logic indicates the usage of the current user's locale. Do you think the portal properties description is somewhat misleading?

**Comment by jgarcialr** [comment]
Hello @ericyanLr,
Regarding your last thoughts:
    Should this existing logic also account for locale.prepend.friendly.url.style=3
    Is this existing logic and the logic you are working on duplicate code?
Yes, we should add the same logic for locale.prepend.friendly.url.style=3 in that part of the code. I discussed with @dacousalr  and we detect some difficulty in this case due to the fact that for checking properly the value 3 case, we need to know whether the user is logged in and, if so, their locale, but at this point (the method call comes from FriendlyURLServlet) we don't know if this info about the user is populated either in the request, the session or any ThreadLocal.
Reaching this point we would need your help or core infra help to find the best approach in how to obtain the user info without adding more overhead to the process.
We don't know if using initUser from portalImpl or getUser method inside this method or call those methods from friendlyURLServlet and change the method signature (this change implies a baseline change and prevents from backporting, and we have this problem reported under 7.3 so we need to be able to backport the change).
The other approach is re-implementing portalImpl.getLocalizedFriendlyURL partially by calling portalImpl.getGroupFriendlyURL method which would already contain the relevant logic about prepending or not the locale prefix. This way we could centralize all this logic in one place.
WDYT?

**Comment by ericyanLr** [comment]
Hi @jgarcialr ,

I'm not sure of the current status regarding this PR and related ticket. However, it sounds like there's much more to consider.

I'll be marking this PR as closed. 

If further discussions are needed, can you address it in a PTR ticket? It would be easier to communicate, have others involved, and to retain a history of the discussion.

Feel free to let me know if you have any questions.
Thanks.

**Pull request closed without merging**
