### PR TITLE
[TS] LPS-108120 CacheModels use ObjectOutput#writeUTF to cache String fields

### PR DESCRIPTION
**Pull request by NorbertKocsis**
https://issues.liferay.com/browse/LPS-108120

### CODE REVIEW

**Comment by NorbertKocsis** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @NorbertKocsis ,

I noticed that a part of your changed involved the removal of the following:
```
<#elseif stringUtil.equals(entityColumn.type, "String")>
```

Can you provide some insight as to why this change is needed?
Thanks!

**Comment by NorbertKocsis** [comment]
Hi,

As we use readObject for String we need to the trows declaration for ClassnotFoundException there too and this way it became a part of the "object and not Blob" category, so it is covered by the next elseif branch. So it is unnecessary to deal with it individually.

Br,
Norbert

**Comment by ericyanLr** [comment]
Thanks for the explanation, that makes sense.

Currently looking a bit more into **(String)objectInput.readObject()**, will most likely push it for further review on Monday.

**Comment by ericyanLr** [comment]
Hi @NorbertKocsis ,

Currently, we've been getting mixed results when running `ant build-services`, so I've been trying to sort that out, since this PR has a conflict.

For instance, your PR regenerated 174 files.
My PR regenerated 236 files.
Another TSE's PR regenerated 275 files.

I'm currently running a CI test here: https://github.com/ericyanLr/liferay-portal/pull/162

If there's no test complaints regarding the SB changes, I'll forward the changes to the next reviewer.

**Comment by NorbertKocsis** [comment]
Thanks! :)

**Comment by ericyanLr** [comment]
Hi @NorbertKocsis ,

After taking a closer look at your proposed fix, we think it would be best if we use readObject/writeObject **only for the specific columns** that may require it.

From the ticket description, it mentions: Web Content, a Wiki Page or a Blog Page. I'm assuming for these three entries, the main focus is the **content** field.

One thing that these three have in common are their SQL datatypes for the content field: CLOB.
- Web Content: [JournalArticleModelImpl.java#L91](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/model/impl/JournalArticleModelImpl.java#L91)
- Wiki Page: [WikiPageModelImpl.java#L89](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/modules/apps/wiki/wiki-service/src/main/java/com/liferay/wiki/model/impl/WikiPageModelImpl.java#L89)
- Blog Page: [BlogsEntryModelImpl.java#L89](https://github.com/liferay/liferay-portal/blob/7.3.0-ga1/modules/apps/blogs/blogs-service/src/main/java/com/liferay/blogs/model/impl/BlogsEntryModelImpl.java#L89)

**Proposed Change**
We'll only use readObject/writeObject for String types, who's column has a SQL datatype of Clob. The other String types can continue to use readUTF/writeUTF.

Link to branch with Proposed Changes: https://github.com/ericyanLr/liferay-portal/pull/169

**Verify Proposed Changes - Does it still resolve the original issue?**
Can you verify if this fix still resolves your issue with this new change?
Thanks!

----

**Additional Notes**
There has been issues with Service Builder yesterday, should now be resolved.

CI test is executing on the branch, to verify if the changes pass Service Builder tests.

**Comment by NorbertKocsis** [comment]
Hi Eric,

Yes, the fix is fine.

Thanks!
Norbert

**Comment by ericyanLr** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/8927

**Pull request closed without merging**
