### PR TITLE
LPS-132215 Slow loading of Users & Organizations page when user has permissions to manage users in a large organization

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-132215](https://issues.liferay.com/browse/LPS-132215).

@ericyanLr will you please test the scenario in the ticket with these changes? If it works then we can send it on as the official fix.

-------
edit: /cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
@pei-jung please see the commit message for an explanation.

@luanmaoski @brandizzi will you please confirm whether my summary in the commit message is accurate? Or rather, confirm whether post-filtering was enabled deliberately, or accidentally? It seems accidental, but I'd like your input before sending. Thanks!

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by ericyanLr** [comment]
Hey @drewbrokke ,

**Findings so far**
From my investigation so far, if we want to make this behavior change work as expected, I think we'll need to migrate our recent changes introduced by LPS-130651 (not sure if there are other existing use-cases as well). 

Basically, the changes from LPS-130651 relied on the usage of the SearchPermissionFilterContributor. However, since we are now suppressing post-permission filtering, this filter would no longer be applied/needed.

I'm thinking that means we'd have to apply these changes as pre-filters instead.

**Challenge**
Our current usage of UserSearchPermissionFilterContributor works by **including** users that are not made available.

However, if we were to use a Pre-Filter, I'm thinking the mechanism would be the opposite? Our pre-filter would have to **exclude** users that should not be made available.

Will continue to investigate some more.

**Comment by ericyanLr** [comment]
Forgot to include an example:

If we follow the steps to reproduce from [LPS-130651](https://issues.liferay.com/browse/LPS-130651)

- **Actual Result:** With this change, the AAA user can see ALL users.
- **Expected Result:** With this change, the AAA user continues to only see users that belong to the organizations they can manage.

**Comment by ericyanLr** [comment]
**Additional Findings**
It looks like the pre-filter already exists, this is how the filtering use to work in 62x to handle this org use-case:
- https://github.com/liferay/liferay-portal-ee/blob/ee-6.2.x/portal-web/docroot/html/portlet/users_admin/view_flat_users.jsp#L222-L226

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:accounts

**Comment by drewbrokke** [comment]
Just pushed the fix that re-enables pre-filtering when calling the search through UserLocalService. @ericyanLr will you please re-test the use-case with this updated code? Thanks!

**Comment by drewbrokke** [comment]
Just pushed a fix for the test failure in UserIndexerIndexedFieldsByAssociationTest.

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
@ericyanLr if this solution seems to work in all our known test cases, I think we're good to forward.

**Comment by ericyanLr** [comment]
Hi @drewbrokke ,

That's great news! And yes, the solution is working for the Organization use-cases we've been testing as well, looks good to me!

**Comment by drewbrokke** [comment]
ci:forward

**Comment by drewbrokke** [comment]
ci:forward

**Pull request closed without merging**
