### PR TITLE
[TS] LPS-183708 - missing language keys should default to language.properties rather than the default locale

### PR DESCRIPTION
**Pull request by wanderlast**
Previous PR: https://github.com/ericyanLr/liferay-portal/pull/308

Hi @ericyanLr!

I've made adjustments per your suggestions. 

A couple of changes:
1. Used a different key than "Liferay" since I realized that "Liferay" is something we don't actually localize so it'd be the same in basically all languages. 😅 I arbitrarily chose the word "Year" instead. 
2. Added some logic to change the default locale. This is since we want to make sure we're grabbing from language.properties instead of the default locale (which is the current behavior). If we keep the default locale as EN-US (which I'm assuming is the default on the test instances), we won't actually see any difference between default locale and language.properties. So we check the following:
- Pre-determined key against the default locale/language (in this case, fr).
- Key that should exist in unsupported locale to make sure we are grabbing from our registered bundle correctly.
- Key that shouldn't exist in unsupported locale to make sure we are using the blank bundle (or Language.properties) vs the default Locale.

Hopefully this works better now, but let me know if you see any other areas for improvement and I'll try to take a look. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @wanderlast ,

Provided feedback here: https://github.com/wanderlast/liferay-portal/pull/104

Feel free to let me know if you have any questions.

**Pull request closed without merging**
