### PR TITLE
[TS] LPS-129450 update org.eclipse.equinox.http.servlet with fix for Bug 562440

### PR DESCRIPTION
**Pull request by nikolettabuza**
Hi @ericyanLr,

this is the new PR for [LPS-129450](https://issues.liferay.com/browse/LPS-129450).

There are two commits to run the relevant tests successfully.

The changes include the fix for Bug 562440: https://github.com/eclipse/rt.equinox.bundles/commit/81083c1d65abe31c8c5ec8fe866ebee96980a84d

The `org.eclipse.equinox.http.servlet` library was generated from https://github.com/rotty3000/rt.equinox.bundles/commit/5a0a668bc0ae5bf879d799c6eaa443cbf0a83055 to include all necessary commits.

Thanks,
N

### CODE REVIEW

**Comment by nikolettabuza** [comment]
ci:test:sf

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
ci:test:relevant

**Comment by nikolettabuza** [comment]
Hi @ericyanLr,

I'm not sure why the tests fail here, I ran them twice from my PRs and all checks have passed.
* https://github.com/nikolettabuza/liferay-portal/pull/5#issuecomment-855094828
* https://github.com/nikolettabuza/liferay-portal/pull/6#issuecomment-859039794

**Comment by ericyanLr** [comment]
Hi @nikolettabuza ,

Thanks for all your hard work on this and clear notes in the PR and tickets. 

From what I can tell, the failing tests look unrelated to your changes.
Forwarding this to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/10072

**Pull request closed without merging**
