### PR TITLE
LPS-99654

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-99654](https://issues.liferay.com/browse/LPS-99654)

Hi Eric,

This is the continuation of https://github.com/ericyanLr/liferay-portal-ee/pull/42. 

Considering the possibility to use DynamicResourceServlet more universally than the out-of-the box way, I am sending the fix to master, as you suggested. Many thanks for the help you gave me!

Please let me know if any further concerns come up.

Thank you,
Istvan

### CODE REVIEW

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
Updated to handle the SF problem.

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
The functional test failure looks unrelated to my changes. @ericyanLr , please let me know if you think differently.

Thanks.

**Comment by ericyanLr** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/8311

**Pull request closed without merging**
