### PR TITLE
Lps 162885

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-162885

The issue here is that it is possible to enable publications on remote live sites.
To fix the issue, I updated the query that retrieves the staged groups to account for remote live sites. I also updated the if statement to include the hasRemoteStagingGroup() method.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
Hey @noornajj ,

Can you provide some context for the change:
- Before: `GroupTable.INSTANCE.typeSettings.like("%staged=true%")`
- After: `GroupTable.INSTANCE.typeSettings.like("%staged%")`

**Comment by noornajj** [comment]
Sorry @ericyanLr ,
That is an unintentional change that I did while testing. I will fix and force push the changes.

**Comment by ericyanLr** [comment]
Reviewed and sent to Publications Team for further review: https://github.com/liferay-publications/liferay-portal/pull/266

**Pull request closed without merging**
