### PR TITLE
LPS-116548 Follow-up to LPS-89210. Make the check stricter.

### PR DESCRIPTION
**Pull request by brianikim**
Sending to you as per MCD as this is a core issue at heart, even though the issue stems from staging.

https://issues.liferay.com/browse/LPS-116548

The way the behavior occurs in LPS-116548:

1. [doProcessAction](https://github.com/liferay/liferay-portal/blob/89b619a60717e2f19a5948dd973b40d08957e8af/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/portlet/action/MoveLayoutMVCActionCommand.java#L73) is called in MoveLayoutMVCActionCommand.
2. Above method in Step 1 eventually calls [updateParentLayoutIdAndPriority](https://github.com/liferay/liferay-portal/blob/89b619a60717e2f19a5948dd973b40d08957e8af/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L3214) in LayoutLocalServiceImpl.
3. Above method in Step 2 calls [updateParentLayoutId](https://github.com/liferay/liferay-portal/blob/89b619a60717e2f19a5948dd973b40d08957e8af/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L3101) which ultimately calls [updateLayout](https://github.com/liferay/liferay-portal/blob/89b619a60717e2f19a5948dd973b40d08957e8af/portal-kernel/src/com/liferay/portal/kernel/service/LayoutLocalServiceWrapper.java#L1738) using the wrapper in LayoutLocalServiceWrapper.
4. Because staging + page versioning is involved, the updated layout is wrapped before it's returned in [wrapLayout](https://github.com/liferay/liferay-portal/blob/89b619a60717e2f19a5948dd973b40d08957e8af/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceStagingAdvice.java#L552) in LayoutLocalServiceStagingAdvice.
5. Again, because staging + page versioning is involved, above method in Step 4 ultimately calls [getProxiedLayout](https://github.com/liferay/liferay-portal/blob/89b619a60717e2f19a5948dd973b40d08957e8af/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceStagingAdvice.java#L488).
6. In getProxiedLayout, we have the following code check:
```
if (layout.getMvccVersion() ==
		cachedProxiedLayout.getMvccVersion()) {

	return cachedProxiedLayout;
```

This is the reason the behavior in LPS-116548 occurs incorrectly. Layout, in this case, is correct, and identifies itself as a child page after the drag is finished. 

However, because above check completes (MvccVersion is the same), the cachedProxiedLayout (which is the layout prior to the drag initiated) is returned.

The solution for this issue is to ensure we do a stricter check by comparing all the modelAttributes of the layout and cachedProxiedLayout to ensure they are actually equal to each other.

**Important information**:
The solution was implemented under the assumption that the MvccVersion is not actually incremented until the transaction is fully complete. In the above situation, I originally expected the layout to have an incremented MvccVersion as it was updated in the persistence. Because this was not the case, I concluded that the MvccVersion is most likely incremented after the transaction is fully complete (in that the calls to the update should be completed as well before MvccVersion is increased).

Now, if my above understanding is incorrect and that the correct behavior of MvccVersion increment should be that it should be increased as soon as the persistence is updated, we might have to potentially implement a different solution by making sure the MvccVersion is incremented when the persistence is updated.

Please confirm whether my understanding of when MvccVersion is incremented is correct or incorrect.

Please let me know if you have any questions. Thanks.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @brianikim ,

I didn't have time to take a look at this PR yet, should have some time tomorrow.

**Comment by ericyanLr** [comment]
Hi @brianikim ,

From my investigation, I think the issue may actually have to do more with the implementation of the API. 

For this scenario, we can focus on this API call: [updateParentLayoutIdAndPriority](https://github.com/liferay/liferay-portal/blob/7.3.3-ga4/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L3213-L3227)
- I noticed that for this API call, it relies on making calls with **layoutLocalService**

If we take a peek at one of the method it calls: [updateParentLayoutId](https://github.com/liferay/liferay-portal/blob/7.3.3-ga4/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L3100-L3140), we can see that it eventually calls [layoutLocalService.updateLayout(layout);](https://github.com/liferay/liferay-portal/blob/7.3.3-ga4/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L3139)

**Thoughts**
Based on my investigation so far, I think the **getProxiedLayout** logic w/ **getMvccVersion** seems reasonable. I haven't dove deeper, but you may be correct in that there may actually be a limitation w/ the current implementation.

But, from what I can tell so far, I think the behavior can be seen as expected behavior, based on the service calls being made and the transaction boundaries set for those service calls.

With that in mind, I think it's worth looking into whether improving the **updateParentLayoutIdAndPriority** API may be a better approach.

**Possible Alternative Fix?**
I'm not sure if you've already explored this route.

But, during my testing, changing the line [layoutLocalService.updateLayout(layout);](https://github.com/liferay/liferay-portal/blob/7.3.3-ga4/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L3139) to **layoutPersistence.update(layout)** no longer reproduced the issue. 

I'm not sure if this is the proper fix, but I think it would be worth looking into. 

Please let me know your thoughts.
Hope that helps!

**Comment by brianikim** [comment]
Hey @ericyanLr ,

Thank you for your analysis. I am currently testing your suggestions. I will close this ticket for now as I do the investigation.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
Hey Eric,

reopening the ticket after investigation.

> With that in mind, I think it's worth looking into whether improving the updateParentLayoutIdAndPriority API may be a better approach.

I am not sure whether updateParentLayoutIdAndPriority is the correct place to approach this because getProxiedLayout will be called regardless and do the MvccVersion check which will always be unsuccessful as the MvccVersion are the same even though the updatedLayout should have an incremented MvccVersion.

Your alternative fix:


> But, during my testing, changing the line layoutLocalService.updateLayout(layout); to layoutPersistence.update(layout) no longer reproduced the issue.

I tested with the above change. The issue is still reproducible. It makes sense that the issue is reproducible because layoutLocalService.updateLayout(layout) directly leads to layoutPersistence.update(layout) anyways.

I think an answer is required for the following as it will ultimately determine whether an alternative approach should be pursued or the current solution should be pushed.

> Important information:
> The solution was implemented under the assumption that the MvccVersion is not actually incremented until the transaction is fully complete. In the above situation, I originally expected the layout to have an incremented MvccVersion as it was updated in the persistence. Because this was not the case, I concluded that the MvccVersion is most likely incremented after the transaction is fully complete (in that the calls to the update should be completed as well before MvccVersion is increased).
> 
> Now, if my above understanding is incorrect and that the correct behavior of MvccVersion increment should be that it should be increased as soon as the persistence is updated, we might have to potentially implement a different solution by making sure the MvccVersion is incremented when the persistence is updated.
> 
> Please confirm whether my understanding of when MvccVersion is incremented is correct or incorrect.


Please let me know if you have any questions. Thanks.


Sincerely,
Brian Kim

**Pull request closed without merging**
