### PR TITLE
[TS] LPS-126209 Avoid adding the same bodyContentString multiple times

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Eric,

could you please check my fix and push it forward?

Thanks, Roland

https://issues.liferay.com/browse/LPS-126209

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @rolandpakai ,

I took a quick glance at your code changes and I don't think this is the proper fix for the bug you are trying to fix. 

The OutputTag is a taglib and the code looks quite broad, and so adding this type of logic to avoid included matching data, does not look correct.

Again, I'm not familiar with your actual bug, but I would say this type of logic would be better handled handled on the Fragment side (since I'm assuming this is where the taglib is being utilized for your bug). 

If I'm misunderstanding the situation and there really is a bug in the OutputTag, can you provide additional information on the actual issue? If not, I would suggest exploring more on the Fragment side.

Please let me know your thoughts and if you have any questions.
Thanks!

**Comment by rolandpakai** [comment]
Hi @ericyanLr
 
i talked with @ealonso and we will try to solve the issue on the Fragment side.

Thanks, Roland

**Pull request closed without merging**
