### PR TITLE
Lps 106586

### PR DESCRIPTION
**Pull request by mtambara**

### CODE REVIEW

**Comment by mtambara** [comment]
ci:test:sf

**Comment by mtambara** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @mtambara ,

I tested the changes and can confirm it resolves the issue for LPS-106586.

I also took a look at the related LPP tickets and can confirm this fix should resolve those issues as well.

**Comment by mtambara** [comment]
See https://github.com/shuyangzhou/liferay-portal/pull/9103

**Pull request closed without merging**
