### PR TITLE
[TS] LPS-122070 PortalImpl.getPlidFromPortletId returns 0 for runtime portlets that are nested in web content article templates

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi @ericyanLr,

Please review my fix, and if you approve this change, please forward it to the next approver,
- Please read the related LPP ticket in case you have questions or need more context
- There may be use cases, other than the customer reported, however we only want to focus on this specific use case.
I have tested this fix against LPS-97073 and LPS-74443 to ensure that my change won't mess up anything else.

Thank you for reviewing my fix,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

**Analysis**
From a quick glance, this doesn't look like the proper fix or at least including it as multiple commits + explanation would be helpful to understand the proposed change.

Looking at the code, it looks like this is the pattern being used in the method:
```
List<Layout> layouts = LayoutLocalServiceUtil.getLayouts(
    groupId, privateLayout, LayoutConstants.TYPE_PORTLET);

long plid = getPlidFromPortletId(layouts, portletId, scopeGroupId);

if (plid != LayoutConstants.DEFAULT_PLID) {
    return plid;
}
```

This pattern is used to reference multiple types of layouts, which we can see is also referenced in **Site Builder > Pages > [+] > Public Page**:
- Widget Page (LayoutConstants.TYPE_PORTLET)
- Full Page Application (LayoutConstants.TYPE_FULL_PAGE_APPLICATION)
- Panel (LayoutConstants.TYPE_PANEL)

With that in mind, your suggested change appears to:
- Replace the logic associated for **LayoutConstants.TYPE_PORTLET (Widget Page)** with **LayoutConstants.TYPE_CONTENT (Blank)**
- Introduce an additional condition: **!layoutTypePortlet.hasDefaultScopePortletId(groupId, portletId)**, to the shared method: **getPlidFromPortletId**, which is deviating from the pattern

**Thoughts**
With that in mind, from a quick glance, this does not look like the proper fix. 

Though I may be wrong, since I haven't had a chance to dive deeper into the reasoning behind the logic in this proposed fix. But, it would be helpful if you provided an explanation as to why this replacement + pattern break is necessary to resolve this issue.

Also, these changes may actually be more related to WEM. If you feel the WEM team may have a better understanding of the changes being made, feel free to ask the team to review the changes instead.

The WEM team should actually be able help more this particular type of change.

Feel free to let me know if you have any questions.
Hope that helps.

**Comment by peterpetrekanics** [comment]
Dear @ericyanLr,

First, a customer reported, that the PortalUtil.getPlidFromPortletId call's behavior has changed, between DXP 7.0 FP 91 and 92. Their issue can be read in the related LPP in more detail.
Anyway, they requested that we restore the original behavior since this change was not described in the breaking changes section of FP 92 and therefore would be a bug.
There were multiple changes made to that code part in the portal, like:  LPS-74443 and LPS-101469.
My goal was to restore the original behavior of that call, while also not breaking other recent fixes, like the one for the full page applications (LPS-74443).
So first I reviewed what was changed with LPS-74443 on 7.0, I found that for example the doGetPlidFromPortletId method was removed:
https://github.com/liferay/liferay-portal-ee/commit/9dda4fd799e3afd2c90f5f44035e5ea5d090873d
then the logic was changed here to add support for full page applications:
https://github.com/liferay/liferay-portal-ee/commit/347de4306e96e905c439e738c4b184286698ced6

In my own fix I was trying to bring back some of the logic from the aforementioned comment: the one that removed doGetPlidFromPortletId,
while I also found during testing that I should use LayoutConstants.TYPE_CONTENT instead of LayoutConstants.TYPE_PORTLET if I want to loop through non-hidden pages.
I am not sure if I can explain this any better than this, but of course if you have further questions feel free to contact me any time,
Wish you a nice weekend!!!
Peter

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

**Regarding:**

> In my own fix I was trying to bring back some of the logic from the aforementioned comment: the one that removed doGetPlidFromPortletId,

From my understanding, the method wasn't removed, but was just switched from protected to private. If I'm misunderstanding this or missing something, please let me know.

**Regarding:**

> while I also found during testing that I should use LayoutConstants.TYPE_CONTENT instead of LayoutConstants.TYPE_PORTLET if I want to loop through non-hidden pages.

I understand that this may be a valid potential fix. However, this illustrates what I was trying to mention in my previous comment.

Again, my understanding of your single commit is to:
- Replace the logic associated for **LayoutConstants.TYPE_PORTLET (Widget Page)** with **LayoutConstants.TYPE_CONTENT (Blank)**
- Introduce an additional condition: **!layoutTypePortlet.hasDefaultScopePortletId(groupId, portletId)**, to the shared method: **getPlidFromPortletId**, which is deviating from the pattern

My suggestion would be to not combine this entire change into a single commit, as it doesn't provide much of an explanation for each of the 2 changes.

----

**Additional Thoughts - Replacing Logic for TYPE_PORTLET with TYPE_CONTENT**
It's still unclear to me, why we need to replace **LayoutConstants.TYPE_PORTLET** with **LayoutConstants.TYPE_CONTENT**. 

I understand that during your testing, everything is working as you expected. But, a few questions come up when I see this replacement:

- Does this break anything for Widget Pages?
- Why did we replace the logic Widget pages with Content Pages?
- Why did we not add new logic for Content Pages instead of replacing the logic for Widget pages?

Again, these are just questions I would think about in my head while reviewing. From what I can tell, the ticket descriptions + commit messages do not provide answers to these questions. 

I would need to investigate deeper to try to understand whether this type of change would break functionality and whether this change makes sense.

Which is why I suggested reaching out to the WEM team, since they would probably have a better understanding of how different page types and the associated portlet ids work.

**Additional Thoughts - Deviating from the pattern**
With your explanation, I now understand that you added this change to loop through hidden pages. And yes, if this were mentioned in a commit message, that would have been helpful.

A few questions that come up for me would be:
- How come we do not need to loop through hidden pages for Widget pages?
- Do Content pages have hidden pages? Do Widget pages have hidden pages? Do Full Page application pages have hidden pages? etc.
- Would it be better to introduce this change to the already existing method: _getPlidFromPortletId?
    - If so, does that break things?
    - If not, should this logic instead be contained within a separate method?
      - Would it be better to prepare a similar method to _getPlidFromPortletId, maybe with an additional parameter, instead of in-lining the logic and making a small tweak? 
      - Would this help make things more clear for future reviewers?

These are just questions I would ask my self when reviewing this change. And again, I think the WEM team would probably have answers to all these types of questions that I would be asking myself.

**Additional Thoughts**
Hopefully this helps provide more context as to what I was suggesting in my previous response. And just wanted to clarify this again, I'm not saying that your fix is wrong, the logic may completely be correct. 

I'm just saying that from my observation, the commits could potentially be: 
- Improved to provide a clearer picture for the reader/reviewer as to why you are introducing these changes
- And that maybe the logic that breaks the pattern, could be refactored to avoid introducing new complexity, which would be helpful for readers/reviewers who need to add more changes in the future.

Hope that helps clear things up.

If there's anything else I could help with, feel free to let me know! 
Otherwise, I think the WEM team would be much more helpful in reviewing this fix.

Best,
Eric

**Pull request closed without merging**
