### PR TITLE
LPS-134094

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-134094

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:stop

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Reviewed and sent to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/10140

**Pull request closed without merging**
