### PR TITLE
[TECHNICAL SUPPORT] LPS-115406 Advanced search on Audit portlet displays wrong end date

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-115406](https://issues.liferay.com/browse/LPS-115406),

As we discussed in [PTR-1781](https://issues.liferay.com/browse/PTR-1781) I send these changes to master as well, as it resolves the duplicate IDs there as well and eventually resolve the wrong date issue on 7.0

Please review it

Thanks,

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @NemethNorbert ,

Sorry for the delay, I will take a look at this on Monday.

**Comment by ericyanLr** [comment]
**Quick Update**
The approach looks okay to me. Will be double checking if we want to use this LPS ticket or a separate ticket, since the steps to reproduce do not apply for master.

Will provide an update tomorrow.

**Comment by ericyanLr** [comment]
Hi @NemethNorbert ,

**Possible Issue: Duplicate element ids + names**
To start, I think a couple of the names you selected: **startDateDay** and **endDateDay** would be problematic, as they are already used by hidden input fields.

For example, if you navigate to the Audit Portlet page and inspect the html elements, you'll notice that these ids + names are already used:
- _com_liferay_portal_security_audit_web_portlet_AuditPortlet_endDateDay
- _com_liferay_portal_security_audit_web_portlet_AuditPortlet_startDateDay

If you were to use those names, I believe it would result in more duplicate elements. (Can you verify if this would be the case?)

**PR - Proposed next steps for master**
Since LPS-115406 cannot be reproduced in master, let's instead create a new ticket to address this issue with a different angle.

From my understanding, the current scenario involves duplicate element ids + names, specifically:
- \_com_liferay_portal_security_audit_web_portlet_AuditPortlet\_

To me, this duplicate element ids + names can be considered a bug.

Approaching this issue with this angle should allow us to:
- Easily reproduce this issue on both master and older versions
- Allow QA to test for the fix
- Would also fix our issue for LPS-115406

Please let me know your thoughts and if you have any questions.
Thanks!

**Comment by NemethNorbert** [comment]
Hey @ericyanLr,

You were absolutely right, I just ended up duplicating the id's again. I force pushed a new solution where this issue won't happen.
I also agree it would be a lot easier to administer the ticket, if we solely focus on the id problem. So I went ahead and reworded LPS-115406 so it applies to all of our versions and easy to test and verify.

Let me know what do you think about the new names and the new ticket description.

Thanks,

**Comment by ericyanLr** [comment]
Hi @NemethNorbert ,

**Regarding:**
> So I went ahead and reworded LPS-115406 so it applies to all of our versions and easy to test and verify.

For me, I would've preferred that LPS-115406 remained the same, since it documented an actual bug that a user may encounter:
- In Audit advanced search, the end date switches back incorrectly to the start date after the search. This gives the false impression as if the filtered results were from that single day. 

However, re-wording it would make the original description no longer searchable in Jira and so if anyone else ever experiences this issue, they would have to eventually deduce that it was resolved by this "duplicate ids" issue.

Creating a new ticket however, would make it so the original issue would still be easily tracked / searchable on Jira and if we link the tickets, it would also make it easy to see that the new ticket resolves the issue.

**Next Steps**
If you would like to proceed with using this re-worded ticket, please let me know. Otherwise, feel free to create a new ticket if you would like to go that route instead.

Please let me know how you would like to proceed.
Thanks.

**Comment by NemethNorbert** [comment]
Hey @ericyanLr,

I would like to go ahead with this ticket. Simply the other issue is only reproducible on 7.0.x, so it's easier to create a new ticket for the 7.0.x issue and simply connect the two ticket  once we backported this solution to 7.0.x

I will take care of the administration.

thanks,

**Comment by NemethNorbert** [comment]
Hey @ericyanLr,

Can we move forward with this solution? I already created https://issues.liferay.com/browse/LPS-131164 for the 7.0.x specific issue, I will close it once I back ported this solution to 7.0.x with a fixed by relation.

**Comment by ericyanLr** [comment]
Hey @NemethNorbert ,

Apologies, Friday was a busy day. 
I have reviewed and sent to AppSec team for further review: https://github.com/liferay-appsec/liferay-portal/pull/344

**Pull request closed without merging**
