### PR TITLE
LPS-112226 Avoid NPE in the toCacheModel, when using primitive wrapper types

### PR DESCRIPTION
**Pull request by hudakl**
Hi Eric,

Could you please review my solution suggestion for LPS-112226.

Please note, that I handled exception in the model_impl.ftl, rather than using the wrapper types in the model_cache.ftl, due to the commits and their messages of LPS-62652.

Thanks,
Laci

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @hudakl ,

I didn't fully look into your implementation, but I wanted to start with a few thoughts regarding:
- isPrimitiveWrapper
- Implementation change?

**isPrimitiveWrapper** 
Is the method you're trying to create the same as this method: [EntityColumn.java#L401-L440](https://github.com/liferay/liferay-portal/blob/7.3.1-ga2/modules/util/portal-tools-service-builder/src/main/java/com/liferay/portal/tools/service/builder/EntityColumn.java#L401-L440)?

If that's the case, you should be able to use that method instead of creating one.

**Implementation change?**
I didn't fully look into analyzing your changes, but I did find a reference of another ftl file, that had similar logic. 

Just wanted to link it, since it utlized the mentioned column method above. 

Maybe it'll be helpful with your implementation as well: [persistence_impl_finder_find.ftl#L2298-L2312](https://github.com/liferay/liferay-portal/blob/7.3.1-ga2/modules/util/portal-tools-service-builder/src/main/resources/com/liferay/portal/tools/service/builder/dependencies/persistence_impl_finder_find.ftl#L2298-L2312)

----
If it's not related, can you provide additional context as to the difference in your change?

If it's similar and the method/examples apply to your use-case, can you update your code to use the existing method and evaluate whether you should tweak your implementation as well?

Feel free to look for other use-cases in the code, I just randomly chose those code samples for references.

Hope that helps!

Best,
Eric

**Comment by hudakl** [comment]
The use case you mentioned is not applicable here. It utilizes isPrimitiveType, but for this issue we specifically need the check for primitive wrapper types.

Most of the context is written in the LPS description. Using a primitive wrapper in the service.xml, leads to an NPE upon adding a new entity, because in the CacheModel, the primitive wrappers types are changed to primitive types.

I originally thought of using primitive wrappers in the CacheModel, but the commit messages of LPS-62652 showed that was intentional. So, I handled the NPE, where it occurred.

I looked for similar use cases, but I couldn't find any. Apparently we don't use primitive wrapper types in the service.xml-s.

**Comment by ericyanLr** [comment]
Hi @hudakl ,

**Regarding:**

> The use case you mentioned is not applicable here. It utilizes isPrimitiveType, but for this issue we specifically need the check for primitive wrapper types.

I think my confusion here is:

- what is a primitive wrapper type?
  - e.g. is your new method: isPrimitiveWrapper defining what a primitive wrapper is?
- and when you say **isPrimitiveType** is not applicable here, can you provide more context?
  - e.g. is the logic here different than the logic you need to indicate a primitive wrapper type?

Can you help elaborate on those points?
Thanks!

**Comment by hudakl** [comment]
Hi,

Most simply put, this describes the primitive wrappers:
https://en.wikipedia.org/wiki/Primitive_wrapper_class_in_Java

And these primitive wrappers in the service.xml causing the problem described in the LPS.

Hopefully, this fills the gap in the context.

Regards,
Laci

**Comment by ericyanLr** [comment]
Hi @hudakl ,

Thanks for the additional info, I think I understand what you're trying to handle and implement with this fix.

I have created a branch with some additional commits:
- Branch: https://github.com/ericyanLr/liferay-portal/tree/pr-178_hudakl_LPS-112226
- Compare: https://github.com/ericyanLr/liferay-portal/compare/master...ericyanLr:pr-178_hudakl_LPS-112226

Can you verify/test if this accomplishes what you need and share your thoughts or any concerns you may have with the new additions?

I'll also leave some additional notes for testing below, in case it's helpful.

Best,
Eric

----

**Additional Notes - Testing**
To test with my local portal-tools-service-builder, I followed this Grow article: [Making changes to service builder](https://grow.liferay.com/people/Making+changes+to+service+builder
)

1\. Create a snapshot of your local portal-tools-service-builder module ([Deploy Your Changes To Maven Local](https://grow.liferay.com/people/Making+changes+to+service+builder#deploy-your-changes-to-maven-local
))
- Modify the bnd.bnd file to change the version to a TIMESTAMP for testing
  - e.g. `Bundle-Version: 1.0.343-20200507162129`
- Add my local portal-tools-service-builder to my local maven cache
  - By running: `gradlew install`

2\. Use your snapshot portal-tools-service-builder-module in your test service module ([Validate Your Changes - Gradle](https://grow.liferay.com/people/Making+changes+to+service+builder#validate-your-changes---gradle)
- Add your local maven cache as an available repository by adding the following in build.gradle:
```
repositories {
    mavenLocal()
}
```
- Specify the specific service builder module to use when building your test service by adding the following in build.gradle: 
```
dependencies {
    // ...

    serviceBuilder group: "com.liferay", name: "com.liferay.portal.tools.service.builder", version: "1.0.343-20200507162129"
}
```
- Example build.gradle with changes:
```
buildService {
	apiDir = "../service-builder-npe-api/src/main/java"
}
dependencies {
	compileOnly group: "com.liferay", name: "com.liferay.petra.io", version: "3.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.lang", version: "3.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.petra.string", version: "3.0.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.aop.api", version: "1.0.0"
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "default"
	compileOnly group: "org.osgi", name: "org.osgi.annotation.versioning", version: "1.1.0"
	compileOnly group: "org.osgi", name: "org.osgi.core", version: "6.0.0"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations", version: "1.3.0"
	compileOnly project(":apps:service-builder-npe:service-builder-npe-api")
	compileOnly project(":core:petra:petra-sql-dsl-api")

	serviceBuilder group: "com.liferay", name: "com.liferay.portal.tools.service.builder", version: "1.0.343-20200507162129"
}

repositories {
	mavenLocal()
}
```

**Comment by hudakl** [comment]
Hi Eric,

Your changes seem valid, and based on my tests they work correctly.

Thanks,
Laci

**Comment by ericyanLr** [comment]
Hi @hudakl ,

Great! I have forwarded the PR to Shuyang for further review: 
https://github.com/shuyangzhou/liferay-portal/pull/9051

**Pull request closed without merging**
