### PR TITLE
LPS-174388 Clear user data when switching to Asset Creator

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-174388

The issue here is Recipient Type doesn't get updated when switching from "User" to "Asset Creator"
The reason is that "Asset Creator" is saved as assignmentType = 'user'; same as "User". When the recipient type is changed from "User" to "Asset Creator" the "emailAddress" property doesn't get cleared from the assignments object. Therefore, assignmentType = 'user' is assumed to be "User" instead of "Asset Creator"

To fix the issue, I had the user data cleared when the recipient type is "Asset Creator".

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

**Regarding:**
> The reason is that "Asset Creator" is saved as assignmentType = 'user'; same as "User". When the recipient type is changed from "User" to "Asset Creator" the "emailAddress" property doesn't get cleared from the assignments object.

I took a look at the code and I'm assuming this is due to: [notifications/utils.js#L18](https://github.com/liferay/liferay-portal/blob/7.4.3.62-ga62/modules/dxp/apps/portal-workflow/portal-workflow-kaleo-designer-web/src/main/resources/META-INF/resources/designer/js/definition-builder/diagram-builder/components/sidebar/sections/notifications/utils.js#L18)

If that's the case, 

**Question**
If only the "emailAddress" property needs to be cleared, is there a reason for clearing the sectionsData as well?
- If it's more for general cleanup purposes, then should it also apply for other use-cases as well, not just when (recipientType === 'assetCreator')?
- Or if this needed for this particular scenario, can you help elaborate the reason?
- Or is it not necessary to remove this?

**Comment by noornajj** [comment]
Hi @ericyanLr 

Clearing the sectionsData was just for general cleanup. The reason I only did it when (recipientType === 'assetCreator') is because that is the only instance it causes an issue. 

I tested changing the recipient type from "User" to "Task Assignee" then to "Asset Creator" and the issue does not occur. So it seems those fields get wiped when changing to a different assignment type but since "User" and "Asset Creator" are both user types then the email and data fields don't get removed.

**Comment by ericyanLr** [comment]
Hi @noornajj ,

**Regarding:**
> I tested changing the recipient type from "User" to "Task Assignee" then to "Asset Creator" and the issue does not occur. So it seems those fields get wiped when changing to a different assignment type but since "User" and "Asset Creator" are both user types then the email and data fields don't get removed.

I'm guessing you meant 'Recipient Type'. And if that is the case, one scenario to test is using the **Role** recipient type, since it utilizes the sectionsData. 

For example:
1. Switch recipient type to: **Role**
2. Select a Role (e.g. Account Manager)
    - Notice: the Role Name and Role Id is populated
3. Switch to recipient type: **Task Assignee** 
4. Switch back to recipient type: **Role**
    - Notice: the Role Name and Role Id is still populated
5. Switch to recipient type: **Asset Creator**
6. Switch back to recipient type: **Role**
    - Notice: that with your change, the Role Name and Role id is no longer populated
    - Notice: that without your change, the Role Name and Role id is still populated

This is a behavior change that I noticed would be introduced, with the new logic to delete the sectionsData.

**Regarding:**
> Clearing the sectionsData was just for general cleanup. The reason I only did it when (recipientType === 'assetCreator') is because that is the only instance it causes an issue.

If resolving the issue actually requires removing the sectionsData, can you help elaborate more on this?

With that in mind, if we do decide that our fix requires removing the sectionsData to resolve the issue or we decide to add this logic to provide some general cleanup, I think our change should provide an overall consistent behavior when switching between the different recipient types.

Please let me know what you think.
Thanks!

**Comment by noornajj** [comment]
Hi @ericyanLr 

Clearing the sectionsData is not needed for this fix to work. Therefore, I have removed it and only have the email deleted so that the behavior stays consistent.

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Sounds good! Reviewed and sent to Workflow team for further review:
https://github.com/liferay-workflow/liferay-portal/pull/890

**Pull request closed without merging**
