### PR TITLE
Lps 141727

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-141727

The issue here is that a user's additional information in Members portlet is not visible in Firefox due to css issue with float.
It was caused by a conflict of the css class name field-group with the file aui_deprecated.css. The issue was fixed by changing the class name to lfr-field-group.

This issue is no longer reproducible in Master because aui_deprecated.css has been removed. However, we are committing these changes to master to insure consistency between Master and 7.3.x

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
Reviewed and sent to Frontend Team for further review: https://github.com/liferay-frontend/liferay-portal/pull/1683

**Pull request closed without merging**
