### PR TITLE
LPS-158932 Allow for userID to be passed correctly when using Experiences with Workflow

### PR DESCRIPTION
**Pull request by noornajj**
Comments from @jakesliwka 
Test results [here](https://github.com/noornajj/liferay-portal/pull/16)

> https://issues.liferay.com/browse/LPP-45997
> 
> While having workflow enabled and creating a new page with multiple experiences, once approved, the pages would appear as blank.
> This was because only when workflow was enabled, and updateLayoutPageTemplateStructureData was called, a user ID of 0 was passed passed in to the _layoutPageTemplateStructureRelLocalService.addLayoutPageTemplateStructureRel method which threw an error saying that there cannot be a userId of 0. This caused the experiences to not display their changes made, despite being 'approved'. When tested with workflow disabled, the correct userID gets passed each time.
> The userID was being retrieved with PrincipalThreadLocal.getUserId() . The solution was to go back to when we had a valid userID and pass it along to make sure that a correct one is used and set it back afterwards, as well as ensure that it is not used anywhere else during the process.
> We found that before updateLayoutPageTemplateStructureData is called, targetLayout.getUserId() is used earlier in the same method to retrieve the current userID.
> Since PrincipalThreadLocal is used later on and causes the error, we set the userID in PrincipalThreadLocal to the targetLayout.getUserId() and wrap the original call to updateLayoutPageTemplateStructureData in a try/finally to quickly set, use, and reset the userId back to what it was.
> We found that the only other place that this userId is used during this execution is within Publications.
> The worry was that if workflow and publications were to be eventually integrated, this issue could potentially pass the wrong userId.
> This [PTR](https://issues.liferay.com/browse/PTR-3253) confirmed that since workflow does not work with publications, this fix can proceed safely.

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @noornajj @jakesliwka ,

**Thoughts**
I think this is a reasonable fix, but I'm trying to determine whether there could be a better place to implement this.

With the current approach, we rely on making sure the **PrincipalThreadLocal** is set, every time we call **updateLayoutPageTemplateStructureData**. 

But, if we take a look at **LayoutCopyHelperImpl**, we can see that it actually calls this in two places. 
- And so, for our proposed fix, a question would be whether we should apply this to both places.

**Alternative Option**
Since this fix is to account for Workflow, an option to explore would be whether we can create a fix that only applies for Workflow.

I did some debugging and it looks like the method is called here when approving the workflow:
- [LayoutWorkflowHandler.java#L109-L114](https://github.com/liferay/liferay-portal/blob/7.4.3.36-ga36/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/workflow/LayoutWorkflowHandler.java#L109-L114)

If the fix is applied here, it would only be utilized when using Workflow.

Can you see if it makes sense to apply the fix here? If not, we can proceed with the current approach.

**Comment by jakesliwka** [comment]
Hello @ericyanLr ,

Thank you for looking in to this!
Here After investigating, this is what I found. Feel free to ask for more clarification or let me know if I missed anything.

In **LayoutCopyHelperImpl**, I looked at where else **updateLayoutPageTemplateStructureData** was used to see if we should also apply the fix there.
It gets called in a separate method, **_copyLayoutPageTemplateStructureFromSegmentsExperience**,  and I found that once changing and approving page and setting a breakpoint on where **updateLayoutPageTemplateStructureData** is called, it is not used. Also, inside that method, **_copyLayoutPageTemplateStructureFromSegmentsExperience**, no userId is ever used.

So, in this case, I do not think that we need to apply the changes there.

I also looked in to **LayoutWorkflowHandler.java** like you suggested and I agree that it would be the perfect spot to put this fix, however I am unsure how to go about doing something like that.
Since the original changes wrap the entire call to [updateLayoutPageTemplateStructureData](https://github.com/liferay/liferay-portal/blob/73f48d7172fef1b840cc776b4505aa6e318817fe/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/util/LayoutCopyHelperImpl.java#L366-L369) which happens later on in the process, I am unsure on how I could implement these changes in **LayoutWorkflowHandler**. I noticed that in **LayoutWorkflowHandler** there is a valid userId which is a start, but I do not think that I can find a fix that I will be able to implement in that file.

Let me know what you think about my findings!

**Comment by ericyanLr** [comment]
Hi @jakesliwka ,

Regarding:

> In **LayoutCopyHelperImpl**, I looked at where else **updateLayoutPageTemplateStructureData** was used to see if we should also apply the fix there.
> 
> It gets called in a separate method, **_copyLayoutPageTemplateStructureFromSegmentsExperience**,  and I found that once changing and approving page and setting a breakpoint on where **updateLayoutPageTemplateStructureData** is called, it is not used. Also, inside that method, **_copyLayoutPageTemplateStructureFromSegmentsExperience**, no userId is ever used.
> 
> So, in this case, I do not think that we need to apply the changes there.

Although the method **_copyLayoutPageTemplateStructureFromSegmentsExperience** may not have been hit for your particular use-case, the question would be whether this change would be needed for other use-cases that may be using this method, especially since the method call is similar to the one you are changing.

Regarding:

> I also looked in to **LayoutWorkflowHandler.java** like you suggested and I agree that it would be the perfect spot to put this fix, however I am unsure how to go about doing something like that.
> 
> Since the original changes wrap the entire call to [updateLayoutPageTemplateStructureData](https://github.com/liferay/liferay-portal/blob/73f48d7172fef1b840cc776b4505aa6e318817fe/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/util/LayoutCopyHelperImpl.java#L366-L369) which happens later on in the process, I am unsure on how I could implement these changes in **LayoutWorkflowHandler**. I noticed that in **LayoutWorkflowHandler** there is a valid userId which is a start, but I do not think that I can find a fix that I will be able to implement in that file.

From my understanding, your fix relies on: 
- Setting: **PrincipalThreadLocal.setName([userId]);**
- try block: execute code
- finally: reset the  **PrincipalThreadLocal.setName([userId]);**

For this case, my assumption would be that:
- Setting: **PrincipalThreadLocal.setName([userId]);**
- And then executing: **_layoutCopyHelper.copyLayout(draftLayout, layout);**
- finally: resetting: **PrincipalThreadLocal.setName([userId]);**

Would provide a similar result. (Though I haven't tested).
Hopefully that helps clarify things a bit.

**Comment by jakesliwka** [comment]
Hey @ericyanLr,
Thanks for explaining, it definitely makes more sense now.

I went in and tried applying the solution in LayoutWorkflowHandler and it worked, however the issue that comes to mind is that PrincipalThreadLocal gets used more in this version of the change than the original.
After setting **PrincipalTHreadLocal.setName(userId)** and setting a breakpoint in the **try** part of the code where **_layoutCopyHelper.copyLayout(draftLayout, layout);** is executed, **PrincipalThreadLocal** gets used more, which could potentially cause issues. 
With the initial solution, it was called by **getCTCollection** (production mode) and **MessageSenderJob** .
With this solution, both the above are used as normal (but seem to be called more often), but now addSystemEvent is called on top of that.

However, it makes more sense to have the solution here. I just can't tell whether or not it is safer.
What can you conclude from these results?

**Comment by ericyanLr** [comment]
Hi @jakesliwka ,

**Regarding:**

> I went in and tried applying the solution in LayoutWorkflowHandler and it worked, however the issue that comes to mind is that PrincipalThreadLocal gets used more in this version of the change than the original.
> 
> After setting PrincipalTHreadLocal.setName(userId) and setting a breakpoint in the try part of the code where _layoutCopyHelper.copyLayout(draftLayout, layout); is executed, PrincipalThreadLocal gets used more, which could potentially cause issues.

I'm not exactly sure what you mean by: "PrincipalThreadLocal gets used more, which could potentially cause issues." 

Are there actual concerns or is this just an initial observation?

**Regarding:**
> With the initial solution, it was called by getCTCollection (production mode) and MessageSenderJob .
> 
> With this solution, both the above are used as normal (but seem to be called more often), but now addSystemEvent is called on top of that.

I'm not exactly sure what you mean by: "With this solution, both the above are used as normal (but seem to be called more often), but now addSystemEvent is called on top of that."

Is there some concern you have regarding this difference in behavior or is this just an observation you noticed / wanted to share?

----

**Thoughts / Suggested Next Steps**
Hopefully, this helps address your question:

> However, it makes more sense to have the solution here. I just can't tell whether or not it is safer.
> What can you conclude from these results?


If for the most part, these are mainly observations and you now have concerns of what the effects of adding this change here would bring about, I would suggest to further analyze the existing use-cases more, to try to make sense of the workflow use-case you are working on.

As an example, analyzing the use-case of a regular publish (without single-approval enabled)
- e.g. seeing what service methods get called, seeing what userId is set in PrincipalThreadLocal, seeing whether PrincipalThreadLocal is changed throughout the way, etc.
- The hope would be that gaining more understanding of how a regular publish works and observing the parameters that are set, would help provide some clarity on how things should work when publishing via a workflow. 

Hopefully, with more analysis and investigations, you can gain a better understanding of how a publish should behave, even when a publish is being done via a workflow. And with that better understanding, I think it should help you feel more confident in deciding on a proposed solution. 

@noornajj , can you help check if I'm misunderstanding the situation? And if not, can you work with Jake on coming up with a Game Plan?

Feel free to let me know if I missed anything or if you have any further questions.

Thanks!

**Comment by noornajj** [comment]
Hi @ericyanLr,

When this fix was proposed to Jake, he was told to verify that nothing else is using the new userId that's being set to the PrincipalThreadLocal that could cause a regression. 
We set a break point in the PrincipalThreadLocal get methods and checked whether they are called in between running the try and finally blocks. We found that the userId is being called by getCTCollection which checks whether the user is in production or a publication. 
When the getCTCollectionId is being retrieved, it uses the userId from PrincipalThreadLocal. If we are currently in production, the ctCollectionId returned is 0 whether the userId being passed is correct or not. But if a publication is involved, then passing in the correct userId makes a difference. However, since workflow and publications do not work together, we were able to ignore this scenario.

What Jake is saying is after the try/finally block is moved to LayoutWorkflowHandler, the userId from PrincipalThreadLocal is now being utilized in a method call by addSystemEvent in between the try and finally blocks. 

@jakesliwka, you'll need to see what addSystemEvent is doing with the userId and whether changing it's value will impact that method.

**Comment by jakesliwka** [comment]
Hey @ericyanLr,
I followed the advice from @noornajj ] and looked around where PrincipalThreadLocal is used in addSystemEvent and wanted to update you on our findings.

It seems like this will not cause a regression, however I am not completely sure on anything yet and can't reach a conclusion. 

A new SystemEvent is being added using **PrincipalThreadLocal.getName** (which uses the changed userId) which is being called every time **deleteLayoutPageTemplateEntryFragmentEntryLinks** is used (which is located inside of LayoutCopyHelperImpl, **_copyLayoutPageTemplateStructure**).
It is not clear what this is being used for, but I suppose that it is a good sign that it is being called from **_copyLayoutPageTemplateStructure** and not from somewhere else.

What steps do you think we should take here?
If we can figure out what this SystemEvent is being used for, and if we can verify that the userId is not important in this scenario, this change should be safely to deploy.

**Comment by ericyanLr** [comment]
Hi @jakesliwka ,

**Regarding:**

> What steps do you think we should take here?
> If we can figure out what this SystemEvent is being used for, and if we can verify that the userId is not important in this scenario, this change should be safely to deploy.

If the uncertainty at the moment is how to further analyze the mentioned **addSystemEvent**, my suggestion would be similar to my previous comment; one option would be to compare it to a regular publish (without single-approval enabled).

Basically, is **addSystemEvent** also being used during a regular publish (without single-approval enabled)? With this, we can investigate questions, such as:
- What is the current behavior regarding **addSystemEvent** during a regular publish? 
- Does it differ from what we are observing when using workflow with our proposed changes?
- What is the userId that is set in the PrincipalThreadLocal during the publish? Does it get changed?
- etc.

**Comment by jakesliwka** [comment]
Hello @ericyanLr ,
I just went through and did some more debugging based off of your suggestions. Here are my results:

When testing it on a new site with no workflow enabled, it reaches addSystemEvent 3 times, and every time the userId that gets returned by PrincipalThreadLocal is the correct userId (**20125** is my user).

When testing it on the old site with our proposed changes, it reaches addSystemEvent once, and PrincipalThreadLocal returns **20125**.

When testing it on the old site **without** any changes, PrincipalThreadLocal returns **0**, which is what is causing the errors.

So, as we can see, both **with our proposed changes** and **on a fresh site without workflow**, the correct userId is stored in PrincipalThreadLocal (20125) when it reaches addSystemEvent, however **without** our changes and **with workflow enabled**, **0** is passed.

Do you think we can conclude anything from this?

**Comment by ericyanLr** [comment]
Hi @jakesliwka ,

**Regarding:**
> Do you think we can conclude anything from this?

I think from all the different debugging scenarios you've been doing, you should now have a variety of findings to help you better understand the state of things during a publish. And so, I would suggest looking at the overall publish process again, with these findings in mind, and you should now have a better picture of what's going on.

Referring back to the common scenario again of comparing: a regular publish vs a workflow publish
- If we can at least confirm that the workflow publish (with the proposed changes) now works the same or very similarly to a regular publish, I would say this observation would greatly increase our confidence in the proposed fixed.
- Or if there are noticeable differences or concerns that you still observe, then maybe we can look into this further on whether there needs to be additional changes or a different approach in solving this issue.

Hopefully this can help you come up with a clearer analysis regarding your proposed fix. If you feel uncertain on how to approach this, I'm sure Noor can help explore this with you as well.

Please let me know what you think and if you have any further questions.

**Comment by jakesliwka** [comment]
Hey @ericyanLr,

I went in and looked around to compare the differences of a regular publish without workflow and a publish with workflow (and our changes) enabled.

I found that they are both calling SystemEvent, and executing, in pretty much the exact same way:

Both call **_fragmentEntryLinkLocalService.deleteLayoutPageTemplateEntryFragmentEntryLinks** in method **_copyLayoutPageTemplateStructure** which leads to the **SystemEvent**.

They retrieve the same userId from PrincipalThreadLocal.

The only difference being the workflow one begins in LayoutWorkflowHandler and the other one does not even enter it, but that is expected behavior.

With this, I think that we can conclude that workflow publish works **very** similarly to a regular publish. I noted the main difference, but it is an expected behavior.

Let me know what you think!

**Comment by ericyanLr** [comment]
Hi @jakesliwka ,

That's great news, sounds like we now have a better understanding of the situation.

**Suggested Next Steps**
Can you work on creating a PR with your new proposed changes and send it to @noornajj for review?

I'll close out this PR.

Please let me know if you have any questions.
Thanks!

**Pull request closed without merging**
