### PR TITLE
LPS-172254 Check whether the layout is an Asset Display Page

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-172254

The issue here that the breadcrumbs widget in a display page template does not show the current site when the site only has private pages. This is due to the display page template being a "public layout" and therefore the layoutsPageCount will be the number of public pages available in the site. However, in this situation, the site does not have any public pages.
After fixing the logic for `_addGroupsBreadcrumbEntries`, the other issue that occurred is the rendering of the friendly URL. The incorrect servlet mapping is added to the URL for the same reason above. 

To fix the issue, I adjusted the logic for checking for public vs private layouts by taking into account whether the layout is an asset display.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Still taking a look at this PR, but wanted to share a question + observation so far:
- Observation:
  - I think `assetDisplay` boolean can be retrieved using: `layout.isTypeAssetDisplay()`
- Question: You mentioned that:
  > However, in this situation, the site does not have any public pages.
  - Does the logic still work, if the site has a mix of public and private pages?

**Comment by ericyanLr** [comment]
Closing out this PR while we wait for clarification from the Product Team.

**Pull request closed without merging**
