### PR TITLE
Lps 150838

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-150838

The issue here is that the Global portlet permissions were being overwritten when importing site preferences and a widget was scoped to the Global site. 
It was occurring due to the global site being passed [here](https://github.com/liferay/liferay-portal-ee/blob/b61b73224e3dbf621004761d7480b9a1184dd02d/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/lar/PortletDataContextImpl.java#L1488) as the new resource and being overwritten by the imported site's settings

To fix the issue, I added an if statement to see whether the portlet being updated belongs to the new site. To do that, I check whether the current site's groupId is the same as the portlet's scopeGroupId

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

I may be wrong, but to me this change looks a bit off, after seeing this code block: 
```
// Source and target group id

Map<Long, Long> groupIds =
    (Map<Long, Long>)portletDataContext.getNewPrimaryKeysMap(
        Group.class);

groupIds.put(
    portletDataContext.getSourceGroupId(),
    portletDataContext.getGroupId());
```
- Reference: https://github.com/liferay/liferay-portal/blob/7.4.3.19-ga19/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/controller/PortletImportControllerImpl.java#L1298-L1306

Usually, this type of map is used for relating the groupId of the exported LAR and the target Liferay instance.

Let's discuss about this more. In the meantime, I'll start a `ci:test` to see if there are any noticeable test failures from the other tests.

**Comment by ericyanLr** [comment]
ci:test

**Comment by jonathanmccann** [comment]
https://github.com/liferay-staging/liferay-portal/pull/49

**Comment by jonathanmccann** [comment]
ci:close

**Pull request closed without merging**
