### PR TITLE
LPS-145833 Set ddmFormFieldValue string to null when string is empty and ddmFormField is repeatable

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-145833

The issue here is that the system configurations for Redirect URL will save the allowed domains list as a list of size 1 with an empty string instead of a list of size 0. 
This was fixed by adding a condition to save the field value as null instead of the default value ("") when the field is repeatable.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

The changes looks good to me, just a couple suggestions:
- Can you create a test case for this? I think it would be helpful, in case future refactors accidentally undo this change.
  - There is an existing unit test for this class you are modifying: DDMFormValuesToPropertiesConverterTest
- Optimize this part of code:
  - Store the output of `_toSimpleValue(ddmFormFieldValue)` to a variable, so we don't have to process it twice
    - https://github.com/ericyanLr/liferay-portal/pull/257/commits/a58d656c9c844601cc37ecf8667fbb57b13d6082#diff-5838e9dde2c87adc6d2956b31186aa2640b18065a0996caf52fbb20042d126f0R264-R265 

Please let me know if you have any questions.
Thanks!

**Comment by ericyanLr** [comment]
Hi @noornajj ,

The changes looks good to me, just a couple suggestions:
- Can you create a test case for this? I think it would be helpful, in case future refactors accidentally undo this change.
  - There is an existing unit test for this class you are modifying: DDMFormValuesToPropertiesConverterTest
- Optimize this part of code:
  - Store the output of `_toSimpleValue(ddmFormFieldValue)` to a variable, so we don't have to process it twice
    - https://github.com/ericyanLr/liferay-portal/pull/257/commits/a58d656c9c844601cc37ecf8667fbb57b13d6082#diff-5838e9dde2c87adc6d2956b31186aa2640b18065a0996caf52fbb20042d126f0R264-R265 

Please let me know if you have any questions.
Thanks!

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Reviewed and forward to USM team: https://github.com/liferay-usm/liferay-portal/pull/487

**Note:** I made some changes to the test cases:
- Added extra assertions
- Renamed test cases to put more emphasis on the array and empty string

**Pull request closed without merging**
