### PR TITLE
Lps 146666

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-146666

The issue here was an infinite loop was caused when the default friendly URL was left empty. The reason this occurred is because the layoutId was being passed into layoutFriendlyURLEntryValidator.validateFriendlyURLEntry instead of the plid of the layout.
To fix the issue, I passed the layout's plid when the friendly URL being validated belongs to an already existing layout.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

I had a question regarding this part of your fix:
https://github.com/ericyanLr/liferay-portal/commit/f1bf2e8dc61ebd138cfe60f0a1af080a20846d98#diff-2106cd14cf1e16c4428313fa09752db440fe6eb78582af6bea05c9d06c379441R123-R127

Just wanted to confirm the reasoning for the if/else statement and whether running the validation method again using layoutId is intended.

Based on the ticket description:
> The reason this occurred is because the layoutId was being passed into layoutFriendlyURLEntryValidator.validateFriendlyURLEntry instead of the plid of the layout.

It sounded like using the layoutId was not correct, so just wanted to get more insight regarding this part of this fix.

Can you help take a look?
Thanks!

**Comment by noornajj** [comment]
Hi @ericyanLr,

My reasoning for the else statement is for when a new layout is being created. If a new layout is being created and validated, then the fetch layout method will return null and the friendly URL will not get validated through the validateFriendlyURLEntry() method. 
It doesn't really matter what value is passed actually. The reason for this value is to check whether the friendly URL being validated belongs to the same layout that the duplicate was found at. If it's the same layout (meaning a layout is getting updated), then no duplicate error is thrown. But since this scenario is for new layouts being created, so if a duplicate is found then we want an error to be thrown. This is the [code](https://github.com/liferay/liferay-portal/blob/64338273f5b930e05087d3d933bbdbddbcdd0440/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/service/impl/FriendlyURLEntryLocalServiceImpl.java#L557-L562) for that logic. 
Maybe it would make more sense to pass in a 0?

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Thanks for the explanation, I think I understand what you mean.

Here are a few suggestions I had in mind:
- Optimize: Move the fetchLayout service call out of the for loop (I think it only needs to be fetched once?)
  - https://github.com/ericyanLr/liferay-portal/pull/258/commits/f1bf2e8dc61ebd138cfe60f0a1af080a20846d98#diff-2106cd14cf1e16c4428313fa09752db440fe6eb78582af6bea05c9d06c379441R109-R111
- Split the commit into two commits:
  - To me, it looks like you're fixing 2 issues: 
    - Issue 1: The current logic is incorrect, since it's passing in the layoutId instead of the plid of the layout
    - Issue 2: The current logic does not properly handle validation when a new layout is being created
  - And so, I think having two commits would be helpful in better understanding the change.
- Revise the commit message to better explain what we're changing
  - Issue 1
    - I think your current message is for this issue and provides a description of the impact of this bug
    - But, I think it would be helpful if the commit message included an explanation that the wrong value is being passed in as the classPK
      - Could be as simple as: **plid should be used for the ClassPK, not layoutId**
- Additional Thoughts: Issue 2
  - You mentioned: **Maybe it would make more sense to pass in a 0?**
    - I think passing in **0** is reasonable
    - If we take a look at: [FriendlyURLEntryLocalServiceImpl.java#L565-L570](https://github.com/liferay/liferay-portal/blob/7.4.3.11-ga11/modules/apps/friendly-url/friendly-url-service/src/main/java/com/liferay/friendly/url/service/impl/FriendlyURLEntryLocalServiceImpl.java#L565-L570), we can see that there exists a validate method that doesn't require passing in a classPK, and it defaults it to 0.
  - Another option would be to modify the interface you created: [LayoutFriendlyURLEntryValidator.java](https://github.com/liferay/liferay-portal/blob/7.4.3.11-ga11/portal-kernel/src/com/liferay/portal/kernel/service/LayoutFriendlyURLEntryValidator.java)
    - We could add another method to validate, without requiring to pass in classPK
    - Adding this would allow us to call this new method to avoid passing in 0.
  - But, I think both approaches are fine
    - If you're not sure which one to go with, we can go with the simple one with passing in a 0
    - Just wanted to share the interface option, in case you think it would be useful to add

Please let me know what you think and if you have any questions.
Thanks!

**Pull request closed without merging**
