### PR TITLE
LPS-92701 Impossible to add image in message with page-scope, when virtual host is used

### PR DESCRIPTION
**Pull request by IstvanD**
Hey @ericyanLr 

Thank you your suggestion [here](https://issues.liferay.com/browse/PTR-753?focusedCommentId=1796225&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1796225), I managed to add a test case of site scoped layout with separate instance and site host names.
Please note that I was not necessary to create a further layout, since publicLayout is already create based on a Site Group, see https://github.com/liferay/liferay-portal/blob/master/portal-test/src/com/liferay/portal/kernel/test/util/GroupTestUtil.java#L109.

Could you please check it?

Thank you and best regards,
István

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @IstvanD ,

From my understanding, the added test would serve to represent the issue in LPS-92701, which would be resolved by your proposed fix.

But, during my testing, adding only your new test (excluding the fix) did not lead to a failed test. To me, this could mean a few things:

- The test does not fully represent the issue in LPS-92701
- The test creates the proper scenario, but does not test for the actual issue
- The test should be failing, but it just didn't fail on my machine

The way I usually utilize tests is:

1. Create a test(s) to represent the issue
2. Verify the created test(s) is failing (since this is a bug)
3. Create a fix for the issue
4. Verify the created test(s) are now running successfully (when the fix is included).

Please let me know your thoughts and if you have any further questions.
Hope that helps!

Best,
Eric

**Comment by IstvanD** [comment]
Hi @ericyanLr 

Thank you for your feedback.

I have used your prior [suggestions](https://issues.liferay.com/browse/PTR-866?focusedCommentId=1813834&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1813834) to create the test, but I'm afraid I have not enough knowledge of the component on the code level to mimic the behavior that exposes the bug.

Perhaps could you suggest someone who could help me to write the tests?

Thank you so much.

Best regards
István

**Comment by ericyanLr** [comment]
Hi @IstvanD ,

I will be on PTO the rest of the week, but if this is urgent, feel free to send it up to the next reviewer. If not, I can probably take a look at writing the test sometime next week.

Best,
Eric

**Comment by IstvanD** [comment]
Hi @ericyanLr 

I see. Let's get back to this next week.
Thank you and have a pleasant PTO.

**Comment by ericyanLr** [comment]
Hi @IstvanD ,

Thanks! Also wanted to give a quick update, currently working on the test.

**Comment by IstvanD** [comment]
Hi @ericyanLr 

Thank you for the update and for your extra work.

Best regards,
István

**Comment by ericyanLr** [comment]
Hi @IstvanD,

I have provided a response on the PTR ticket.

Feel free to let me know if you have any further questions.
Cheers!

**Pull request closed without merging**
