### PR TITLE
[TECNICAL SUPPORT] LPS-87075 Only add user tracker if node is master

### PR DESCRIPTION
**Pull request by amadeafejes**
Hi Eric,

I'm sending this pull again as I still believe this is a better way to solve the issue. However I got a suggestion from the User & System Management SME (see LPP-31934 for further information) but after I tried that different kind of approach I find that is not applicable easily.

Could you please review this pull request? If this pull is wrong in any reason could you please describe what is the concrete problem with it and could you please advise how to improve this fix?

Thank you in advance,
Amadea

Related LPS:
https://issues.liferay.com/browse/LPS-87075

### CODE REVIEW

**Comment by amadeafejes** [comment]
ci:test:sf

**Comment by amadeafejes** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @amadeafejes ,

**Overall Issue**
From my understanding, there is still quite a bit of confusion in regards to LiveUsers and it's expected behavior within a clustered environment.

I think it would be best if discussions with the User & System Management team can eventually lead to a clear understanding of how LiveUsers is supposed to operate within a clustered environment.

For example:
- Understanding why LiveUsers keeps track of each node within a cluster
- Understanding what is expected to occur when a user signs in/out on a node within a cluster
  - e.g. Is it expected that we let every node know or only the master node or only the node itself?
- Determining whether LiveUsers actually supports clustering in the first place

**Regarding the actual fix**
In regards to the actual fix, from my understanding, the proposed change would make it so that if this code is executed on a slave node (not master), nothing will happen. But, if this code is executed on master, only then will it be executed.

Again, I'm not familiar with how LiveUsers utilizes cluster communication, so I just wanted to make sure that the resulting outcome above is what you are trying to accomplish.

**Regarding this pr**
In regards to the pr, I think your main goal is mainly to make sure the code executes once. And your current approach is to make it so that only the master node will be able to execute this code.

Whether this is the correct approach or not, I think this would be best decided by the User & System Management team.

So for this pr, I think it would be best if it was instead reviewed by the User & System Management team.

However, feel free to reach out if there's any clarifications regarding clustering that I can help with.
Hope that helps!

Thanks!

**Comment by amadeafejes** [comment]
Hi Eric,

Thanks, forwarded to https://github.com/ChrisKian/liferay-portal/pull/81

**Pull request closed without merging**
