### PR TITLE
[TS] LPS-117030 Use String model factory in Freemarker templates

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Hi @ericyanLr ,

Please review my fix, and if you approve this change, please forward it to the next approver,
Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

I did not have time to today to look over this pr, hopefully I'll have some time tomorrow.

**Comment by ericyanLr** [comment]
Hi @peterpetrekanics ,

I took a look at this issue and it looks like this new behavior doesn't only apply to java.lang.String. 

For example, if we follow the steps to reproduce and also include the following in the template:
```
<#assign companyId = themeDisplay.getCompanyId().longValue()/>
${companyId}
```

You will notice that the same error will occur for java.lang.Long as well.

## Explanation
As you mentioned, this issue starting occurring after [LPS-110849](https://issues.liferay.com/browse/LPS-110849).

With the commits from this ticket, it looks like the Object Wrapper being used has changed:
- **From:** freemarker.ext.beans.BeansWrapper
- **To:** com.liferay.portal.template.freemarker.internal.RestrictedLiferayObjectWrapper

One thing to note here is that RestrictedLiferayObjectWrapper extends LiferayObjectWrapper, which extends: **DefaultObjectWrapper**

Basically, the main change is that **DefaultObjectWrapper** is now used instead of **BeansWrapper**

If we take a look at this [Freemarker Documentation](https://freemarker.apache.org/docs/pgui_misc_beanwrapper.html), it mentions a consideration when choosing between the two:

> You will want to use BeansWrapper instead of DefaultObjectWrapper when any of these stands:
> 
> - The Collection-s and Map-s of the model should be allowed to be modified during template execution. (DefaultObjectWrapper prevents that, since it creates a copy of the collections when they are wrapped, and the copies will be read-only.)
> 
> - If the identity of the array, Collection and Map objects must be kept when they are passed to a wrapped object's method in the template. That is, if those methods must get exactly the same object that was earlier wrapped.
> 
> - **If the Java API of the earlier listed classes (String, Map, List ...etc) should be visible for the templates. Even with BeansWrapper, they are not visible by default, but it can be achieved by setting the exposure level (see later). Note that this is usually a bad practice; try to use the built-ins (like foo?size, foo?upper_case, foo?replace('_', '-') ...etc) instead of the Java API.**
> 

If we take a look at the last line, it mentions Java API of classes like String. They instead recommend using built-ins.


## Solution/Workaround?

So for this ticket's particular steps to reproduce, replacing `<#assign themeId = themeDisplay.getThemeId().toUpperCase()/>` with `<#assign themeId = themeDisplay.getThemeId()?upper_case/>` provides the proper result.

As another example, replacing `<#assign companyId = themeDisplay.getCompanyId().longValue()/>` with `<#assign companyId = themeDisplay.getCompanyId()?long/>` provides the proper result.

Here is a reference to Freemarker's built-ins: 
https://freemarker.apache.org/docs/ref_builtins.html

**Note:** You may need to clear your caches after updating the template

## Thoughts
Basically, using built-ins would resolve the issue for this ticket. 

If that's not an acceptable solution, I would suggest:
- Investigating whether the current switch of Object Wrappers is expected behavior
  - If not, maybe the fix should be for that instead
- If you do decide you want to go with your current approach, analyze whether the fix should also account for other affected classes
  - Here, we can see a kind of comparison between the two:
    - BeansWrapper: https://github.com/apache/freemarker/blob/v2.3.28/src/main/java/freemarker/ext/beans/BeansWrapper.java#L970-L999
    - DefaultObjectWrapper: https://github.com/apache/freemarker/blob/v2.3.28/src/main/java/freemarker/template/DefaultObjectWrapper.java#L180-L249
- Also, feel free to create a PTR ticket if needed. 

Feel free to let me know if you have any questions.
Hope that helps you move forward with your investigation.

**Comment by lipusz** [comment]
Hello Eric, @ericyanLr

Thank you for the detailed analysis

Because of the nature of the cause fix and the technical detials, I'd like to ask you to move this comment to Peter's JIRA ticket with liferay-staff visibility and delete your comment from here.

Thanks,
Tibi

**Pull request closed without merging**
