### PR TITLE
[TS] LPS-88338

### PR DESCRIPTION
**Pull request by istvansajtos**
[LPS-88338](https://issues.liferay.com/browse/LPS-88338)

Hi Eric,

I hope you can review my changes. 

We were talking about the issue in the past in frame of [PTR-725](https://issues.liferay.com/browse/PTR-725). Sorry for sending the PR only after such a long time, but eliminating certain test failures caused some headache for me.

**Issue:**
In short, the check introduced by [LPS-71409](https://issues.liferay.com/browse/LPS-71409) doesn't work on Wildfly / JBoss EAP/ WebSphere because we don't follow the [Servlet 3 specification](https://download.oracle.com/otn-pub/jcp/servlet-3.0-fr-eval-oth-JSpec/servlet-3_0-final-spec.pdf) when accessing the originally sent request parameters on dispatched requests. (Dispatched requests may have different parameters than the original.)

Using the PortalUtil.getOriginalServletRequest(HttpServletRequest) to access the properties of the request originally sent from the browser is a wrong approach.

**Technical Background:**
The issue originates from the incorrect assumption that PortalImpl.getOriginalServletRequest(HttpServletRequest) returns the "original request" carrying the URL, query string, etc. as it comes from the browser.

The request (in recent scenario a RenderRequest) we want to use to retrieve the original URL and query string is wrapped multiple times and went through several RequestDispatchers. I found no info in [Servlet 3 specification](https://download.oracle.com/otn-pub/jcp/servlet-3.0-fr-eval-oth-JSpec/servlet-3_0-final-spec.pdf) what to expect from the current approach of unwrapping the "original request" (in PortalImpl.getOriginalServletRequest(HttpServletRequest)). I found, however, the description of how to access the properties of the "original request" (facing the very first servlet) in case of forwarded/included requests.

> 9.3.1 Included Request Parameters
> 
> ...
> 
> The following request attributes must be set:
> 
> javax.servlet.include.request_uri
> javax.servlet.include.context_path
> javax.servlet.include.servlet_path
> javax.servlet.include.path_info
> javax.servlet.include.query_string
> 
> These attributes are accessible from the included servlet via the getAttribute method on the request object and their values must be equal to the request URI, context path, servlet path, path info, and query string of the included servlet, respectively. If the request is subsequently included, these attributes are replaced for that include.

> 9.4.2 Forwarded Request Parameters
> 
> ...
> 
> The following request attributes must be set:
> 
> javax.servlet.forward.request_uri
> javax.servlet.forward.context_path
> javax.servlet.forward.servlet_path
> javax.servlet.forward.path_info
> javax.servlet.forward.query_string
> 
> The values of these attributes must be equal to the return values of the HttpServletRequest methods getRequestURI, getContextPath, getServletPath, getPathInfo, getQueryString respectively, invoked on the request object passed to the first servlet object in the call chain that received the request from the client.
> These attributes are accessible from the forwarded servlet via the getAttribute method on the request object. Note that these attributes must always reflect the information in the original request even under the situation that multiple forwards and subsequent includes are called.

**How I understand the spec:**
If the request was forwarded, then the properties (request URI, context path, servlet path, path_info, query_string) of the originally sent request are preserved by the javax.servlet.forward.* attributes. For included request we can call the getter methods directly on the request as they return the values belonging to the originally sent request. That is, we have to handle distinctively only the case of forwarded requests.

**FYI**, LPS-94230 had basically the same root cause and I used the same approach to fix it.

Please let me know what you think about my changes.

Thank you,
István

### CODE REVIEW

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Also triggering security suite

**Comment by lipusz** [comment]
ci:test:security

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by istvansajtos** [comment]
ci:test:security

**Comment by lipusz** [comment]
:white_check_mark: Regarding the weird SAML failures: as per @dellawang in https://liferay.slack.com/archives/GLA3KMB32/p1594022858001000
> There's a known issue about page crash [LRCI-1048](https://issues.liferay.com/browse/LRCI-1048).

**Comment by ericyanLr** [comment]
Hi @istvansajtos ,

Just wanted to let you know I took a look at this PR today and will continue reviewing tomorrow.

Best,
Eric

**Comment by ericyanLr** [comment]
Hi @istvansajtos ,

Thanks for your analysis, findings, and detailed notes. It was really helpful in understanding the situation and passing on the PR to the next reviewer.

I have forwarded your PR to Shuyang for further review: https://github.com/shuyangzhou/liferay-portal/pull/9242

**Comment by ericyanLr** [comment]
Hi @istvansajtos ,

I closed the PR to Shuyang to verify one thing I noticed.

Can you help verify whether this is an oversight or whether this logic is just no longer needed.

Your changes modifies the current logic of retrieving the queryString from PortalUtil.getOriginalServletRequest(HttpServletRequest), even if it's not a Forwarded request.

**Before your changes:**
```
httpServletRequest = PortalUtil.getOriginalServletRequest(
    httpServletRequest);

String queryString = httpServletRequest.getQueryString();
```

**After your changes:**
```
if (PortalUtil.isForwarded(httpServletRequest)) {
    queryString = (String)httpServletRequest.getAttribute(
        JavaConstants.JAVAX_SERVLET_FORWARD_QUERY_STRING);
}
else {
    queryString = httpServletRequest.getQueryString();
}

httpServletRequest = PortalUtil.getOriginalServletRequest(
    httpServletRequest);
```

As you can see, if the request is not forwarded, it no longer utilizes the retrieved request from `PortalUtil.getOriginalServletRequest(httpServletRequest);` to retrieve the queryString from the unwrapped request.

**Question**
I'm not sure whether this was an oversight or if this is just no longer needed.

Also, if you happen to need to make changes, just wanted to suggest that for the 2nd commit (https://github.com/ericyanLr/liferay-portal/pull/188/commits/a56ae620c38322d721118aa8a6fef997ebd4ab5c), it would be nice if we can move the changes for LoginMVCActionCommand to the 3rd commit (https://github.com/ericyanLr/liferay-portal/pull/188/commits/95889c4d8283b1bbf4fbb3c24de3b1501f645144)
- This would just make the 2nd commit a little more easy to understand
- And the changes to LoginMVCActionCommand seem to fit more with the 3rd commit's commit message

Please let me know if you have any questions.
Thanks!

**Comment by istvansajtos** [comment]
Hi @ericyanLr ,

> Your changes modifies the current logic of retrieving the queryString from PortalUtil.getOriginalServletRequest(HttpServletRequest), even if it's not a Forwarded request.
> 
> **Before your changes:**
> 
> ```
> httpServletRequest = PortalUtil.getOriginalServletRequest(
>     httpServletRequest);
> 
> String queryString = httpServletRequest.getQueryString();
> ```
> 
> **After your changes:**
> 
> ```
> if (PortalUtil.isForwarded(httpServletRequest)) {
>     queryString = (String)httpServletRequest.getAttribute(
>         JavaConstants.JAVAX_SERVLET_FORWARD_QUERY_STRING);
> }
> else {
>     queryString = httpServletRequest.getQueryString();
> }
> 
> httpServletRequest = PortalUtil.getOriginalServletRequest(
>     httpServletRequest);
> ```
> 
> As you can see, if the request is not forwarded, it no longer utilizes the retrieved request from `PortalUtil.getOriginalServletRequest(httpServletRequest);` to retrieve the queryString from the unwrapped request.
> 
> **Question**
> I'm not sure whether this was an oversight or if this is just no longer needed.

I am glad for your observation because double-checking what the servlet spec says, the included case doesn't look good indeed. BTW, as I remember from my previous tests, the use of PortalUtil.getOriginalServletRequest(httpServletRequest) is wrong for both dispatch methods. And I am not even sure we have to handle the included case, because if login URL is guaranteed to be friendly, then FriendlyURLServlet will always forward dispatch the request. I will investigate this case a little bit anyway.

> Also, if you happen to need to make changes, just wanted to suggest that for the 2nd commit ([a56ae62](https://github.com/ericyanLr/liferay-portal/commit/a56ae620c38322d721118aa8a6fef997ebd4ab5c)), it would be nice if we can move the changes for LoginMVCActionCommand to the 3rd commit ([95889c4](https://github.com/ericyanLr/liferay-portal/commit/95889c4d8283b1bbf4fbb3c24de3b1501f645144))
> 
> * This would just make the 2nd commit a little more easy to understand
> * And the changes to LoginMVCActionCommand seem to fit more with the 3rd commit's commit message

I completely agree on this. I will update the commits according to your suggestion.

Thank you!

**Comment by ericyanLr** [comment]
Hi @istvansajtos ,

Thanks for double-checking.

**Regarding:**

> I am glad for your observation because double-checking what the servlet spec says, the included case doesn't look good indeed.

I'm not exactly sure what you mean by this, hopefully it's not too bad haha.

**Regarding:**

> BTW, as I remember from my previous tests, the use of PortalUtil.getOriginalServletRequest(httpServletRequest) is wrong for both dispatch methods. 

I see what you mean, it's possible that the previous fix only utilized PortalUtil.getOriginalServletRequest(httpServletRequest) to handle the Forwarded requests, which your new fix now handles.

**Regarding:**

> And I am not even sure we have to handle the included case, because if login URL is guaranteed to be friendly, then FriendlyURLServlet will always forward dispatch the request. I will investigate this case a little bit anyway.

I observed this as well. 

In case you wanted to debug test this a bit further, I crafted this link during my testing, to try to skip the forward dispatches:
- http://localhost:8080/c/portal/layout?p_l_id=9&p_v_l_s_g_id=0&p_p_id=com_liferay_login_web_portlet_LoginPortlet&p_p_lifecycle=1&p_p_state=exclusive&p_p_mode=view&_com_liferay_login_web_portlet_LoginPortlet_javax.portlet.action=%2Flogin%2Flogin&_com_liferay_login_web_portlet_LoginPortlet_mvcRenderCommandName=%2Flogin%2Flogin&_com_liferay_login_web_portlet_LoginPortlet_login=test@liferay.com&_com_liferay_login_web_portlet_LoginPortlet_password=asdf&p_auth=w6FDcMcB
    - **Note:** Would need to update the p_auth value for your session

**Additional Thoughts**

I think as long as the changes still handles the previous fix's ticket and it's related regression bug tickets, that should be a good enough sign.

Your fix is technically to improve upon the previous fix anyways.

Thanks again for double-checking!

**Comment by istvansajtos** [comment]
Hi @ericyanLr , 

Thanks for all the help! I will resend the PR early next.

Regards,
Istvan

**Pull request closed without merging**
