### PR TITLE
LPS-106586 Escape the properties to be exported

### PR DESCRIPTION
**Pull request by hudakl**
Hi Eric,

Based on are discussion, I've updated the fix to use the LocationVariableResolver. I'm not entirelly sure if that's the correct way to do it. Please feel free to rearrange it as you see fit.

I also didn't add the test yet, as it would depend on how the solution itself would look, and I'm not sure how the test cases should be updated, in light of the new requirements.

Thanks,
Laci

### CODE REVIEW

**Comment by ericyanLr** [comment]
Hi @hudakl,

I took a look at your proposed solution and have a couple suggestions:

- Move the logic back to ExportConfigurationMVCResourceCommand
- Provide a more description name for the method

**Move the logic back to ExportConfigurationMVCResourceCommand**
In the previous PRs, I suggested moving the logic to the ConfigurationExporter class, since I felt the issue/bug was related more to the OSGI side of the configuration.

But, after our discussion with the USM team, the issue/bug is now more related to Liferay's configuration export side.

With that in mind, I feel it would make more sense to include it in Liferay's configuration export side, which resides in ExportConfigurationMVCResourceCommand.

**Provide a more description name for the method**
Also, I would suggest providing a more descriptive name for the method, so it'll be easier for others to understand what this method is doing.

----

**Test?**
With the new requirements, the changes are much more defined now and more narrowly scoped. Also, I believe this fix would be better suited to be reviewed by the USM team. 

With that said, I'm not sure if the USM team would require tests or not for this type of change. And so, I think it should be your decision as to whether you want to include tests or not.

--
If you do choose to include tests though, I think it would be best to create a new test class: **ExportConfigurationMVCResourceCommandTest**. 

This test class does not exist yet, but I think it would make sense to create a test class for the actual MVC Resource action with the new requirements, instead of trying to handle it in the ConfigurationExportImportTest.

With the new requirements, a few possible test cases could be:
- String value that contains only a location variable
- String value that starts with a location variable
- String value that ends with a location variable
- String value that contains a location variable
- String array, with the same conditions above

For examples of such test classes, you can search for filenames that end with **MVCResourceCommandTest**, such as: **GetAnalyticsReportsTotalViewsMVCResourceCommandTest**.

**Note:** This type of test would probably take more work, as it would probably involve creating a few mock objects. 

Also, feel free to ask team members if they think there's a simpler or more preferred way of preparing this test. 

Again, I'll leave the decision of whether to include tests to you.

Feel free to let me know if you have any questions.
Hope that helps!

**Comment by hudakl** [comment]
Thank you for your reply! As I will be on holiday on Monday, I can make the changes on Tuesday.

**Comment by ericyanLr** [comment]
Hi @hudakl ,

**Regarding my initial comment:**

> Again, I'll leave the decision of whether to include tests to you.

I thought about it some more and I think we should actually create a test for it, especially since this involves exporting OSGI configs. The test could help to prevent regression bugs that may occur in the future, regarding OSGI config exports.

From what I can tell, this test is a bit more difficult to create, especially since the test file hasn't been created it yet and the structure of test class that would be needed.

**Note:** If you do not have bandwidth or this is urgent or etc., feel free to let me know and I can always help with creating the test or provide guidance on creating the test as well.

I'll include my notes from my previous comment on suggestions to create the test below.

Please let me know your thoughts.
Thanks!

----
**Suggestions for creating the Test**
I think it would be best to create a new test class: **ExportConfigurationMVCResourceCommandTest**.

This test class does not exist yet, but I think it would make sense to create a test class for the actual MVC Resource action with the new requirements, instead of trying to handle it in the ConfigurationExportImportTest.

With the new requirements, a few possible test cases could be:

String value that contains only a location variable
String value that starts with a location variable
String value that ends with a location variable
String value that contains a location variable
String array, with the same conditions above

For examples of such test classes, you can search for filenames that end with **MVCResourceCommandTest**, such as: **GetAnalyticsReportsTotalViewsMVCResourceCommandTest**.

**Note:** This type of test would probably take more work, as it would probably involve creating a few mock objects.

**Comment by georgel-pop-lr** [comment]
Hi @ericyanLr  and @hudakl,

I understand the need for a perfect solution with tests.
My question would be if this solution is enough for a hotfix to the client version? 

Regards.

**Comment by ericyanLr** [comment]
Hi @georgel-pop-lr ,

**Context**
I would refer to the note section I mentioned on my previous comment:

> **Note:** If you do not have bandwidth or this is urgent or etc., feel free to let me know and I can always help with creating the test or provide guidance on creating the test as well.

With that said, that also applies to you as well.

**Thoughts**
Basically, our work on this ticket, whether we can take our time to create the final solution or expedite it, can change depending on the situation, such as whether there is any urgency and/or bandwidth issues.

As for you question regarding a hotfix, from my understanding, this depends on the TS department and which particular office. I would say for this particular question, it could be discussed with a senior team member and/or lead.

----
Feel free to let us know how this current fix may be affecting your current customer ticket and we can adjust our game plan for this fix accordingly.

As for TS related questions regarding hotfixes, again, the decision whether a hotfix can be delivered, mostly lies with your team from my understanding. If this is not actually the case or if there's still confusion regarding this topic, please let me know and we can reach out to the proper channels to address this issue.

Thanks!

**Pull request closed without merging**
