### PR TITLE
LPS-160922 Add ability to configure search results template

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-160922

The issue here is that the Search Results portlet couldn't be configured to a custom template through the system settings. 
To fix this issue, I added a bean declaration for the SearchResultsPortletInstanceConfiguration class.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
Hi @noornajj ,

Since you are the one adding the class, let's change the author to your name.

Please let me know if you have any questions.
Thanks!

**Comment by noornajj** [comment]
Oh yeah! I forgot to update that.
Thanks @ericyanLr

**Comment by ericyanLr** [comment]
Reviewed and sent to Search Team for further review: https://github.com/liferay-search/liferay-portal/pull/530

**Pull request closed without merging**
